// Code generated by ent, DO NOT EDIT.

package oauthclient

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the oauthclient type in the database.
	Label = "oauth_client"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldClientID holds the string denoting the client_id field in the database.
	FieldClientID = "client_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldClientSecretHash holds the string denoting the client_secret_hash field in the database.
	FieldClientSecretHash = "client_secret_hash"
	// FieldRedirectUris holds the string denoting the redirect_uris field in the database.
	FieldRedirectUris = "redirect_uris"
	// FieldAllowedScopes holds the string denoting the allowed_scopes field in the database.
	FieldAllowedScopes = "allowed_scopes"
	// FieldPkceRequired holds the string denoting the pkce_required field in the database.
	FieldPkceRequired = "pkce_required"
	// FieldDefaultGroupID holds the string denoting the default_group_id field in the database.
	FieldDefaultGroupID = "default_group_id"
	// FieldAccessTokenTTLSeconds holds the string denoting the access_token_ttl_seconds field in the database.
	FieldAccessTokenTTLSeconds = "access_token_ttl_seconds"
	// FieldRefreshTokenTTLSeconds holds the string denoting the refresh_token_ttl_seconds field in the database.
	FieldRefreshTokenTTLSeconds = "refresh_token_ttl_seconds"
	// FieldDisabled holds the string denoting the disabled field in the database.
	FieldDisabled = "disabled"
	// FieldClientType holds the string denoting the client_type field in the database.
	FieldClientType = "client_type"
	// FieldAppType holds the string denoting the app_type field in the database.
	FieldAppType = "app_type"
	// FieldTrustedFirstParty holds the string denoting the trusted_first_party field in the database.
	FieldTrustedFirstParty = "trusted_first_party"
	// FieldDefaultScopes holds the string denoting the default_scopes field in the database.
	FieldDefaultScopes = "default_scopes"
	// FieldAllowedGroupIds holds the string denoting the allowed_group_ids field in the database.
	FieldAllowedGroupIds = "allowed_group_ids"
	// FieldAllowedOrigins holds the string denoting the allowed_origins field in the database.
	FieldAllowedOrigins = "allowed_origins"
	// FieldLogoutRedirectUris holds the string denoting the logout_redirect_uris field in the database.
	FieldLogoutRedirectUris = "logout_redirect_uris"
	// FieldDeviceFlowEnabled holds the string denoting the device_flow_enabled field in the database.
	FieldDeviceFlowEnabled = "device_flow_enabled"
	// FieldAllowRefreshWithoutOfflineAccess holds the string denoting the allow_refresh_without_offline_access field in the database.
	FieldAllowRefreshWithoutOfflineAccess = "allow_refresh_without_offline_access"
	// FieldIconURL holds the string denoting the icon_url field in the database.
	FieldIconURL = "icon_url"
	// FieldHomepageURL holds the string denoting the homepage_url field in the database.
	FieldHomepageURL = "homepage_url"
	// FieldPrivacyURL holds the string denoting the privacy_url field in the database.
	FieldPrivacyURL = "privacy_url"
	// FieldTermsURL holds the string denoting the terms_url field in the database.
	FieldTermsURL = "terms_url"
	// FieldSigningAlgorithm holds the string denoting the signing_algorithm field in the database.
	FieldSigningAlgorithm = "signing_algorithm"
	// Table holds the table name of the oauthclient in the database.
	Table = "oauth_clients"
)

// Columns holds all SQL columns for oauthclient fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldClientID,
	FieldName,
	FieldClientSecretHash,
	FieldRedirectUris,
	FieldAllowedScopes,
	FieldPkceRequired,
	FieldDefaultGroupID,
	FieldAccessTokenTTLSeconds,
	FieldRefreshTokenTTLSeconds,
	FieldDisabled,
	FieldClientType,
	FieldAppType,
	FieldTrustedFirstParty,
	FieldDefaultScopes,
	FieldAllowedGroupIds,
	FieldAllowedOrigins,
	FieldLogoutRedirectUris,
	FieldDeviceFlowEnabled,
	FieldAllowRefreshWithoutOfflineAccess,
	FieldIconURL,
	FieldHomepageURL,
	FieldPrivacyURL,
	FieldTermsURL,
	FieldSigningAlgorithm,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	ClientIDValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultPkceRequired holds the default value on creation for the "pkce_required" field.
	DefaultPkceRequired bool
	// DefaultAccessTokenTTLSeconds holds the default value on creation for the "access_token_ttl_seconds" field.
	DefaultAccessTokenTTLSeconds int
	// DefaultRefreshTokenTTLSeconds holds the default value on creation for the "refresh_token_ttl_seconds" field.
	DefaultRefreshTokenTTLSeconds int
	// DefaultDisabled holds the default value on creation for the "disabled" field.
	DefaultDisabled bool
	// DefaultClientType holds the default value on creation for the "client_type" field.
	DefaultClientType string
	// ClientTypeValidator is a validator for the "client_type" field. It is called by the builders before save.
	ClientTypeValidator func(string) error
	// DefaultAppType holds the default value on creation for the "app_type" field.
	DefaultAppType string
	// AppTypeValidator is a validator for the "app_type" field. It is called by the builders before save.
	AppTypeValidator func(string) error
	// DefaultTrustedFirstParty holds the default value on creation for the "trusted_first_party" field.
	DefaultTrustedFirstParty bool
	// DefaultDefaultScopes holds the default value on creation for the "default_scopes" field.
	DefaultDefaultScopes []string
	// DefaultAllowedOrigins holds the default value on creation for the "allowed_origins" field.
	DefaultAllowedOrigins []string
	// DefaultLogoutRedirectUris holds the default value on creation for the "logout_redirect_uris" field.
	DefaultLogoutRedirectUris []string
	// DefaultDeviceFlowEnabled holds the default value on creation for the "device_flow_enabled" field.
	DefaultDeviceFlowEnabled bool
	// DefaultAllowRefreshWithoutOfflineAccess holds the default value on creation for the "allow_refresh_without_offline_access" field.
	DefaultAllowRefreshWithoutOfflineAccess bool
	// DefaultSigningAlgorithm holds the default value on creation for the "signing_algorithm" field.
	DefaultSigningAlgorithm string
	// SigningAlgorithmValidator is a validator for the "signing_algorithm" field. It is called by the builders before save.
	SigningAlgorithmValidator func(string) error
)

// OrderOption defines the ordering options for the OAuthClient queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByClientID orders the results by the client_id field.
func ByClientID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByClientSecretHash orders the results by the client_secret_hash field.
func ByClientSecretHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientSecretHash, opts...).ToFunc()
}

// ByPkceRequired orders the results by the pkce_required field.
func ByPkceRequired(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPkceRequired, opts...).ToFunc()
}

// ByDefaultGroupID orders the results by the default_group_id field.
func ByDefaultGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDefaultGroupID, opts...).ToFunc()
}

// ByAccessTokenTTLSeconds orders the results by the access_token_ttl_seconds field.
func ByAccessTokenTTLSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccessTokenTTLSeconds, opts...).ToFunc()
}

// ByRefreshTokenTTLSeconds orders the results by the refresh_token_ttl_seconds field.
func ByRefreshTokenTTLSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefreshTokenTTLSeconds, opts...).ToFunc()
}

// ByDisabled orders the results by the disabled field.
func ByDisabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisabled, opts...).ToFunc()
}

// ByClientType orders the results by the client_type field.
func ByClientType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientType, opts...).ToFunc()
}

// ByAppType orders the results by the app_type field.
func ByAppType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAppType, opts...).ToFunc()
}

// ByTrustedFirstParty orders the results by the trusted_first_party field.
func ByTrustedFirstParty(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTrustedFirstParty, opts...).ToFunc()
}

// ByDeviceFlowEnabled orders the results by the device_flow_enabled field.
func ByDeviceFlowEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeviceFlowEnabled, opts...).ToFunc()
}

// ByAllowRefreshWithoutOfflineAccess orders the results by the allow_refresh_without_offline_access field.
func ByAllowRefreshWithoutOfflineAccess(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAllowRefreshWithoutOfflineAccess, opts...).ToFunc()
}

// ByIconURL orders the results by the icon_url field.
func ByIconURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIconURL, opts...).ToFunc()
}

// ByHomepageURL orders the results by the homepage_url field.
func ByHomepageURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHomepageURL, opts...).ToFunc()
}

// ByPrivacyURL orders the results by the privacy_url field.
func ByPrivacyURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrivacyURL, opts...).ToFunc()
}

// ByTermsURL orders the results by the terms_url field.
func ByTermsURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTermsURL, opts...).ToFunc()
}

// BySigningAlgorithm orders the results by the signing_algorithm field.
func BySigningAlgorithm(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSigningAlgorithm, opts...).ToFunc()
}
