// Code generated by ent, DO NOT EDIT.

package oauthclient

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldUpdatedAt, v))
}

// ClientID applies equality check predicate on the "client_id" field. It's identical to ClientIDEQ.
func ClientID(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldClientID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldName, v))
}

// ClientSecretHash applies equality check predicate on the "client_secret_hash" field. It's identical to ClientSecretHashEQ.
func ClientSecretHash(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldClientSecretHash, v))
}

// PkceRequired applies equality check predicate on the "pkce_required" field. It's identical to PkceRequiredEQ.
func PkceRequired(v bool) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldPkceRequired, v))
}

// DefaultGroupID applies equality check predicate on the "default_group_id" field. It's identical to DefaultGroupIDEQ.
func DefaultGroupID(v int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldDefaultGroupID, v))
}

// AccessTokenTTLSeconds applies equality check predicate on the "access_token_ttl_seconds" field. It's identical to AccessTokenTTLSecondsEQ.
func AccessTokenTTLSeconds(v int) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldAccessTokenTTLSeconds, v))
}

// RefreshTokenTTLSeconds applies equality check predicate on the "refresh_token_ttl_seconds" field. It's identical to RefreshTokenTTLSecondsEQ.
func RefreshTokenTTLSeconds(v int) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldRefreshTokenTTLSeconds, v))
}

// Disabled applies equality check predicate on the "disabled" field. It's identical to DisabledEQ.
func Disabled(v bool) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldDisabled, v))
}

// ClientType applies equality check predicate on the "client_type" field. It's identical to ClientTypeEQ.
func ClientType(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldClientType, v))
}

// AppType applies equality check predicate on the "app_type" field. It's identical to AppTypeEQ.
func AppType(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldAppType, v))
}

// TrustedFirstParty applies equality check predicate on the "trusted_first_party" field. It's identical to TrustedFirstPartyEQ.
func TrustedFirstParty(v bool) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldTrustedFirstParty, v))
}

// DeviceFlowEnabled applies equality check predicate on the "device_flow_enabled" field. It's identical to DeviceFlowEnabledEQ.
func DeviceFlowEnabled(v bool) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldDeviceFlowEnabled, v))
}

// AllowRefreshWithoutOfflineAccess applies equality check predicate on the "allow_refresh_without_offline_access" field. It's identical to AllowRefreshWithoutOfflineAccessEQ.
func AllowRefreshWithoutOfflineAccess(v bool) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldAllowRefreshWithoutOfflineAccess, v))
}

// IconURL applies equality check predicate on the "icon_url" field. It's identical to IconURLEQ.
func IconURL(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldIconURL, v))
}

// HomepageURL applies equality check predicate on the "homepage_url" field. It's identical to HomepageURLEQ.
func HomepageURL(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldHomepageURL, v))
}

// PrivacyURL applies equality check predicate on the "privacy_url" field. It's identical to PrivacyURLEQ.
func PrivacyURL(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldPrivacyURL, v))
}

// TermsURL applies equality check predicate on the "terms_url" field. It's identical to TermsURLEQ.
func TermsURL(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldTermsURL, v))
}

// SigningAlgorithm applies equality check predicate on the "signing_algorithm" field. It's identical to SigningAlgorithmEQ.
func SigningAlgorithm(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldSigningAlgorithm, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldUpdatedAt, v))
}

// ClientIDEQ applies the EQ predicate on the "client_id" field.
func ClientIDEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldClientID, v))
}

// ClientIDNEQ applies the NEQ predicate on the "client_id" field.
func ClientIDNEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldClientID, v))
}

// ClientIDIn applies the In predicate on the "client_id" field.
func ClientIDIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldClientID, vs...))
}

// ClientIDNotIn applies the NotIn predicate on the "client_id" field.
func ClientIDNotIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldClientID, vs...))
}

// ClientIDGT applies the GT predicate on the "client_id" field.
func ClientIDGT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldClientID, v))
}

// ClientIDGTE applies the GTE predicate on the "client_id" field.
func ClientIDGTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldClientID, v))
}

// ClientIDLT applies the LT predicate on the "client_id" field.
func ClientIDLT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldClientID, v))
}

// ClientIDLTE applies the LTE predicate on the "client_id" field.
func ClientIDLTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldClientID, v))
}

// ClientIDContains applies the Contains predicate on the "client_id" field.
func ClientIDContains(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContains(FieldClientID, v))
}

// ClientIDHasPrefix applies the HasPrefix predicate on the "client_id" field.
func ClientIDHasPrefix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasPrefix(FieldClientID, v))
}

// ClientIDHasSuffix applies the HasSuffix predicate on the "client_id" field.
func ClientIDHasSuffix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasSuffix(FieldClientID, v))
}

// ClientIDEqualFold applies the EqualFold predicate on the "client_id" field.
func ClientIDEqualFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEqualFold(FieldClientID, v))
}

// ClientIDContainsFold applies the ContainsFold predicate on the "client_id" field.
func ClientIDContainsFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContainsFold(FieldClientID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContainsFold(FieldName, v))
}

// ClientSecretHashEQ applies the EQ predicate on the "client_secret_hash" field.
func ClientSecretHashEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldClientSecretHash, v))
}

// ClientSecretHashNEQ applies the NEQ predicate on the "client_secret_hash" field.
func ClientSecretHashNEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldClientSecretHash, v))
}

// ClientSecretHashIn applies the In predicate on the "client_secret_hash" field.
func ClientSecretHashIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldClientSecretHash, vs...))
}

// ClientSecretHashNotIn applies the NotIn predicate on the "client_secret_hash" field.
func ClientSecretHashNotIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldClientSecretHash, vs...))
}

// ClientSecretHashGT applies the GT predicate on the "client_secret_hash" field.
func ClientSecretHashGT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldClientSecretHash, v))
}

// ClientSecretHashGTE applies the GTE predicate on the "client_secret_hash" field.
func ClientSecretHashGTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldClientSecretHash, v))
}

// ClientSecretHashLT applies the LT predicate on the "client_secret_hash" field.
func ClientSecretHashLT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldClientSecretHash, v))
}

// ClientSecretHashLTE applies the LTE predicate on the "client_secret_hash" field.
func ClientSecretHashLTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldClientSecretHash, v))
}

// ClientSecretHashContains applies the Contains predicate on the "client_secret_hash" field.
func ClientSecretHashContains(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContains(FieldClientSecretHash, v))
}

// ClientSecretHashHasPrefix applies the HasPrefix predicate on the "client_secret_hash" field.
func ClientSecretHashHasPrefix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasPrefix(FieldClientSecretHash, v))
}

// ClientSecretHashHasSuffix applies the HasSuffix predicate on the "client_secret_hash" field.
func ClientSecretHashHasSuffix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasSuffix(FieldClientSecretHash, v))
}

// ClientSecretHashIsNil applies the IsNil predicate on the "client_secret_hash" field.
func ClientSecretHashIsNil() predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIsNull(FieldClientSecretHash))
}

// ClientSecretHashNotNil applies the NotNil predicate on the "client_secret_hash" field.
func ClientSecretHashNotNil() predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotNull(FieldClientSecretHash))
}

// ClientSecretHashEqualFold applies the EqualFold predicate on the "client_secret_hash" field.
func ClientSecretHashEqualFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEqualFold(FieldClientSecretHash, v))
}

// ClientSecretHashContainsFold applies the ContainsFold predicate on the "client_secret_hash" field.
func ClientSecretHashContainsFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContainsFold(FieldClientSecretHash, v))
}

// PkceRequiredEQ applies the EQ predicate on the "pkce_required" field.
func PkceRequiredEQ(v bool) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldPkceRequired, v))
}

// PkceRequiredNEQ applies the NEQ predicate on the "pkce_required" field.
func PkceRequiredNEQ(v bool) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldPkceRequired, v))
}

// DefaultGroupIDEQ applies the EQ predicate on the "default_group_id" field.
func DefaultGroupIDEQ(v int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldDefaultGroupID, v))
}

// DefaultGroupIDNEQ applies the NEQ predicate on the "default_group_id" field.
func DefaultGroupIDNEQ(v int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldDefaultGroupID, v))
}

// DefaultGroupIDIn applies the In predicate on the "default_group_id" field.
func DefaultGroupIDIn(vs ...int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldDefaultGroupID, vs...))
}

// DefaultGroupIDNotIn applies the NotIn predicate on the "default_group_id" field.
func DefaultGroupIDNotIn(vs ...int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldDefaultGroupID, vs...))
}

// DefaultGroupIDGT applies the GT predicate on the "default_group_id" field.
func DefaultGroupIDGT(v int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldDefaultGroupID, v))
}

// DefaultGroupIDGTE applies the GTE predicate on the "default_group_id" field.
func DefaultGroupIDGTE(v int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldDefaultGroupID, v))
}

// DefaultGroupIDLT applies the LT predicate on the "default_group_id" field.
func DefaultGroupIDLT(v int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldDefaultGroupID, v))
}

// DefaultGroupIDLTE applies the LTE predicate on the "default_group_id" field.
func DefaultGroupIDLTE(v int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldDefaultGroupID, v))
}

// DefaultGroupIDIsNil applies the IsNil predicate on the "default_group_id" field.
func DefaultGroupIDIsNil() predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIsNull(FieldDefaultGroupID))
}

// DefaultGroupIDNotNil applies the NotNil predicate on the "default_group_id" field.
func DefaultGroupIDNotNil() predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotNull(FieldDefaultGroupID))
}

// AccessTokenTTLSecondsEQ applies the EQ predicate on the "access_token_ttl_seconds" field.
func AccessTokenTTLSecondsEQ(v int) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldAccessTokenTTLSeconds, v))
}

// AccessTokenTTLSecondsNEQ applies the NEQ predicate on the "access_token_ttl_seconds" field.
func AccessTokenTTLSecondsNEQ(v int) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldAccessTokenTTLSeconds, v))
}

// AccessTokenTTLSecondsIn applies the In predicate on the "access_token_ttl_seconds" field.
func AccessTokenTTLSecondsIn(vs ...int) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldAccessTokenTTLSeconds, vs...))
}

// AccessTokenTTLSecondsNotIn applies the NotIn predicate on the "access_token_ttl_seconds" field.
func AccessTokenTTLSecondsNotIn(vs ...int) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldAccessTokenTTLSeconds, vs...))
}

// AccessTokenTTLSecondsGT applies the GT predicate on the "access_token_ttl_seconds" field.
func AccessTokenTTLSecondsGT(v int) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldAccessTokenTTLSeconds, v))
}

// AccessTokenTTLSecondsGTE applies the GTE predicate on the "access_token_ttl_seconds" field.
func AccessTokenTTLSecondsGTE(v int) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldAccessTokenTTLSeconds, v))
}

// AccessTokenTTLSecondsLT applies the LT predicate on the "access_token_ttl_seconds" field.
func AccessTokenTTLSecondsLT(v int) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldAccessTokenTTLSeconds, v))
}

// AccessTokenTTLSecondsLTE applies the LTE predicate on the "access_token_ttl_seconds" field.
func AccessTokenTTLSecondsLTE(v int) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldAccessTokenTTLSeconds, v))
}

// RefreshTokenTTLSecondsEQ applies the EQ predicate on the "refresh_token_ttl_seconds" field.
func RefreshTokenTTLSecondsEQ(v int) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldRefreshTokenTTLSeconds, v))
}

// RefreshTokenTTLSecondsNEQ applies the NEQ predicate on the "refresh_token_ttl_seconds" field.
func RefreshTokenTTLSecondsNEQ(v int) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldRefreshTokenTTLSeconds, v))
}

// RefreshTokenTTLSecondsIn applies the In predicate on the "refresh_token_ttl_seconds" field.
func RefreshTokenTTLSecondsIn(vs ...int) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldRefreshTokenTTLSeconds, vs...))
}

// RefreshTokenTTLSecondsNotIn applies the NotIn predicate on the "refresh_token_ttl_seconds" field.
func RefreshTokenTTLSecondsNotIn(vs ...int) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldRefreshTokenTTLSeconds, vs...))
}

// RefreshTokenTTLSecondsGT applies the GT predicate on the "refresh_token_ttl_seconds" field.
func RefreshTokenTTLSecondsGT(v int) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldRefreshTokenTTLSeconds, v))
}

// RefreshTokenTTLSecondsGTE applies the GTE predicate on the "refresh_token_ttl_seconds" field.
func RefreshTokenTTLSecondsGTE(v int) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldRefreshTokenTTLSeconds, v))
}

// RefreshTokenTTLSecondsLT applies the LT predicate on the "refresh_token_ttl_seconds" field.
func RefreshTokenTTLSecondsLT(v int) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldRefreshTokenTTLSeconds, v))
}

// RefreshTokenTTLSecondsLTE applies the LTE predicate on the "refresh_token_ttl_seconds" field.
func RefreshTokenTTLSecondsLTE(v int) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldRefreshTokenTTLSeconds, v))
}

// DisabledEQ applies the EQ predicate on the "disabled" field.
func DisabledEQ(v bool) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldDisabled, v))
}

// DisabledNEQ applies the NEQ predicate on the "disabled" field.
func DisabledNEQ(v bool) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldDisabled, v))
}

// ClientTypeEQ applies the EQ predicate on the "client_type" field.
func ClientTypeEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldClientType, v))
}

// ClientTypeNEQ applies the NEQ predicate on the "client_type" field.
func ClientTypeNEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldClientType, v))
}

// ClientTypeIn applies the In predicate on the "client_type" field.
func ClientTypeIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldClientType, vs...))
}

// ClientTypeNotIn applies the NotIn predicate on the "client_type" field.
func ClientTypeNotIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldClientType, vs...))
}

// ClientTypeGT applies the GT predicate on the "client_type" field.
func ClientTypeGT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldClientType, v))
}

// ClientTypeGTE applies the GTE predicate on the "client_type" field.
func ClientTypeGTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldClientType, v))
}

// ClientTypeLT applies the LT predicate on the "client_type" field.
func ClientTypeLT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldClientType, v))
}

// ClientTypeLTE applies the LTE predicate on the "client_type" field.
func ClientTypeLTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldClientType, v))
}

// ClientTypeContains applies the Contains predicate on the "client_type" field.
func ClientTypeContains(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContains(FieldClientType, v))
}

// ClientTypeHasPrefix applies the HasPrefix predicate on the "client_type" field.
func ClientTypeHasPrefix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasPrefix(FieldClientType, v))
}

// ClientTypeHasSuffix applies the HasSuffix predicate on the "client_type" field.
func ClientTypeHasSuffix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasSuffix(FieldClientType, v))
}

// ClientTypeEqualFold applies the EqualFold predicate on the "client_type" field.
func ClientTypeEqualFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEqualFold(FieldClientType, v))
}

// ClientTypeContainsFold applies the ContainsFold predicate on the "client_type" field.
func ClientTypeContainsFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContainsFold(FieldClientType, v))
}

// AppTypeEQ applies the EQ predicate on the "app_type" field.
func AppTypeEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldAppType, v))
}

// AppTypeNEQ applies the NEQ predicate on the "app_type" field.
func AppTypeNEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldAppType, v))
}

// AppTypeIn applies the In predicate on the "app_type" field.
func AppTypeIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldAppType, vs...))
}

// AppTypeNotIn applies the NotIn predicate on the "app_type" field.
func AppTypeNotIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldAppType, vs...))
}

// AppTypeGT applies the GT predicate on the "app_type" field.
func AppTypeGT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldAppType, v))
}

// AppTypeGTE applies the GTE predicate on the "app_type" field.
func AppTypeGTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldAppType, v))
}

// AppTypeLT applies the LT predicate on the "app_type" field.
func AppTypeLT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldAppType, v))
}

// AppTypeLTE applies the LTE predicate on the "app_type" field.
func AppTypeLTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldAppType, v))
}

// AppTypeContains applies the Contains predicate on the "app_type" field.
func AppTypeContains(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContains(FieldAppType, v))
}

// AppTypeHasPrefix applies the HasPrefix predicate on the "app_type" field.
func AppTypeHasPrefix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasPrefix(FieldAppType, v))
}

// AppTypeHasSuffix applies the HasSuffix predicate on the "app_type" field.
func AppTypeHasSuffix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasSuffix(FieldAppType, v))
}

// AppTypeEqualFold applies the EqualFold predicate on the "app_type" field.
func AppTypeEqualFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEqualFold(FieldAppType, v))
}

// AppTypeContainsFold applies the ContainsFold predicate on the "app_type" field.
func AppTypeContainsFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContainsFold(FieldAppType, v))
}

// TrustedFirstPartyEQ applies the EQ predicate on the "trusted_first_party" field.
func TrustedFirstPartyEQ(v bool) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldTrustedFirstParty, v))
}

// TrustedFirstPartyNEQ applies the NEQ predicate on the "trusted_first_party" field.
func TrustedFirstPartyNEQ(v bool) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldTrustedFirstParty, v))
}

// AllowedGroupIdsIsNil applies the IsNil predicate on the "allowed_group_ids" field.
func AllowedGroupIdsIsNil() predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIsNull(FieldAllowedGroupIds))
}

// AllowedGroupIdsNotNil applies the NotNil predicate on the "allowed_group_ids" field.
func AllowedGroupIdsNotNil() predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotNull(FieldAllowedGroupIds))
}

// DeviceFlowEnabledEQ applies the EQ predicate on the "device_flow_enabled" field.
func DeviceFlowEnabledEQ(v bool) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldDeviceFlowEnabled, v))
}

// DeviceFlowEnabledNEQ applies the NEQ predicate on the "device_flow_enabled" field.
func DeviceFlowEnabledNEQ(v bool) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldDeviceFlowEnabled, v))
}

// AllowRefreshWithoutOfflineAccessEQ applies the EQ predicate on the "allow_refresh_without_offline_access" field.
func AllowRefreshWithoutOfflineAccessEQ(v bool) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldAllowRefreshWithoutOfflineAccess, v))
}

// AllowRefreshWithoutOfflineAccessNEQ applies the NEQ predicate on the "allow_refresh_without_offline_access" field.
func AllowRefreshWithoutOfflineAccessNEQ(v bool) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldAllowRefreshWithoutOfflineAccess, v))
}

// IconURLEQ applies the EQ predicate on the "icon_url" field.
func IconURLEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldIconURL, v))
}

// IconURLNEQ applies the NEQ predicate on the "icon_url" field.
func IconURLNEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldIconURL, v))
}

// IconURLIn applies the In predicate on the "icon_url" field.
func IconURLIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldIconURL, vs...))
}

// IconURLNotIn applies the NotIn predicate on the "icon_url" field.
func IconURLNotIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldIconURL, vs...))
}

// IconURLGT applies the GT predicate on the "icon_url" field.
func IconURLGT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldIconURL, v))
}

// IconURLGTE applies the GTE predicate on the "icon_url" field.
func IconURLGTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldIconURL, v))
}

// IconURLLT applies the LT predicate on the "icon_url" field.
func IconURLLT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldIconURL, v))
}

// IconURLLTE applies the LTE predicate on the "icon_url" field.
func IconURLLTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldIconURL, v))
}

// IconURLContains applies the Contains predicate on the "icon_url" field.
func IconURLContains(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContains(FieldIconURL, v))
}

// IconURLHasPrefix applies the HasPrefix predicate on the "icon_url" field.
func IconURLHasPrefix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasPrefix(FieldIconURL, v))
}

// IconURLHasSuffix applies the HasSuffix predicate on the "icon_url" field.
func IconURLHasSuffix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasSuffix(FieldIconURL, v))
}

// IconURLIsNil applies the IsNil predicate on the "icon_url" field.
func IconURLIsNil() predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIsNull(FieldIconURL))
}

// IconURLNotNil applies the NotNil predicate on the "icon_url" field.
func IconURLNotNil() predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotNull(FieldIconURL))
}

// IconURLEqualFold applies the EqualFold predicate on the "icon_url" field.
func IconURLEqualFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEqualFold(FieldIconURL, v))
}

// IconURLContainsFold applies the ContainsFold predicate on the "icon_url" field.
func IconURLContainsFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContainsFold(FieldIconURL, v))
}

// HomepageURLEQ applies the EQ predicate on the "homepage_url" field.
func HomepageURLEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldHomepageURL, v))
}

// HomepageURLNEQ applies the NEQ predicate on the "homepage_url" field.
func HomepageURLNEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldHomepageURL, v))
}

// HomepageURLIn applies the In predicate on the "homepage_url" field.
func HomepageURLIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldHomepageURL, vs...))
}

// HomepageURLNotIn applies the NotIn predicate on the "homepage_url" field.
func HomepageURLNotIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldHomepageURL, vs...))
}

// HomepageURLGT applies the GT predicate on the "homepage_url" field.
func HomepageURLGT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldHomepageURL, v))
}

// HomepageURLGTE applies the GTE predicate on the "homepage_url" field.
func HomepageURLGTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldHomepageURL, v))
}

// HomepageURLLT applies the LT predicate on the "homepage_url" field.
func HomepageURLLT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldHomepageURL, v))
}

// HomepageURLLTE applies the LTE predicate on the "homepage_url" field.
func HomepageURLLTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldHomepageURL, v))
}

// HomepageURLContains applies the Contains predicate on the "homepage_url" field.
func HomepageURLContains(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContains(FieldHomepageURL, v))
}

// HomepageURLHasPrefix applies the HasPrefix predicate on the "homepage_url" field.
func HomepageURLHasPrefix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasPrefix(FieldHomepageURL, v))
}

// HomepageURLHasSuffix applies the HasSuffix predicate on the "homepage_url" field.
func HomepageURLHasSuffix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasSuffix(FieldHomepageURL, v))
}

// HomepageURLIsNil applies the IsNil predicate on the "homepage_url" field.
func HomepageURLIsNil() predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIsNull(FieldHomepageURL))
}

// HomepageURLNotNil applies the NotNil predicate on the "homepage_url" field.
func HomepageURLNotNil() predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotNull(FieldHomepageURL))
}

// HomepageURLEqualFold applies the EqualFold predicate on the "homepage_url" field.
func HomepageURLEqualFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEqualFold(FieldHomepageURL, v))
}

// HomepageURLContainsFold applies the ContainsFold predicate on the "homepage_url" field.
func HomepageURLContainsFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContainsFold(FieldHomepageURL, v))
}

// PrivacyURLEQ applies the EQ predicate on the "privacy_url" field.
func PrivacyURLEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldPrivacyURL, v))
}

// PrivacyURLNEQ applies the NEQ predicate on the "privacy_url" field.
func PrivacyURLNEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldPrivacyURL, v))
}

// PrivacyURLIn applies the In predicate on the "privacy_url" field.
func PrivacyURLIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldPrivacyURL, vs...))
}

// PrivacyURLNotIn applies the NotIn predicate on the "privacy_url" field.
func PrivacyURLNotIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldPrivacyURL, vs...))
}

// PrivacyURLGT applies the GT predicate on the "privacy_url" field.
func PrivacyURLGT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldPrivacyURL, v))
}

// PrivacyURLGTE applies the GTE predicate on the "privacy_url" field.
func PrivacyURLGTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldPrivacyURL, v))
}

// PrivacyURLLT applies the LT predicate on the "privacy_url" field.
func PrivacyURLLT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldPrivacyURL, v))
}

// PrivacyURLLTE applies the LTE predicate on the "privacy_url" field.
func PrivacyURLLTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldPrivacyURL, v))
}

// PrivacyURLContains applies the Contains predicate on the "privacy_url" field.
func PrivacyURLContains(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContains(FieldPrivacyURL, v))
}

// PrivacyURLHasPrefix applies the HasPrefix predicate on the "privacy_url" field.
func PrivacyURLHasPrefix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasPrefix(FieldPrivacyURL, v))
}

// PrivacyURLHasSuffix applies the HasSuffix predicate on the "privacy_url" field.
func PrivacyURLHasSuffix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasSuffix(FieldPrivacyURL, v))
}

// PrivacyURLIsNil applies the IsNil predicate on the "privacy_url" field.
func PrivacyURLIsNil() predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIsNull(FieldPrivacyURL))
}

// PrivacyURLNotNil applies the NotNil predicate on the "privacy_url" field.
func PrivacyURLNotNil() predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotNull(FieldPrivacyURL))
}

// PrivacyURLEqualFold applies the EqualFold predicate on the "privacy_url" field.
func PrivacyURLEqualFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEqualFold(FieldPrivacyURL, v))
}

// PrivacyURLContainsFold applies the ContainsFold predicate on the "privacy_url" field.
func PrivacyURLContainsFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContainsFold(FieldPrivacyURL, v))
}

// TermsURLEQ applies the EQ predicate on the "terms_url" field.
func TermsURLEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldTermsURL, v))
}

// TermsURLNEQ applies the NEQ predicate on the "terms_url" field.
func TermsURLNEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldTermsURL, v))
}

// TermsURLIn applies the In predicate on the "terms_url" field.
func TermsURLIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldTermsURL, vs...))
}

// TermsURLNotIn applies the NotIn predicate on the "terms_url" field.
func TermsURLNotIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldTermsURL, vs...))
}

// TermsURLGT applies the GT predicate on the "terms_url" field.
func TermsURLGT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldTermsURL, v))
}

// TermsURLGTE applies the GTE predicate on the "terms_url" field.
func TermsURLGTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldTermsURL, v))
}

// TermsURLLT applies the LT predicate on the "terms_url" field.
func TermsURLLT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldTermsURL, v))
}

// TermsURLLTE applies the LTE predicate on the "terms_url" field.
func TermsURLLTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldTermsURL, v))
}

// TermsURLContains applies the Contains predicate on the "terms_url" field.
func TermsURLContains(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContains(FieldTermsURL, v))
}

// TermsURLHasPrefix applies the HasPrefix predicate on the "terms_url" field.
func TermsURLHasPrefix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasPrefix(FieldTermsURL, v))
}

// TermsURLHasSuffix applies the HasSuffix predicate on the "terms_url" field.
func TermsURLHasSuffix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasSuffix(FieldTermsURL, v))
}

// TermsURLIsNil applies the IsNil predicate on the "terms_url" field.
func TermsURLIsNil() predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIsNull(FieldTermsURL))
}

// TermsURLNotNil applies the NotNil predicate on the "terms_url" field.
func TermsURLNotNil() predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotNull(FieldTermsURL))
}

// TermsURLEqualFold applies the EqualFold predicate on the "terms_url" field.
func TermsURLEqualFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEqualFold(FieldTermsURL, v))
}

// TermsURLContainsFold applies the ContainsFold predicate on the "terms_url" field.
func TermsURLContainsFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContainsFold(FieldTermsURL, v))
}

// SigningAlgorithmEQ applies the EQ predicate on the "signing_algorithm" field.
func SigningAlgorithmEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldSigningAlgorithm, v))
}

// SigningAlgorithmNEQ applies the NEQ predicate on the "signing_algorithm" field.
func SigningAlgorithmNEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldSigningAlgorithm, v))
}

// SigningAlgorithmIn applies the In predicate on the "signing_algorithm" field.
func SigningAlgorithmIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldSigningAlgorithm, vs...))
}

// SigningAlgorithmNotIn applies the NotIn predicate on the "signing_algorithm" field.
func SigningAlgorithmNotIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldSigningAlgorithm, vs...))
}

// SigningAlgorithmGT applies the GT predicate on the "signing_algorithm" field.
func SigningAlgorithmGT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldSigningAlgorithm, v))
}

// SigningAlgorithmGTE applies the GTE predicate on the "signing_algorithm" field.
func SigningAlgorithmGTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldSigningAlgorithm, v))
}

// SigningAlgorithmLT applies the LT predicate on the "signing_algorithm" field.
func SigningAlgorithmLT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldSigningAlgorithm, v))
}

// SigningAlgorithmLTE applies the LTE predicate on the "signing_algorithm" field.
func SigningAlgorithmLTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldSigningAlgorithm, v))
}

// SigningAlgorithmContains applies the Contains predicate on the "signing_algorithm" field.
func SigningAlgorithmContains(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContains(FieldSigningAlgorithm, v))
}

// SigningAlgorithmHasPrefix applies the HasPrefix predicate on the "signing_algorithm" field.
func SigningAlgorithmHasPrefix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasPrefix(FieldSigningAlgorithm, v))
}

// SigningAlgorithmHasSuffix applies the HasSuffix predicate on the "signing_algorithm" field.
func SigningAlgorithmHasSuffix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasSuffix(FieldSigningAlgorithm, v))
}

// SigningAlgorithmEqualFold applies the EqualFold predicate on the "signing_algorithm" field.
func SigningAlgorithmEqualFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEqualFold(FieldSigningAlgorithm, v))
}

// SigningAlgorithmContainsFold applies the ContainsFold predicate on the "signing_algorithm" field.
func SigningAlgorithmContainsFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContainsFold(FieldSigningAlgorithm, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OAuthClient) predicate.OAuthClient {
	return predicate.OAuthClient(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OAuthClient) predicate.OAuthClient {
	return predicate.OAuthClient(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OAuthClient) predicate.OAuthClient {
	return predicate.OAuthClient(sql.NotPredicates(p))
}
