// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/oauthclient"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// OAuthClientUpdate is the builder for updating OAuthClient entities.
type OAuthClientUpdate struct {
	config
	hooks    []Hook
	mutation *OAuthClientMutation
}

// Where appends a list predicates to the OAuthClientUpdate builder.
func (_u *OAuthClientUpdate) Where(ps ...predicate.OAuthClient) *OAuthClientUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OAuthClientUpdate) SetUpdatedAt(v time.Time) *OAuthClientUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *OAuthClientUpdate) SetClientID(v string) *OAuthClientUpdate {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OAuthClientUpdate) SetNillableClientID(v *string) *OAuthClientUpdate {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *OAuthClientUpdate) SetName(v string) *OAuthClientUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *OAuthClientUpdate) SetNillableName(v *string) *OAuthClientUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetClientSecretHash sets the "client_secret_hash" field.
func (_u *OAuthClientUpdate) SetClientSecretHash(v string) *OAuthClientUpdate {
	_u.mutation.SetClientSecretHash(v)
	return _u
}

// SetNillableClientSecretHash sets the "client_secret_hash" field if the given value is not nil.
func (_u *OAuthClientUpdate) SetNillableClientSecretHash(v *string) *OAuthClientUpdate {
	if v != nil {
		_u.SetClientSecretHash(*v)
	}
	return _u
}

// ClearClientSecretHash clears the value of the "client_secret_hash" field.
func (_u *OAuthClientUpdate) ClearClientSecretHash() *OAuthClientUpdate {
	_u.mutation.ClearClientSecretHash()
	return _u
}

// SetRedirectUris sets the "redirect_uris" field.
func (_u *OAuthClientUpdate) SetRedirectUris(v []string) *OAuthClientUpdate {
	_u.mutation.SetRedirectUris(v)
	return _u
}

// AppendRedirectUris appends value to the "redirect_uris" field.
func (_u *OAuthClientUpdate) AppendRedirectUris(v []string) *OAuthClientUpdate {
	_u.mutation.AppendRedirectUris(v)
	return _u
}

// SetAllowedScopes sets the "allowed_scopes" field.
func (_u *OAuthClientUpdate) SetAllowedScopes(v []string) *OAuthClientUpdate {
	_u.mutation.SetAllowedScopes(v)
	return _u
}

// AppendAllowedScopes appends value to the "allowed_scopes" field.
func (_u *OAuthClientUpdate) AppendAllowedScopes(v []string) *OAuthClientUpdate {
	_u.mutation.AppendAllowedScopes(v)
	return _u
}

// SetPkceRequired sets the "pkce_required" field.
func (_u *OAuthClientUpdate) SetPkceRequired(v bool) *OAuthClientUpdate {
	_u.mutation.SetPkceRequired(v)
	return _u
}

// SetNillablePkceRequired sets the "pkce_required" field if the given value is not nil.
func (_u *OAuthClientUpdate) SetNillablePkceRequired(v *bool) *OAuthClientUpdate {
	if v != nil {
		_u.SetPkceRequired(*v)
	}
	return _u
}

// SetDefaultGroupID sets the "default_group_id" field.
func (_u *OAuthClientUpdate) SetDefaultGroupID(v int64) *OAuthClientUpdate {
	_u.mutation.ResetDefaultGroupID()
	_u.mutation.SetDefaultGroupID(v)
	return _u
}

// SetNillableDefaultGroupID sets the "default_group_id" field if the given value is not nil.
func (_u *OAuthClientUpdate) SetNillableDefaultGroupID(v *int64) *OAuthClientUpdate {
	if v != nil {
		_u.SetDefaultGroupID(*v)
	}
	return _u
}

// AddDefaultGroupID adds value to the "default_group_id" field.
func (_u *OAuthClientUpdate) AddDefaultGroupID(v int64) *OAuthClientUpdate {
	_u.mutation.AddDefaultGroupID(v)
	return _u
}

// ClearDefaultGroupID clears the value of the "default_group_id" field.
func (_u *OAuthClientUpdate) ClearDefaultGroupID() *OAuthClientUpdate {
	_u.mutation.ClearDefaultGroupID()
	return _u
}

// SetAccessTokenTTLSeconds sets the "access_token_ttl_seconds" field.
func (_u *OAuthClientUpdate) SetAccessTokenTTLSeconds(v int) *OAuthClientUpdate {
	_u.mutation.ResetAccessTokenTTLSeconds()
	_u.mutation.SetAccessTokenTTLSeconds(v)
	return _u
}

// SetNillableAccessTokenTTLSeconds sets the "access_token_ttl_seconds" field if the given value is not nil.
func (_u *OAuthClientUpdate) SetNillableAccessTokenTTLSeconds(v *int) *OAuthClientUpdate {
	if v != nil {
		_u.SetAccessTokenTTLSeconds(*v)
	}
	return _u
}

// AddAccessTokenTTLSeconds adds value to the "access_token_ttl_seconds" field.
func (_u *OAuthClientUpdate) AddAccessTokenTTLSeconds(v int) *OAuthClientUpdate {
	_u.mutation.AddAccessTokenTTLSeconds(v)
	return _u
}

// SetRefreshTokenTTLSeconds sets the "refresh_token_ttl_seconds" field.
func (_u *OAuthClientUpdate) SetRefreshTokenTTLSeconds(v int) *OAuthClientUpdate {
	_u.mutation.ResetRefreshTokenTTLSeconds()
	_u.mutation.SetRefreshTokenTTLSeconds(v)
	return _u
}

// SetNillableRefreshTokenTTLSeconds sets the "refresh_token_ttl_seconds" field if the given value is not nil.
func (_u *OAuthClientUpdate) SetNillableRefreshTokenTTLSeconds(v *int) *OAuthClientUpdate {
	if v != nil {
		_u.SetRefreshTokenTTLSeconds(*v)
	}
	return _u
}

// AddRefreshTokenTTLSeconds adds value to the "refresh_token_ttl_seconds" field.
func (_u *OAuthClientUpdate) AddRefreshTokenTTLSeconds(v int) *OAuthClientUpdate {
	_u.mutation.AddRefreshTokenTTLSeconds(v)
	return _u
}

// SetDisabled sets the "disabled" field.
func (_u *OAuthClientUpdate) SetDisabled(v bool) *OAuthClientUpdate {
	_u.mutation.SetDisabled(v)
	return _u
}

// SetNillableDisabled sets the "disabled" field if the given value is not nil.
func (_u *OAuthClientUpdate) SetNillableDisabled(v *bool) *OAuthClientUpdate {
	if v != nil {
		_u.SetDisabled(*v)
	}
	return _u
}

// Mutation returns the OAuthClientMutation object of the builder.
func (_u *OAuthClientUpdate) Mutation() *OAuthClientMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OAuthClientUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthClientUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OAuthClientUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthClientUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OAuthClientUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := oauthclient.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthClientUpdate) check() error {
	if v, ok := _u.mutation.ClientID(); ok {
		if err := oauthclient.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "OAuthClient.client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := oauthclient.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "OAuthClient.name": %w`, err)}
		}
	}
	return nil
}

func (_u *OAuthClientUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthclient.Table, oauthclient.Columns, sqlgraph.NewFieldSpec(oauthclient.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthclient.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(oauthclient.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(oauthclient.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientSecretHash(); ok {
		_spec.SetField(oauthclient.FieldClientSecretHash, field.TypeString, value)
	}
	if _u.mutation.ClientSecretHashCleared() {
		_spec.ClearField(oauthclient.FieldClientSecretHash, field.TypeString)
	}
	if value, ok := _u.mutation.RedirectUris(); ok {
		_spec.SetField(oauthclient.FieldRedirectUris, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRedirectUris(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthclient.FieldRedirectUris, value)
		})
	}
	if value, ok := _u.mutation.AllowedScopes(); ok {
		_spec.SetField(oauthclient.FieldAllowedScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAllowedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthclient.FieldAllowedScopes, value)
		})
	}
	if value, ok := _u.mutation.PkceRequired(); ok {
		_spec.SetField(oauthclient.FieldPkceRequired, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DefaultGroupID(); ok {
		_spec.SetField(oauthclient.FieldDefaultGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDefaultGroupID(); ok {
		_spec.AddField(oauthclient.FieldDefaultGroupID, field.TypeInt64, value)
	}
	if _u.mutation.DefaultGroupIDCleared() {
		_spec.ClearField(oauthclient.FieldDefaultGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AccessTokenTTLSeconds(); ok {
		_spec.SetField(oauthclient.FieldAccessTokenTTLSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAccessTokenTTLSeconds(); ok {
		_spec.AddField(oauthclient.FieldAccessTokenTTLSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RefreshTokenTTLSeconds(); ok {
		_spec.SetField(oauthclient.FieldRefreshTokenTTLSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRefreshTokenTTLSeconds(); ok {
		_spec.AddField(oauthclient.FieldRefreshTokenTTLSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Disabled(); ok {
		_spec.SetField(oauthclient.FieldDisabled, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthclient.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OAuthClientUpdateOne is the builder for updating a single OAuthClient entity.
type OAuthClientUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OAuthClientMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OAuthClientUpdateOne) SetUpdatedAt(v time.Time) *OAuthClientUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *OAuthClientUpdateOne) SetClientID(v string) *OAuthClientUpdateOne {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OAuthClientUpdateOne) SetNillableClientID(v *string) *OAuthClientUpdateOne {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *OAuthClientUpdateOne) SetName(v string) *OAuthClientUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *OAuthClientUpdateOne) SetNillableName(v *string) *OAuthClientUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetClientSecretHash sets the "client_secret_hash" field.
func (_u *OAuthClientUpdateOne) SetClientSecretHash(v string) *OAuthClientUpdateOne {
	_u.mutation.SetClientSecretHash(v)
	return _u
}

// SetNillableClientSecretHash sets the "client_secret_hash" field if the given value is not nil.
func (_u *OAuthClientUpdateOne) SetNillableClientSecretHash(v *string) *OAuthClientUpdateOne {
	if v != nil {
		_u.SetClientSecretHash(*v)
	}
	return _u
}

// ClearClientSecretHash clears the value of the "client_secret_hash" field.
func (_u *OAuthClientUpdateOne) ClearClientSecretHash() *OAuthClientUpdateOne {
	_u.mutation.ClearClientSecretHash()
	return _u
}

// SetRedirectUris sets the "redirect_uris" field.
func (_u *OAuthClientUpdateOne) SetRedirectUris(v []string) *OAuthClientUpdateOne {
	_u.mutation.SetRedirectUris(v)
	return _u
}

// AppendRedirectUris appends value to the "redirect_uris" field.
func (_u *OAuthClientUpdateOne) AppendRedirectUris(v []string) *OAuthClientUpdateOne {
	_u.mutation.AppendRedirectUris(v)
	return _u
}

// SetAllowedScopes sets the "allowed_scopes" field.
func (_u *OAuthClientUpdateOne) SetAllowedScopes(v []string) *OAuthClientUpdateOne {
	_u.mutation.SetAllowedScopes(v)
	return _u
}

// AppendAllowedScopes appends value to the "allowed_scopes" field.
func (_u *OAuthClientUpdateOne) AppendAllowedScopes(v []string) *OAuthClientUpdateOne {
	_u.mutation.AppendAllowedScopes(v)
	return _u
}

// SetPkceRequired sets the "pkce_required" field.
func (_u *OAuthClientUpdateOne) SetPkceRequired(v bool) *OAuthClientUpdateOne {
	_u.mutation.SetPkceRequired(v)
	return _u
}

// SetNillablePkceRequired sets the "pkce_required" field if the given value is not nil.
func (_u *OAuthClientUpdateOne) SetNillablePkceRequired(v *bool) *OAuthClientUpdateOne {
	if v != nil {
		_u.SetPkceRequired(*v)
	}
	return _u
}

// SetDefaultGroupID sets the "default_group_id" field.
func (_u *OAuthClientUpdateOne) SetDefaultGroupID(v int64) *OAuthClientUpdateOne {
	_u.mutation.ResetDefaultGroupID()
	_u.mutation.SetDefaultGroupID(v)
	return _u
}

// SetNillableDefaultGroupID sets the "default_group_id" field if the given value is not nil.
func (_u *OAuthClientUpdateOne) SetNillableDefaultGroupID(v *int64) *OAuthClientUpdateOne {
	if v != nil {
		_u.SetDefaultGroupID(*v)
	}
	return _u
}

// AddDefaultGroupID adds value to the "default_group_id" field.
func (_u *OAuthClientUpdateOne) AddDefaultGroupID(v int64) *OAuthClientUpdateOne {
	_u.mutation.AddDefaultGroupID(v)
	return _u
}

// ClearDefaultGroupID clears the value of the "default_group_id" field.
func (_u *OAuthClientUpdateOne) ClearDefaultGroupID() *OAuthClientUpdateOne {
	_u.mutation.ClearDefaultGroupID()
	return _u
}

// SetAccessTokenTTLSeconds sets the "access_token_ttl_seconds" field.
func (_u *OAuthClientUpdateOne) SetAccessTokenTTLSeconds(v int) *OAuthClientUpdateOne {
	_u.mutation.ResetAccessTokenTTLSeconds()
	_u.mutation.SetAccessTokenTTLSeconds(v)
	return _u
}

// SetNillableAccessTokenTTLSeconds sets the "access_token_ttl_seconds" field if the given value is not nil.
func (_u *OAuthClientUpdateOne) SetNillableAccessTokenTTLSeconds(v *int) *OAuthClientUpdateOne {
	if v != nil {
		_u.SetAccessTokenTTLSeconds(*v)
	}
	return _u
}

// AddAccessTokenTTLSeconds adds value to the "access_token_ttl_seconds" field.
func (_u *OAuthClientUpdateOne) AddAccessTokenTTLSeconds(v int) *OAuthClientUpdateOne {
	_u.mutation.AddAccessTokenTTLSeconds(v)
	return _u
}

// SetRefreshTokenTTLSeconds sets the "refresh_token_ttl_seconds" field.
func (_u *OAuthClientUpdateOne) SetRefreshTokenTTLSeconds(v int) *OAuthClientUpdateOne {
	_u.mutation.ResetRefreshTokenTTLSeconds()
	_u.mutation.SetRefreshTokenTTLSeconds(v)
	return _u
}

// SetNillableRefreshTokenTTLSeconds sets the "refresh_token_ttl_seconds" field if the given value is not nil.
func (_u *OAuthClientUpdateOne) SetNillableRefreshTokenTTLSeconds(v *int) *OAuthClientUpdateOne {
	if v != nil {
		_u.SetRefreshTokenTTLSeconds(*v)
	}
	return _u
}

// AddRefreshTokenTTLSeconds adds value to the "refresh_token_ttl_seconds" field.
func (_u *OAuthClientUpdateOne) AddRefreshTokenTTLSeconds(v int) *OAuthClientUpdateOne {
	_u.mutation.AddRefreshTokenTTLSeconds(v)
	return _u
}

// SetDisabled sets the "disabled" field.
func (_u *OAuthClientUpdateOne) SetDisabled(v bool) *OAuthClientUpdateOne {
	_u.mutation.SetDisabled(v)
	return _u
}

// SetNillableDisabled sets the "disabled" field if the given value is not nil.
func (_u *OAuthClientUpdateOne) SetNillableDisabled(v *bool) *OAuthClientUpdateOne {
	if v != nil {
		_u.SetDisabled(*v)
	}
	return _u
}

// Mutation returns the OAuthClientMutation object of the builder.
func (_u *OAuthClientUpdateOne) Mutation() *OAuthClientMutation {
	return _u.mutation
}

// Where appends a list predicates to the OAuthClientUpdate builder.
func (_u *OAuthClientUpdateOne) Where(ps ...predicate.OAuthClient) *OAuthClientUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OAuthClientUpdateOne) Select(field string, fields ...string) *OAuthClientUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OAuthClient entity.
func (_u *OAuthClientUpdateOne) Save(ctx context.Context) (*OAuthClient, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthClientUpdateOne) SaveX(ctx context.Context) *OAuthClient {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OAuthClientUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthClientUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OAuthClientUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := oauthclient.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthClientUpdateOne) check() error {
	if v, ok := _u.mutation.ClientID(); ok {
		if err := oauthclient.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "OAuthClient.client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := oauthclient.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "OAuthClient.name": %w`, err)}
		}
	}
	return nil
}

func (_u *OAuthClientUpdateOne) sqlSave(ctx context.Context) (_node *OAuthClient, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthclient.Table, oauthclient.Columns, sqlgraph.NewFieldSpec(oauthclient.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OAuthClient.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauthclient.FieldID)
		for _, f := range fields {
			if !oauthclient.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != oauthclient.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthclient.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(oauthclient.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(oauthclient.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientSecretHash(); ok {
		_spec.SetField(oauthclient.FieldClientSecretHash, field.TypeString, value)
	}
	if _u.mutation.ClientSecretHashCleared() {
		_spec.ClearField(oauthclient.FieldClientSecretHash, field.TypeString)
	}
	if value, ok := _u.mutation.RedirectUris(); ok {
		_spec.SetField(oauthclient.FieldRedirectUris, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRedirectUris(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthclient.FieldRedirectUris, value)
		})
	}
	if value, ok := _u.mutation.AllowedScopes(); ok {
		_spec.SetField(oauthclient.FieldAllowedScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAllowedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthclient.FieldAllowedScopes, value)
		})
	}
	if value, ok := _u.mutation.PkceRequired(); ok {
		_spec.SetField(oauthclient.FieldPkceRequired, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DefaultGroupID(); ok {
		_spec.SetField(oauthclient.FieldDefaultGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDefaultGroupID(); ok {
		_spec.AddField(oauthclient.FieldDefaultGroupID, field.TypeInt64, value)
	}
	if _u.mutation.DefaultGroupIDCleared() {
		_spec.ClearField(oauthclient.FieldDefaultGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AccessTokenTTLSeconds(); ok {
		_spec.SetField(oauthclient.FieldAccessTokenTTLSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAccessTokenTTLSeconds(); ok {
		_spec.AddField(oauthclient.FieldAccessTokenTTLSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RefreshTokenTTLSeconds(); ok {
		_spec.SetField(oauthclient.FieldRefreshTokenTTLSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRefreshTokenTTLSeconds(); ok {
		_spec.AddField(oauthclient.FieldRefreshTokenTTLSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Disabled(); ok {
		_spec.SetField(oauthclient.FieldDisabled, field.TypeBool, value)
	}
	_node = &OAuthClient{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthclient.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
