// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/oauthclient"
)

// OAuthClientCreate is the builder for creating a OAuthClient entity.
type OAuthClientCreate struct {
	config
	mutation *OAuthClientMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *OAuthClientCreate) SetCreatedAt(v time.Time) *OAuthClientCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OAuthClientCreate) SetNillableCreatedAt(v *time.Time) *OAuthClientCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OAuthClientCreate) SetUpdatedAt(v time.Time) *OAuthClientCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OAuthClientCreate) SetNillableUpdatedAt(v *time.Time) *OAuthClientCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetClientID sets the "client_id" field.
func (_c *OAuthClientCreate) SetClientID(v string) *OAuthClientCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *OAuthClientCreate) SetName(v string) *OAuthClientCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetClientSecretHash sets the "client_secret_hash" field.
func (_c *OAuthClientCreate) SetClientSecretHash(v string) *OAuthClientCreate {
	_c.mutation.SetClientSecretHash(v)
	return _c
}

// SetNillableClientSecretHash sets the "client_secret_hash" field if the given value is not nil.
func (_c *OAuthClientCreate) SetNillableClientSecretHash(v *string) *OAuthClientCreate {
	if v != nil {
		_c.SetClientSecretHash(*v)
	}
	return _c
}

// SetRedirectUris sets the "redirect_uris" field.
func (_c *OAuthClientCreate) SetRedirectUris(v []string) *OAuthClientCreate {
	_c.mutation.SetRedirectUris(v)
	return _c
}

// SetAllowedScopes sets the "allowed_scopes" field.
func (_c *OAuthClientCreate) SetAllowedScopes(v []string) *OAuthClientCreate {
	_c.mutation.SetAllowedScopes(v)
	return _c
}

// SetPkceRequired sets the "pkce_required" field.
func (_c *OAuthClientCreate) SetPkceRequired(v bool) *OAuthClientCreate {
	_c.mutation.SetPkceRequired(v)
	return _c
}

// SetNillablePkceRequired sets the "pkce_required" field if the given value is not nil.
func (_c *OAuthClientCreate) SetNillablePkceRequired(v *bool) *OAuthClientCreate {
	if v != nil {
		_c.SetPkceRequired(*v)
	}
	return _c
}

// SetDefaultGroupID sets the "default_group_id" field.
func (_c *OAuthClientCreate) SetDefaultGroupID(v int64) *OAuthClientCreate {
	_c.mutation.SetDefaultGroupID(v)
	return _c
}

// SetNillableDefaultGroupID sets the "default_group_id" field if the given value is not nil.
func (_c *OAuthClientCreate) SetNillableDefaultGroupID(v *int64) *OAuthClientCreate {
	if v != nil {
		_c.SetDefaultGroupID(*v)
	}
	return _c
}

// SetAccessTokenTTLSeconds sets the "access_token_ttl_seconds" field.
func (_c *OAuthClientCreate) SetAccessTokenTTLSeconds(v int) *OAuthClientCreate {
	_c.mutation.SetAccessTokenTTLSeconds(v)
	return _c
}

// SetNillableAccessTokenTTLSeconds sets the "access_token_ttl_seconds" field if the given value is not nil.
func (_c *OAuthClientCreate) SetNillableAccessTokenTTLSeconds(v *int) *OAuthClientCreate {
	if v != nil {
		_c.SetAccessTokenTTLSeconds(*v)
	}
	return _c
}

// SetRefreshTokenTTLSeconds sets the "refresh_token_ttl_seconds" field.
func (_c *OAuthClientCreate) SetRefreshTokenTTLSeconds(v int) *OAuthClientCreate {
	_c.mutation.SetRefreshTokenTTLSeconds(v)
	return _c
}

// SetNillableRefreshTokenTTLSeconds sets the "refresh_token_ttl_seconds" field if the given value is not nil.
func (_c *OAuthClientCreate) SetNillableRefreshTokenTTLSeconds(v *int) *OAuthClientCreate {
	if v != nil {
		_c.SetRefreshTokenTTLSeconds(*v)
	}
	return _c
}

// SetDisabled sets the "disabled" field.
func (_c *OAuthClientCreate) SetDisabled(v bool) *OAuthClientCreate {
	_c.mutation.SetDisabled(v)
	return _c
}

// SetNillableDisabled sets the "disabled" field if the given value is not nil.
func (_c *OAuthClientCreate) SetNillableDisabled(v *bool) *OAuthClientCreate {
	if v != nil {
		_c.SetDisabled(*v)
	}
	return _c
}

// SetClientType sets the "client_type" field.
func (_c *OAuthClientCreate) SetClientType(v string) *OAuthClientCreate {
	_c.mutation.SetClientType(v)
	return _c
}

// SetNillableClientType sets the "client_type" field if the given value is not nil.
func (_c *OAuthClientCreate) SetNillableClientType(v *string) *OAuthClientCreate {
	if v != nil {
		_c.SetClientType(*v)
	}
	return _c
}

// SetAppType sets the "app_type" field.
func (_c *OAuthClientCreate) SetAppType(v string) *OAuthClientCreate {
	_c.mutation.SetAppType(v)
	return _c
}

// SetNillableAppType sets the "app_type" field if the given value is not nil.
func (_c *OAuthClientCreate) SetNillableAppType(v *string) *OAuthClientCreate {
	if v != nil {
		_c.SetAppType(*v)
	}
	return _c
}

// SetTrustedFirstParty sets the "trusted_first_party" field.
func (_c *OAuthClientCreate) SetTrustedFirstParty(v bool) *OAuthClientCreate {
	_c.mutation.SetTrustedFirstParty(v)
	return _c
}

// SetNillableTrustedFirstParty sets the "trusted_first_party" field if the given value is not nil.
func (_c *OAuthClientCreate) SetNillableTrustedFirstParty(v *bool) *OAuthClientCreate {
	if v != nil {
		_c.SetTrustedFirstParty(*v)
	}
	return _c
}

// SetDefaultScopes sets the "default_scopes" field.
func (_c *OAuthClientCreate) SetDefaultScopes(v []string) *OAuthClientCreate {
	_c.mutation.SetDefaultScopes(v)
	return _c
}

// SetAllowedGroupIds sets the "allowed_group_ids" field.
func (_c *OAuthClientCreate) SetAllowedGroupIds(v []int64) *OAuthClientCreate {
	_c.mutation.SetAllowedGroupIds(v)
	return _c
}

// SetAllowedOrigins sets the "allowed_origins" field.
func (_c *OAuthClientCreate) SetAllowedOrigins(v []string) *OAuthClientCreate {
	_c.mutation.SetAllowedOrigins(v)
	return _c
}

// SetLogoutRedirectUris sets the "logout_redirect_uris" field.
func (_c *OAuthClientCreate) SetLogoutRedirectUris(v []string) *OAuthClientCreate {
	_c.mutation.SetLogoutRedirectUris(v)
	return _c
}

// SetDeviceFlowEnabled sets the "device_flow_enabled" field.
func (_c *OAuthClientCreate) SetDeviceFlowEnabled(v bool) *OAuthClientCreate {
	_c.mutation.SetDeviceFlowEnabled(v)
	return _c
}

// SetNillableDeviceFlowEnabled sets the "device_flow_enabled" field if the given value is not nil.
func (_c *OAuthClientCreate) SetNillableDeviceFlowEnabled(v *bool) *OAuthClientCreate {
	if v != nil {
		_c.SetDeviceFlowEnabled(*v)
	}
	return _c
}

// SetAllowRefreshWithoutOfflineAccess sets the "allow_refresh_without_offline_access" field.
func (_c *OAuthClientCreate) SetAllowRefreshWithoutOfflineAccess(v bool) *OAuthClientCreate {
	_c.mutation.SetAllowRefreshWithoutOfflineAccess(v)
	return _c
}

// SetNillableAllowRefreshWithoutOfflineAccess sets the "allow_refresh_without_offline_access" field if the given value is not nil.
func (_c *OAuthClientCreate) SetNillableAllowRefreshWithoutOfflineAccess(v *bool) *OAuthClientCreate {
	if v != nil {
		_c.SetAllowRefreshWithoutOfflineAccess(*v)
	}
	return _c
}

// SetIconURL sets the "icon_url" field.
func (_c *OAuthClientCreate) SetIconURL(v string) *OAuthClientCreate {
	_c.mutation.SetIconURL(v)
	return _c
}

// SetNillableIconURL sets the "icon_url" field if the given value is not nil.
func (_c *OAuthClientCreate) SetNillableIconURL(v *string) *OAuthClientCreate {
	if v != nil {
		_c.SetIconURL(*v)
	}
	return _c
}

// SetHomepageURL sets the "homepage_url" field.
func (_c *OAuthClientCreate) SetHomepageURL(v string) *OAuthClientCreate {
	_c.mutation.SetHomepageURL(v)
	return _c
}

// SetNillableHomepageURL sets the "homepage_url" field if the given value is not nil.
func (_c *OAuthClientCreate) SetNillableHomepageURL(v *string) *OAuthClientCreate {
	if v != nil {
		_c.SetHomepageURL(*v)
	}
	return _c
}

// SetPrivacyURL sets the "privacy_url" field.
func (_c *OAuthClientCreate) SetPrivacyURL(v string) *OAuthClientCreate {
	_c.mutation.SetPrivacyURL(v)
	return _c
}

// SetNillablePrivacyURL sets the "privacy_url" field if the given value is not nil.
func (_c *OAuthClientCreate) SetNillablePrivacyURL(v *string) *OAuthClientCreate {
	if v != nil {
		_c.SetPrivacyURL(*v)
	}
	return _c
}

// SetTermsURL sets the "terms_url" field.
func (_c *OAuthClientCreate) SetTermsURL(v string) *OAuthClientCreate {
	_c.mutation.SetTermsURL(v)
	return _c
}

// SetNillableTermsURL sets the "terms_url" field if the given value is not nil.
func (_c *OAuthClientCreate) SetNillableTermsURL(v *string) *OAuthClientCreate {
	if v != nil {
		_c.SetTermsURL(*v)
	}
	return _c
}

// Mutation returns the OAuthClientMutation object of the builder.
func (_c *OAuthClientCreate) Mutation() *OAuthClientMutation {
	return _c.mutation
}

// Save creates the OAuthClient in the database.
func (_c *OAuthClientCreate) Save(ctx context.Context) (*OAuthClient, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OAuthClientCreate) SaveX(ctx context.Context) *OAuthClient {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthClientCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthClientCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OAuthClientCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := oauthclient.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := oauthclient.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.PkceRequired(); !ok {
		v := oauthclient.DefaultPkceRequired
		_c.mutation.SetPkceRequired(v)
	}
	if _, ok := _c.mutation.AccessTokenTTLSeconds(); !ok {
		v := oauthclient.DefaultAccessTokenTTLSeconds
		_c.mutation.SetAccessTokenTTLSeconds(v)
	}
	if _, ok := _c.mutation.RefreshTokenTTLSeconds(); !ok {
		v := oauthclient.DefaultRefreshTokenTTLSeconds
		_c.mutation.SetRefreshTokenTTLSeconds(v)
	}
	if _, ok := _c.mutation.Disabled(); !ok {
		v := oauthclient.DefaultDisabled
		_c.mutation.SetDisabled(v)
	}
	if _, ok := _c.mutation.ClientType(); !ok {
		v := oauthclient.DefaultClientType
		_c.mutation.SetClientType(v)
	}
	if _, ok := _c.mutation.AppType(); !ok {
		v := oauthclient.DefaultAppType
		_c.mutation.SetAppType(v)
	}
	if _, ok := _c.mutation.TrustedFirstParty(); !ok {
		v := oauthclient.DefaultTrustedFirstParty
		_c.mutation.SetTrustedFirstParty(v)
	}
	if _, ok := _c.mutation.DefaultScopes(); !ok {
		v := oauthclient.DefaultDefaultScopes
		_c.mutation.SetDefaultScopes(v)
	}
	if _, ok := _c.mutation.AllowedOrigins(); !ok {
		v := oauthclient.DefaultAllowedOrigins
		_c.mutation.SetAllowedOrigins(v)
	}
	if _, ok := _c.mutation.LogoutRedirectUris(); !ok {
		v := oauthclient.DefaultLogoutRedirectUris
		_c.mutation.SetLogoutRedirectUris(v)
	}
	if _, ok := _c.mutation.DeviceFlowEnabled(); !ok {
		v := oauthclient.DefaultDeviceFlowEnabled
		_c.mutation.SetDeviceFlowEnabled(v)
	}
	if _, ok := _c.mutation.AllowRefreshWithoutOfflineAccess(); !ok {
		v := oauthclient.DefaultAllowRefreshWithoutOfflineAccess
		_c.mutation.SetAllowRefreshWithoutOfflineAccess(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OAuthClientCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OAuthClient.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OAuthClient.updated_at"`)}
	}
	if _, ok := _c.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`ent: missing required field "OAuthClient.client_id"`)}
	}
	if v, ok := _c.mutation.ClientID(); ok {
		if err := oauthclient.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "OAuthClient.client_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "OAuthClient.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := oauthclient.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "OAuthClient.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RedirectUris(); !ok {
		return &ValidationError{Name: "redirect_uris", err: errors.New(`ent: missing required field "OAuthClient.redirect_uris"`)}
	}
	if _, ok := _c.mutation.AllowedScopes(); !ok {
		return &ValidationError{Name: "allowed_scopes", err: errors.New(`ent: missing required field "OAuthClient.allowed_scopes"`)}
	}
	if _, ok := _c.mutation.PkceRequired(); !ok {
		return &ValidationError{Name: "pkce_required", err: errors.New(`ent: missing required field "OAuthClient.pkce_required"`)}
	}
	if _, ok := _c.mutation.AccessTokenTTLSeconds(); !ok {
		return &ValidationError{Name: "access_token_ttl_seconds", err: errors.New(`ent: missing required field "OAuthClient.access_token_ttl_seconds"`)}
	}
	if _, ok := _c.mutation.RefreshTokenTTLSeconds(); !ok {
		return &ValidationError{Name: "refresh_token_ttl_seconds", err: errors.New(`ent: missing required field "OAuthClient.refresh_token_ttl_seconds"`)}
	}
	if _, ok := _c.mutation.Disabled(); !ok {
		return &ValidationError{Name: "disabled", err: errors.New(`ent: missing required field "OAuthClient.disabled"`)}
	}
	if _, ok := _c.mutation.ClientType(); !ok {
		return &ValidationError{Name: "client_type", err: errors.New(`ent: missing required field "OAuthClient.client_type"`)}
	}
	if v, ok := _c.mutation.ClientType(); ok {
		if err := oauthclient.ClientTypeValidator(v); err != nil {
			return &ValidationError{Name: "client_type", err: fmt.Errorf(`ent: validator failed for field "OAuthClient.client_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AppType(); !ok {
		return &ValidationError{Name: "app_type", err: errors.New(`ent: missing required field "OAuthClient.app_type"`)}
	}
	if v, ok := _c.mutation.AppType(); ok {
		if err := oauthclient.AppTypeValidator(v); err != nil {
			return &ValidationError{Name: "app_type", err: fmt.Errorf(`ent: validator failed for field "OAuthClient.app_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TrustedFirstParty(); !ok {
		return &ValidationError{Name: "trusted_first_party", err: errors.New(`ent: missing required field "OAuthClient.trusted_first_party"`)}
	}
	if _, ok := _c.mutation.DefaultScopes(); !ok {
		return &ValidationError{Name: "default_scopes", err: errors.New(`ent: missing required field "OAuthClient.default_scopes"`)}
	}
	if _, ok := _c.mutation.AllowedOrigins(); !ok {
		return &ValidationError{Name: "allowed_origins", err: errors.New(`ent: missing required field "OAuthClient.allowed_origins"`)}
	}
	if _, ok := _c.mutation.LogoutRedirectUris(); !ok {
		return &ValidationError{Name: "logout_redirect_uris", err: errors.New(`ent: missing required field "OAuthClient.logout_redirect_uris"`)}
	}
	if _, ok := _c.mutation.DeviceFlowEnabled(); !ok {
		return &ValidationError{Name: "device_flow_enabled", err: errors.New(`ent: missing required field "OAuthClient.device_flow_enabled"`)}
	}
	if _, ok := _c.mutation.AllowRefreshWithoutOfflineAccess(); !ok {
		return &ValidationError{Name: "allow_refresh_without_offline_access", err: errors.New(`ent: missing required field "OAuthClient.allow_refresh_without_offline_access"`)}
	}
	return nil
}

func (_c *OAuthClientCreate) sqlSave(ctx context.Context) (*OAuthClient, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OAuthClientCreate) createSpec() (*OAuthClient, *sqlgraph.CreateSpec) {
	var (
		_node = &OAuthClient{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(oauthclient.Table, sqlgraph.NewFieldSpec(oauthclient.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(oauthclient.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthclient.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(oauthclient.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(oauthclient.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.ClientSecretHash(); ok {
		_spec.SetField(oauthclient.FieldClientSecretHash, field.TypeString, value)
		_node.ClientSecretHash = &value
	}
	if value, ok := _c.mutation.RedirectUris(); ok {
		_spec.SetField(oauthclient.FieldRedirectUris, field.TypeJSON, value)
		_node.RedirectUris = value
	}
	if value, ok := _c.mutation.AllowedScopes(); ok {
		_spec.SetField(oauthclient.FieldAllowedScopes, field.TypeJSON, value)
		_node.AllowedScopes = value
	}
	if value, ok := _c.mutation.PkceRequired(); ok {
		_spec.SetField(oauthclient.FieldPkceRequired, field.TypeBool, value)
		_node.PkceRequired = value
	}
	if value, ok := _c.mutation.DefaultGroupID(); ok {
		_spec.SetField(oauthclient.FieldDefaultGroupID, field.TypeInt64, value)
		_node.DefaultGroupID = &value
	}
	if value, ok := _c.mutation.AccessTokenTTLSeconds(); ok {
		_spec.SetField(oauthclient.FieldAccessTokenTTLSeconds, field.TypeInt, value)
		_node.AccessTokenTTLSeconds = value
	}
	if value, ok := _c.mutation.RefreshTokenTTLSeconds(); ok {
		_spec.SetField(oauthclient.FieldRefreshTokenTTLSeconds, field.TypeInt, value)
		_node.RefreshTokenTTLSeconds = value
	}
	if value, ok := _c.mutation.Disabled(); ok {
		_spec.SetField(oauthclient.FieldDisabled, field.TypeBool, value)
		_node.Disabled = value
	}
	if value, ok := _c.mutation.ClientType(); ok {
		_spec.SetField(oauthclient.FieldClientType, field.TypeString, value)
		_node.ClientType = value
	}
	if value, ok := _c.mutation.AppType(); ok {
		_spec.SetField(oauthclient.FieldAppType, field.TypeString, value)
		_node.AppType = value
	}
	if value, ok := _c.mutation.TrustedFirstParty(); ok {
		_spec.SetField(oauthclient.FieldTrustedFirstParty, field.TypeBool, value)
		_node.TrustedFirstParty = value
	}
	if value, ok := _c.mutation.DefaultScopes(); ok {
		_spec.SetField(oauthclient.FieldDefaultScopes, field.TypeJSON, value)
		_node.DefaultScopes = value
	}
	if value, ok := _c.mutation.AllowedGroupIds(); ok {
		_spec.SetField(oauthclient.FieldAllowedGroupIds, field.TypeJSON, value)
		_node.AllowedGroupIds = value
	}
	if value, ok := _c.mutation.AllowedOrigins(); ok {
		_spec.SetField(oauthclient.FieldAllowedOrigins, field.TypeJSON, value)
		_node.AllowedOrigins = value
	}
	if value, ok := _c.mutation.LogoutRedirectUris(); ok {
		_spec.SetField(oauthclient.FieldLogoutRedirectUris, field.TypeJSON, value)
		_node.LogoutRedirectUris = value
	}
	if value, ok := _c.mutation.DeviceFlowEnabled(); ok {
		_spec.SetField(oauthclient.FieldDeviceFlowEnabled, field.TypeBool, value)
		_node.DeviceFlowEnabled = value
	}
	if value, ok := _c.mutation.AllowRefreshWithoutOfflineAccess(); ok {
		_spec.SetField(oauthclient.FieldAllowRefreshWithoutOfflineAccess, field.TypeBool, value)
		_node.AllowRefreshWithoutOfflineAccess = value
	}
	if value, ok := _c.mutation.IconURL(); ok {
		_spec.SetField(oauthclient.FieldIconURL, field.TypeString, value)
		_node.IconURL = &value
	}
	if value, ok := _c.mutation.HomepageURL(); ok {
		_spec.SetField(oauthclient.FieldHomepageURL, field.TypeString, value)
		_node.HomepageURL = &value
	}
	if value, ok := _c.mutation.PrivacyURL(); ok {
		_spec.SetField(oauthclient.FieldPrivacyURL, field.TypeString, value)
		_node.PrivacyURL = &value
	}
	if value, ok := _c.mutation.TermsURL(); ok {
		_spec.SetField(oauthclient.FieldTermsURL, field.TypeString, value)
		_node.TermsURL = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OAuthClient.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OAuthClientUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OAuthClientCreate) OnConflict(opts ...sql.ConflictOption) *OAuthClientUpsertOne {
	_c.conflict = opts
	return &OAuthClientUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OAuthClient.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OAuthClientCreate) OnConflictColumns(columns ...string) *OAuthClientUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OAuthClientUpsertOne{
		create: _c,
	}
}

type (
	// OAuthClientUpsertOne is the builder for "upsert"-ing
	//  one OAuthClient node.
	OAuthClientUpsertOne struct {
		create *OAuthClientCreate
	}

	// OAuthClientUpsert is the "OnConflict" setter.
	OAuthClientUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *OAuthClientUpsert) SetUpdatedAt(v time.Time) *OAuthClientUpsert {
	u.Set(oauthclient.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OAuthClientUpsert) UpdateUpdatedAt() *OAuthClientUpsert {
	u.SetExcluded(oauthclient.FieldUpdatedAt)
	return u
}

// SetClientID sets the "client_id" field.
func (u *OAuthClientUpsert) SetClientID(v string) *OAuthClientUpsert {
	u.Set(oauthclient.FieldClientID, v)
	return u
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *OAuthClientUpsert) UpdateClientID() *OAuthClientUpsert {
	u.SetExcluded(oauthclient.FieldClientID)
	return u
}

// SetName sets the "name" field.
func (u *OAuthClientUpsert) SetName(v string) *OAuthClientUpsert {
	u.Set(oauthclient.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *OAuthClientUpsert) UpdateName() *OAuthClientUpsert {
	u.SetExcluded(oauthclient.FieldName)
	return u
}

// SetClientSecretHash sets the "client_secret_hash" field.
func (u *OAuthClientUpsert) SetClientSecretHash(v string) *OAuthClientUpsert {
	u.Set(oauthclient.FieldClientSecretHash, v)
	return u
}

// UpdateClientSecretHash sets the "client_secret_hash" field to the value that was provided on create.
func (u *OAuthClientUpsert) UpdateClientSecretHash() *OAuthClientUpsert {
	u.SetExcluded(oauthclient.FieldClientSecretHash)
	return u
}

// ClearClientSecretHash clears the value of the "client_secret_hash" field.
func (u *OAuthClientUpsert) ClearClientSecretHash() *OAuthClientUpsert {
	u.SetNull(oauthclient.FieldClientSecretHash)
	return u
}

// SetRedirectUris sets the "redirect_uris" field.
func (u *OAuthClientUpsert) SetRedirectUris(v []string) *OAuthClientUpsert {
	u.Set(oauthclient.FieldRedirectUris, v)
	return u
}

// UpdateRedirectUris sets the "redirect_uris" field to the value that was provided on create.
func (u *OAuthClientUpsert) UpdateRedirectUris() *OAuthClientUpsert {
	u.SetExcluded(oauthclient.FieldRedirectUris)
	return u
}

// SetAllowedScopes sets the "allowed_scopes" field.
func (u *OAuthClientUpsert) SetAllowedScopes(v []string) *OAuthClientUpsert {
	u.Set(oauthclient.FieldAllowedScopes, v)
	return u
}

// UpdateAllowedScopes sets the "allowed_scopes" field to the value that was provided on create.
func (u *OAuthClientUpsert) UpdateAllowedScopes() *OAuthClientUpsert {
	u.SetExcluded(oauthclient.FieldAllowedScopes)
	return u
}

// SetPkceRequired sets the "pkce_required" field.
func (u *OAuthClientUpsert) SetPkceRequired(v bool) *OAuthClientUpsert {
	u.Set(oauthclient.FieldPkceRequired, v)
	return u
}

// UpdatePkceRequired sets the "pkce_required" field to the value that was provided on create.
func (u *OAuthClientUpsert) UpdatePkceRequired() *OAuthClientUpsert {
	u.SetExcluded(oauthclient.FieldPkceRequired)
	return u
}

// SetDefaultGroupID sets the "default_group_id" field.
func (u *OAuthClientUpsert) SetDefaultGroupID(v int64) *OAuthClientUpsert {
	u.Set(oauthclient.FieldDefaultGroupID, v)
	return u
}

// UpdateDefaultGroupID sets the "default_group_id" field to the value that was provided on create.
func (u *OAuthClientUpsert) UpdateDefaultGroupID() *OAuthClientUpsert {
	u.SetExcluded(oauthclient.FieldDefaultGroupID)
	return u
}

// AddDefaultGroupID adds v to the "default_group_id" field.
func (u *OAuthClientUpsert) AddDefaultGroupID(v int64) *OAuthClientUpsert {
	u.Add(oauthclient.FieldDefaultGroupID, v)
	return u
}

// ClearDefaultGroupID clears the value of the "default_group_id" field.
func (u *OAuthClientUpsert) ClearDefaultGroupID() *OAuthClientUpsert {
	u.SetNull(oauthclient.FieldDefaultGroupID)
	return u
}

// SetAccessTokenTTLSeconds sets the "access_token_ttl_seconds" field.
func (u *OAuthClientUpsert) SetAccessTokenTTLSeconds(v int) *OAuthClientUpsert {
	u.Set(oauthclient.FieldAccessTokenTTLSeconds, v)
	return u
}

// UpdateAccessTokenTTLSeconds sets the "access_token_ttl_seconds" field to the value that was provided on create.
func (u *OAuthClientUpsert) UpdateAccessTokenTTLSeconds() *OAuthClientUpsert {
	u.SetExcluded(oauthclient.FieldAccessTokenTTLSeconds)
	return u
}

// AddAccessTokenTTLSeconds adds v to the "access_token_ttl_seconds" field.
func (u *OAuthClientUpsert) AddAccessTokenTTLSeconds(v int) *OAuthClientUpsert {
	u.Add(oauthclient.FieldAccessTokenTTLSeconds, v)
	return u
}

// SetRefreshTokenTTLSeconds sets the "refresh_token_ttl_seconds" field.
func (u *OAuthClientUpsert) SetRefreshTokenTTLSeconds(v int) *OAuthClientUpsert {
	u.Set(oauthclient.FieldRefreshTokenTTLSeconds, v)
	return u
}

// UpdateRefreshTokenTTLSeconds sets the "refresh_token_ttl_seconds" field to the value that was provided on create.
func (u *OAuthClientUpsert) UpdateRefreshTokenTTLSeconds() *OAuthClientUpsert {
	u.SetExcluded(oauthclient.FieldRefreshTokenTTLSeconds)
	return u
}

// AddRefreshTokenTTLSeconds adds v to the "refresh_token_ttl_seconds" field.
func (u *OAuthClientUpsert) AddRefreshTokenTTLSeconds(v int) *OAuthClientUpsert {
	u.Add(oauthclient.FieldRefreshTokenTTLSeconds, v)
	return u
}

// SetDisabled sets the "disabled" field.
func (u *OAuthClientUpsert) SetDisabled(v bool) *OAuthClientUpsert {
	u.Set(oauthclient.FieldDisabled, v)
	return u
}

// UpdateDisabled sets the "disabled" field to the value that was provided on create.
func (u *OAuthClientUpsert) UpdateDisabled() *OAuthClientUpsert {
	u.SetExcluded(oauthclient.FieldDisabled)
	return u
}

// SetClientType sets the "client_type" field.
func (u *OAuthClientUpsert) SetClientType(v string) *OAuthClientUpsert {
	u.Set(oauthclient.FieldClientType, v)
	return u
}

// UpdateClientType sets the "client_type" field to the value that was provided on create.
func (u *OAuthClientUpsert) UpdateClientType() *OAuthClientUpsert {
	u.SetExcluded(oauthclient.FieldClientType)
	return u
}

// SetAppType sets the "app_type" field.
func (u *OAuthClientUpsert) SetAppType(v string) *OAuthClientUpsert {
	u.Set(oauthclient.FieldAppType, v)
	return u
}

// UpdateAppType sets the "app_type" field to the value that was provided on create.
func (u *OAuthClientUpsert) UpdateAppType() *OAuthClientUpsert {
	u.SetExcluded(oauthclient.FieldAppType)
	return u
}

// SetTrustedFirstParty sets the "trusted_first_party" field.
func (u *OAuthClientUpsert) SetTrustedFirstParty(v bool) *OAuthClientUpsert {
	u.Set(oauthclient.FieldTrustedFirstParty, v)
	return u
}

// UpdateTrustedFirstParty sets the "trusted_first_party" field to the value that was provided on create.
func (u *OAuthClientUpsert) UpdateTrustedFirstParty() *OAuthClientUpsert {
	u.SetExcluded(oauthclient.FieldTrustedFirstParty)
	return u
}

// SetDefaultScopes sets the "default_scopes" field.
func (u *OAuthClientUpsert) SetDefaultScopes(v []string) *OAuthClientUpsert {
	u.Set(oauthclient.FieldDefaultScopes, v)
	return u
}

// UpdateDefaultScopes sets the "default_scopes" field to the value that was provided on create.
func (u *OAuthClientUpsert) UpdateDefaultScopes() *OAuthClientUpsert {
	u.SetExcluded(oauthclient.FieldDefaultScopes)
	return u
}

// SetAllowedGroupIds sets the "allowed_group_ids" field.
func (u *OAuthClientUpsert) SetAllowedGroupIds(v []int64) *OAuthClientUpsert {
	u.Set(oauthclient.FieldAllowedGroupIds, v)
	return u
}

// UpdateAllowedGroupIds sets the "allowed_group_ids" field to the value that was provided on create.
func (u *OAuthClientUpsert) UpdateAllowedGroupIds() *OAuthClientUpsert {
	u.SetExcluded(oauthclient.FieldAllowedGroupIds)
	return u
}

// ClearAllowedGroupIds clears the value of the "allowed_group_ids" field.
func (u *OAuthClientUpsert) ClearAllowedGroupIds() *OAuthClientUpsert {
	u.SetNull(oauthclient.FieldAllowedGroupIds)
	return u
}

// SetAllowedOrigins sets the "allowed_origins" field.
func (u *OAuthClientUpsert) SetAllowedOrigins(v []string) *OAuthClientUpsert {
	u.Set(oauthclient.FieldAllowedOrigins, v)
	return u
}

// UpdateAllowedOrigins sets the "allowed_origins" field to the value that was provided on create.
func (u *OAuthClientUpsert) UpdateAllowedOrigins() *OAuthClientUpsert {
	u.SetExcluded(oauthclient.FieldAllowedOrigins)
	return u
}

// SetLogoutRedirectUris sets the "logout_redirect_uris" field.
func (u *OAuthClientUpsert) SetLogoutRedirectUris(v []string) *OAuthClientUpsert {
	u.Set(oauthclient.FieldLogoutRedirectUris, v)
	return u
}

// UpdateLogoutRedirectUris sets the "logout_redirect_uris" field to the value that was provided on create.
func (u *OAuthClientUpsert) UpdateLogoutRedirectUris() *OAuthClientUpsert {
	u.SetExcluded(oauthclient.FieldLogoutRedirectUris)
	return u
}

// SetDeviceFlowEnabled sets the "device_flow_enabled" field.
func (u *OAuthClientUpsert) SetDeviceFlowEnabled(v bool) *OAuthClientUpsert {
	u.Set(oauthclient.FieldDeviceFlowEnabled, v)
	return u
}

// UpdateDeviceFlowEnabled sets the "device_flow_enabled" field to the value that was provided on create.
func (u *OAuthClientUpsert) UpdateDeviceFlowEnabled() *OAuthClientUpsert {
	u.SetExcluded(oauthclient.FieldDeviceFlowEnabled)
	return u
}

// SetAllowRefreshWithoutOfflineAccess sets the "allow_refresh_without_offline_access" field.
func (u *OAuthClientUpsert) SetAllowRefreshWithoutOfflineAccess(v bool) *OAuthClientUpsert {
	u.Set(oauthclient.FieldAllowRefreshWithoutOfflineAccess, v)
	return u
}

// UpdateAllowRefreshWithoutOfflineAccess sets the "allow_refresh_without_offline_access" field to the value that was provided on create.
func (u *OAuthClientUpsert) UpdateAllowRefreshWithoutOfflineAccess() *OAuthClientUpsert {
	u.SetExcluded(oauthclient.FieldAllowRefreshWithoutOfflineAccess)
	return u
}

// SetIconURL sets the "icon_url" field.
func (u *OAuthClientUpsert) SetIconURL(v string) *OAuthClientUpsert {
	u.Set(oauthclient.FieldIconURL, v)
	return u
}

// UpdateIconURL sets the "icon_url" field to the value that was provided on create.
func (u *OAuthClientUpsert) UpdateIconURL() *OAuthClientUpsert {
	u.SetExcluded(oauthclient.FieldIconURL)
	return u
}

// ClearIconURL clears the value of the "icon_url" field.
func (u *OAuthClientUpsert) ClearIconURL() *OAuthClientUpsert {
	u.SetNull(oauthclient.FieldIconURL)
	return u
}

// SetHomepageURL sets the "homepage_url" field.
func (u *OAuthClientUpsert) SetHomepageURL(v string) *OAuthClientUpsert {
	u.Set(oauthclient.FieldHomepageURL, v)
	return u
}

// UpdateHomepageURL sets the "homepage_url" field to the value that was provided on create.
func (u *OAuthClientUpsert) UpdateHomepageURL() *OAuthClientUpsert {
	u.SetExcluded(oauthclient.FieldHomepageURL)
	return u
}

// ClearHomepageURL clears the value of the "homepage_url" field.
func (u *OAuthClientUpsert) ClearHomepageURL() *OAuthClientUpsert {
	u.SetNull(oauthclient.FieldHomepageURL)
	return u
}

// SetPrivacyURL sets the "privacy_url" field.
func (u *OAuthClientUpsert) SetPrivacyURL(v string) *OAuthClientUpsert {
	u.Set(oauthclient.FieldPrivacyURL, v)
	return u
}

// UpdatePrivacyURL sets the "privacy_url" field to the value that was provided on create.
func (u *OAuthClientUpsert) UpdatePrivacyURL() *OAuthClientUpsert {
	u.SetExcluded(oauthclient.FieldPrivacyURL)
	return u
}

// ClearPrivacyURL clears the value of the "privacy_url" field.
func (u *OAuthClientUpsert) ClearPrivacyURL() *OAuthClientUpsert {
	u.SetNull(oauthclient.FieldPrivacyURL)
	return u
}

// SetTermsURL sets the "terms_url" field.
func (u *OAuthClientUpsert) SetTermsURL(v string) *OAuthClientUpsert {
	u.Set(oauthclient.FieldTermsURL, v)
	return u
}

// UpdateTermsURL sets the "terms_url" field to the value that was provided on create.
func (u *OAuthClientUpsert) UpdateTermsURL() *OAuthClientUpsert {
	u.SetExcluded(oauthclient.FieldTermsURL)
	return u
}

// ClearTermsURL clears the value of the "terms_url" field.
func (u *OAuthClientUpsert) ClearTermsURL() *OAuthClientUpsert {
	u.SetNull(oauthclient.FieldTermsURL)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.OAuthClient.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OAuthClientUpsertOne) UpdateNewValues() *OAuthClientUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(oauthclient.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OAuthClient.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OAuthClientUpsertOne) Ignore() *OAuthClientUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OAuthClientUpsertOne) DoNothing() *OAuthClientUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OAuthClientCreate.OnConflict
// documentation for more info.
func (u *OAuthClientUpsertOne) Update(set func(*OAuthClientUpsert)) *OAuthClientUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OAuthClientUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OAuthClientUpsertOne) SetUpdatedAt(v time.Time) *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OAuthClientUpsertOne) UpdateUpdatedAt() *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetClientID sets the "client_id" field.
func (u *OAuthClientUpsertOne) SetClientID(v string) *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *OAuthClientUpsertOne) UpdateClientID() *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateClientID()
	})
}

// SetName sets the "name" field.
func (u *OAuthClientUpsertOne) SetName(v string) *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *OAuthClientUpsertOne) UpdateName() *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateName()
	})
}

// SetClientSecretHash sets the "client_secret_hash" field.
func (u *OAuthClientUpsertOne) SetClientSecretHash(v string) *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetClientSecretHash(v)
	})
}

// UpdateClientSecretHash sets the "client_secret_hash" field to the value that was provided on create.
func (u *OAuthClientUpsertOne) UpdateClientSecretHash() *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateClientSecretHash()
	})
}

// ClearClientSecretHash clears the value of the "client_secret_hash" field.
func (u *OAuthClientUpsertOne) ClearClientSecretHash() *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.ClearClientSecretHash()
	})
}

// SetRedirectUris sets the "redirect_uris" field.
func (u *OAuthClientUpsertOne) SetRedirectUris(v []string) *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetRedirectUris(v)
	})
}

// UpdateRedirectUris sets the "redirect_uris" field to the value that was provided on create.
func (u *OAuthClientUpsertOne) UpdateRedirectUris() *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateRedirectUris()
	})
}

// SetAllowedScopes sets the "allowed_scopes" field.
func (u *OAuthClientUpsertOne) SetAllowedScopes(v []string) *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetAllowedScopes(v)
	})
}

// UpdateAllowedScopes sets the "allowed_scopes" field to the value that was provided on create.
func (u *OAuthClientUpsertOne) UpdateAllowedScopes() *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateAllowedScopes()
	})
}

// SetPkceRequired sets the "pkce_required" field.
func (u *OAuthClientUpsertOne) SetPkceRequired(v bool) *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetPkceRequired(v)
	})
}

// UpdatePkceRequired sets the "pkce_required" field to the value that was provided on create.
func (u *OAuthClientUpsertOne) UpdatePkceRequired() *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdatePkceRequired()
	})
}

// SetDefaultGroupID sets the "default_group_id" field.
func (u *OAuthClientUpsertOne) SetDefaultGroupID(v int64) *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetDefaultGroupID(v)
	})
}

// AddDefaultGroupID adds v to the "default_group_id" field.
func (u *OAuthClientUpsertOne) AddDefaultGroupID(v int64) *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.AddDefaultGroupID(v)
	})
}

// UpdateDefaultGroupID sets the "default_group_id" field to the value that was provided on create.
func (u *OAuthClientUpsertOne) UpdateDefaultGroupID() *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateDefaultGroupID()
	})
}

// ClearDefaultGroupID clears the value of the "default_group_id" field.
func (u *OAuthClientUpsertOne) ClearDefaultGroupID() *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.ClearDefaultGroupID()
	})
}

// SetAccessTokenTTLSeconds sets the "access_token_ttl_seconds" field.
func (u *OAuthClientUpsertOne) SetAccessTokenTTLSeconds(v int) *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetAccessTokenTTLSeconds(v)
	})
}

// AddAccessTokenTTLSeconds adds v to the "access_token_ttl_seconds" field.
func (u *OAuthClientUpsertOne) AddAccessTokenTTLSeconds(v int) *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.AddAccessTokenTTLSeconds(v)
	})
}

// UpdateAccessTokenTTLSeconds sets the "access_token_ttl_seconds" field to the value that was provided on create.
func (u *OAuthClientUpsertOne) UpdateAccessTokenTTLSeconds() *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateAccessTokenTTLSeconds()
	})
}

// SetRefreshTokenTTLSeconds sets the "refresh_token_ttl_seconds" field.
func (u *OAuthClientUpsertOne) SetRefreshTokenTTLSeconds(v int) *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetRefreshTokenTTLSeconds(v)
	})
}

// AddRefreshTokenTTLSeconds adds v to the "refresh_token_ttl_seconds" field.
func (u *OAuthClientUpsertOne) AddRefreshTokenTTLSeconds(v int) *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.AddRefreshTokenTTLSeconds(v)
	})
}

// UpdateRefreshTokenTTLSeconds sets the "refresh_token_ttl_seconds" field to the value that was provided on create.
func (u *OAuthClientUpsertOne) UpdateRefreshTokenTTLSeconds() *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateRefreshTokenTTLSeconds()
	})
}

// SetDisabled sets the "disabled" field.
func (u *OAuthClientUpsertOne) SetDisabled(v bool) *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetDisabled(v)
	})
}

// UpdateDisabled sets the "disabled" field to the value that was provided on create.
func (u *OAuthClientUpsertOne) UpdateDisabled() *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateDisabled()
	})
}

// SetClientType sets the "client_type" field.
func (u *OAuthClientUpsertOne) SetClientType(v string) *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetClientType(v)
	})
}

// UpdateClientType sets the "client_type" field to the value that was provided on create.
func (u *OAuthClientUpsertOne) UpdateClientType() *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateClientType()
	})
}

// SetAppType sets the "app_type" field.
func (u *OAuthClientUpsertOne) SetAppType(v string) *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetAppType(v)
	})
}

// UpdateAppType sets the "app_type" field to the value that was provided on create.
func (u *OAuthClientUpsertOne) UpdateAppType() *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateAppType()
	})
}

// SetTrustedFirstParty sets the "trusted_first_party" field.
func (u *OAuthClientUpsertOne) SetTrustedFirstParty(v bool) *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetTrustedFirstParty(v)
	})
}

// UpdateTrustedFirstParty sets the "trusted_first_party" field to the value that was provided on create.
func (u *OAuthClientUpsertOne) UpdateTrustedFirstParty() *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateTrustedFirstParty()
	})
}

// SetDefaultScopes sets the "default_scopes" field.
func (u *OAuthClientUpsertOne) SetDefaultScopes(v []string) *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetDefaultScopes(v)
	})
}

// UpdateDefaultScopes sets the "default_scopes" field to the value that was provided on create.
func (u *OAuthClientUpsertOne) UpdateDefaultScopes() *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateDefaultScopes()
	})
}

// SetAllowedGroupIds sets the "allowed_group_ids" field.
func (u *OAuthClientUpsertOne) SetAllowedGroupIds(v []int64) *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetAllowedGroupIds(v)
	})
}

// UpdateAllowedGroupIds sets the "allowed_group_ids" field to the value that was provided on create.
func (u *OAuthClientUpsertOne) UpdateAllowedGroupIds() *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateAllowedGroupIds()
	})
}

// ClearAllowedGroupIds clears the value of the "allowed_group_ids" field.
func (u *OAuthClientUpsertOne) ClearAllowedGroupIds() *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.ClearAllowedGroupIds()
	})
}

// SetAllowedOrigins sets the "allowed_origins" field.
func (u *OAuthClientUpsertOne) SetAllowedOrigins(v []string) *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetAllowedOrigins(v)
	})
}

// UpdateAllowedOrigins sets the "allowed_origins" field to the value that was provided on create.
func (u *OAuthClientUpsertOne) UpdateAllowedOrigins() *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateAllowedOrigins()
	})
}

// SetLogoutRedirectUris sets the "logout_redirect_uris" field.
func (u *OAuthClientUpsertOne) SetLogoutRedirectUris(v []string) *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetLogoutRedirectUris(v)
	})
}

// UpdateLogoutRedirectUris sets the "logout_redirect_uris" field to the value that was provided on create.
func (u *OAuthClientUpsertOne) UpdateLogoutRedirectUris() *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateLogoutRedirectUris()
	})
}

// SetDeviceFlowEnabled sets the "device_flow_enabled" field.
func (u *OAuthClientUpsertOne) SetDeviceFlowEnabled(v bool) *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetDeviceFlowEnabled(v)
	})
}

// UpdateDeviceFlowEnabled sets the "device_flow_enabled" field to the value that was provided on create.
func (u *OAuthClientUpsertOne) UpdateDeviceFlowEnabled() *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateDeviceFlowEnabled()
	})
}

// SetAllowRefreshWithoutOfflineAccess sets the "allow_refresh_without_offline_access" field.
func (u *OAuthClientUpsertOne) SetAllowRefreshWithoutOfflineAccess(v bool) *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetAllowRefreshWithoutOfflineAccess(v)
	})
}

// UpdateAllowRefreshWithoutOfflineAccess sets the "allow_refresh_without_offline_access" field to the value that was provided on create.
func (u *OAuthClientUpsertOne) UpdateAllowRefreshWithoutOfflineAccess() *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateAllowRefreshWithoutOfflineAccess()
	})
}

// SetIconURL sets the "icon_url" field.
func (u *OAuthClientUpsertOne) SetIconURL(v string) *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetIconURL(v)
	})
}

// UpdateIconURL sets the "icon_url" field to the value that was provided on create.
func (u *OAuthClientUpsertOne) UpdateIconURL() *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateIconURL()
	})
}

// ClearIconURL clears the value of the "icon_url" field.
func (u *OAuthClientUpsertOne) ClearIconURL() *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.ClearIconURL()
	})
}

// SetHomepageURL sets the "homepage_url" field.
func (u *OAuthClientUpsertOne) SetHomepageURL(v string) *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetHomepageURL(v)
	})
}

// UpdateHomepageURL sets the "homepage_url" field to the value that was provided on create.
func (u *OAuthClientUpsertOne) UpdateHomepageURL() *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateHomepageURL()
	})
}

// ClearHomepageURL clears the value of the "homepage_url" field.
func (u *OAuthClientUpsertOne) ClearHomepageURL() *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.ClearHomepageURL()
	})
}

// SetPrivacyURL sets the "privacy_url" field.
func (u *OAuthClientUpsertOne) SetPrivacyURL(v string) *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetPrivacyURL(v)
	})
}

// UpdatePrivacyURL sets the "privacy_url" field to the value that was provided on create.
func (u *OAuthClientUpsertOne) UpdatePrivacyURL() *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdatePrivacyURL()
	})
}

// ClearPrivacyURL clears the value of the "privacy_url" field.
func (u *OAuthClientUpsertOne) ClearPrivacyURL() *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.ClearPrivacyURL()
	})
}

// SetTermsURL sets the "terms_url" field.
func (u *OAuthClientUpsertOne) SetTermsURL(v string) *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetTermsURL(v)
	})
}

// UpdateTermsURL sets the "terms_url" field to the value that was provided on create.
func (u *OAuthClientUpsertOne) UpdateTermsURL() *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateTermsURL()
	})
}

// ClearTermsURL clears the value of the "terms_url" field.
func (u *OAuthClientUpsertOne) ClearTermsURL() *OAuthClientUpsertOne {
	return u.Update(func(s *OAuthClientUpsert) {
		s.ClearTermsURL()
	})
}

// Exec executes the query.
func (u *OAuthClientUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OAuthClientCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OAuthClientUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OAuthClientUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OAuthClientUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OAuthClientCreateBulk is the builder for creating many OAuthClient entities in bulk.
type OAuthClientCreateBulk struct {
	config
	err      error
	builders []*OAuthClientCreate
	conflict []sql.ConflictOption
}

// Save creates the OAuthClient entities in the database.
func (_c *OAuthClientCreateBulk) Save(ctx context.Context) ([]*OAuthClient, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OAuthClient, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OAuthClientMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OAuthClientCreateBulk) SaveX(ctx context.Context) []*OAuthClient {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthClientCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthClientCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OAuthClient.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OAuthClientUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OAuthClientCreateBulk) OnConflict(opts ...sql.ConflictOption) *OAuthClientUpsertBulk {
	_c.conflict = opts
	return &OAuthClientUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OAuthClient.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OAuthClientCreateBulk) OnConflictColumns(columns ...string) *OAuthClientUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OAuthClientUpsertBulk{
		create: _c,
	}
}

// OAuthClientUpsertBulk is the builder for "upsert"-ing
// a bulk of OAuthClient nodes.
type OAuthClientUpsertBulk struct {
	create *OAuthClientCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OAuthClient.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OAuthClientUpsertBulk) UpdateNewValues() *OAuthClientUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(oauthclient.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OAuthClient.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OAuthClientUpsertBulk) Ignore() *OAuthClientUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OAuthClientUpsertBulk) DoNothing() *OAuthClientUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OAuthClientCreateBulk.OnConflict
// documentation for more info.
func (u *OAuthClientUpsertBulk) Update(set func(*OAuthClientUpsert)) *OAuthClientUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OAuthClientUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OAuthClientUpsertBulk) SetUpdatedAt(v time.Time) *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OAuthClientUpsertBulk) UpdateUpdatedAt() *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetClientID sets the "client_id" field.
func (u *OAuthClientUpsertBulk) SetClientID(v string) *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *OAuthClientUpsertBulk) UpdateClientID() *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateClientID()
	})
}

// SetName sets the "name" field.
func (u *OAuthClientUpsertBulk) SetName(v string) *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *OAuthClientUpsertBulk) UpdateName() *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateName()
	})
}

// SetClientSecretHash sets the "client_secret_hash" field.
func (u *OAuthClientUpsertBulk) SetClientSecretHash(v string) *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetClientSecretHash(v)
	})
}

// UpdateClientSecretHash sets the "client_secret_hash" field to the value that was provided on create.
func (u *OAuthClientUpsertBulk) UpdateClientSecretHash() *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateClientSecretHash()
	})
}

// ClearClientSecretHash clears the value of the "client_secret_hash" field.
func (u *OAuthClientUpsertBulk) ClearClientSecretHash() *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.ClearClientSecretHash()
	})
}

// SetRedirectUris sets the "redirect_uris" field.
func (u *OAuthClientUpsertBulk) SetRedirectUris(v []string) *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetRedirectUris(v)
	})
}

// UpdateRedirectUris sets the "redirect_uris" field to the value that was provided on create.
func (u *OAuthClientUpsertBulk) UpdateRedirectUris() *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateRedirectUris()
	})
}

// SetAllowedScopes sets the "allowed_scopes" field.
func (u *OAuthClientUpsertBulk) SetAllowedScopes(v []string) *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetAllowedScopes(v)
	})
}

// UpdateAllowedScopes sets the "allowed_scopes" field to the value that was provided on create.
func (u *OAuthClientUpsertBulk) UpdateAllowedScopes() *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateAllowedScopes()
	})
}

// SetPkceRequired sets the "pkce_required" field.
func (u *OAuthClientUpsertBulk) SetPkceRequired(v bool) *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetPkceRequired(v)
	})
}

// UpdatePkceRequired sets the "pkce_required" field to the value that was provided on create.
func (u *OAuthClientUpsertBulk) UpdatePkceRequired() *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdatePkceRequired()
	})
}

// SetDefaultGroupID sets the "default_group_id" field.
func (u *OAuthClientUpsertBulk) SetDefaultGroupID(v int64) *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetDefaultGroupID(v)
	})
}

// AddDefaultGroupID adds v to the "default_group_id" field.
func (u *OAuthClientUpsertBulk) AddDefaultGroupID(v int64) *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.AddDefaultGroupID(v)
	})
}

// UpdateDefaultGroupID sets the "default_group_id" field to the value that was provided on create.
func (u *OAuthClientUpsertBulk) UpdateDefaultGroupID() *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateDefaultGroupID()
	})
}

// ClearDefaultGroupID clears the value of the "default_group_id" field.
func (u *OAuthClientUpsertBulk) ClearDefaultGroupID() *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.ClearDefaultGroupID()
	})
}

// SetAccessTokenTTLSeconds sets the "access_token_ttl_seconds" field.
func (u *OAuthClientUpsertBulk) SetAccessTokenTTLSeconds(v int) *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetAccessTokenTTLSeconds(v)
	})
}

// AddAccessTokenTTLSeconds adds v to the "access_token_ttl_seconds" field.
func (u *OAuthClientUpsertBulk) AddAccessTokenTTLSeconds(v int) *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.AddAccessTokenTTLSeconds(v)
	})
}

// UpdateAccessTokenTTLSeconds sets the "access_token_ttl_seconds" field to the value that was provided on create.
func (u *OAuthClientUpsertBulk) UpdateAccessTokenTTLSeconds() *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateAccessTokenTTLSeconds()
	})
}

// SetRefreshTokenTTLSeconds sets the "refresh_token_ttl_seconds" field.
func (u *OAuthClientUpsertBulk) SetRefreshTokenTTLSeconds(v int) *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetRefreshTokenTTLSeconds(v)
	})
}

// AddRefreshTokenTTLSeconds adds v to the "refresh_token_ttl_seconds" field.
func (u *OAuthClientUpsertBulk) AddRefreshTokenTTLSeconds(v int) *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.AddRefreshTokenTTLSeconds(v)
	})
}

// UpdateRefreshTokenTTLSeconds sets the "refresh_token_ttl_seconds" field to the value that was provided on create.
func (u *OAuthClientUpsertBulk) UpdateRefreshTokenTTLSeconds() *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateRefreshTokenTTLSeconds()
	})
}

// SetDisabled sets the "disabled" field.
func (u *OAuthClientUpsertBulk) SetDisabled(v bool) *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetDisabled(v)
	})
}

// UpdateDisabled sets the "disabled" field to the value that was provided on create.
func (u *OAuthClientUpsertBulk) UpdateDisabled() *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateDisabled()
	})
}

// SetClientType sets the "client_type" field.
func (u *OAuthClientUpsertBulk) SetClientType(v string) *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetClientType(v)
	})
}

// UpdateClientType sets the "client_type" field to the value that was provided on create.
func (u *OAuthClientUpsertBulk) UpdateClientType() *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateClientType()
	})
}

// SetAppType sets the "app_type" field.
func (u *OAuthClientUpsertBulk) SetAppType(v string) *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetAppType(v)
	})
}

// UpdateAppType sets the "app_type" field to the value that was provided on create.
func (u *OAuthClientUpsertBulk) UpdateAppType() *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateAppType()
	})
}

// SetTrustedFirstParty sets the "trusted_first_party" field.
func (u *OAuthClientUpsertBulk) SetTrustedFirstParty(v bool) *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetTrustedFirstParty(v)
	})
}

// UpdateTrustedFirstParty sets the "trusted_first_party" field to the value that was provided on create.
func (u *OAuthClientUpsertBulk) UpdateTrustedFirstParty() *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateTrustedFirstParty()
	})
}

// SetDefaultScopes sets the "default_scopes" field.
func (u *OAuthClientUpsertBulk) SetDefaultScopes(v []string) *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetDefaultScopes(v)
	})
}

// UpdateDefaultScopes sets the "default_scopes" field to the value that was provided on create.
func (u *OAuthClientUpsertBulk) UpdateDefaultScopes() *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateDefaultScopes()
	})
}

// SetAllowedGroupIds sets the "allowed_group_ids" field.
func (u *OAuthClientUpsertBulk) SetAllowedGroupIds(v []int64) *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetAllowedGroupIds(v)
	})
}

// UpdateAllowedGroupIds sets the "allowed_group_ids" field to the value that was provided on create.
func (u *OAuthClientUpsertBulk) UpdateAllowedGroupIds() *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateAllowedGroupIds()
	})
}

// ClearAllowedGroupIds clears the value of the "allowed_group_ids" field.
func (u *OAuthClientUpsertBulk) ClearAllowedGroupIds() *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.ClearAllowedGroupIds()
	})
}

// SetAllowedOrigins sets the "allowed_origins" field.
func (u *OAuthClientUpsertBulk) SetAllowedOrigins(v []string) *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetAllowedOrigins(v)
	})
}

// UpdateAllowedOrigins sets the "allowed_origins" field to the value that was provided on create.
func (u *OAuthClientUpsertBulk) UpdateAllowedOrigins() *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateAllowedOrigins()
	})
}

// SetLogoutRedirectUris sets the "logout_redirect_uris" field.
func (u *OAuthClientUpsertBulk) SetLogoutRedirectUris(v []string) *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetLogoutRedirectUris(v)
	})
}

// UpdateLogoutRedirectUris sets the "logout_redirect_uris" field to the value that was provided on create.
func (u *OAuthClientUpsertBulk) UpdateLogoutRedirectUris() *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateLogoutRedirectUris()
	})
}

// SetDeviceFlowEnabled sets the "device_flow_enabled" field.
func (u *OAuthClientUpsertBulk) SetDeviceFlowEnabled(v bool) *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetDeviceFlowEnabled(v)
	})
}

// UpdateDeviceFlowEnabled sets the "device_flow_enabled" field to the value that was provided on create.
func (u *OAuthClientUpsertBulk) UpdateDeviceFlowEnabled() *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateDeviceFlowEnabled()
	})
}

// SetAllowRefreshWithoutOfflineAccess sets the "allow_refresh_without_offline_access" field.
func (u *OAuthClientUpsertBulk) SetAllowRefreshWithoutOfflineAccess(v bool) *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetAllowRefreshWithoutOfflineAccess(v)
	})
}

// UpdateAllowRefreshWithoutOfflineAccess sets the "allow_refresh_without_offline_access" field to the value that was provided on create.
func (u *OAuthClientUpsertBulk) UpdateAllowRefreshWithoutOfflineAccess() *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateAllowRefreshWithoutOfflineAccess()
	})
}

// SetIconURL sets the "icon_url" field.
func (u *OAuthClientUpsertBulk) SetIconURL(v string) *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetIconURL(v)
	})
}

// UpdateIconURL sets the "icon_url" field to the value that was provided on create.
func (u *OAuthClientUpsertBulk) UpdateIconURL() *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateIconURL()
	})
}

// ClearIconURL clears the value of the "icon_url" field.
func (u *OAuthClientUpsertBulk) ClearIconURL() *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.ClearIconURL()
	})
}

// SetHomepageURL sets the "homepage_url" field.
func (u *OAuthClientUpsertBulk) SetHomepageURL(v string) *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetHomepageURL(v)
	})
}

// UpdateHomepageURL sets the "homepage_url" field to the value that was provided on create.
func (u *OAuthClientUpsertBulk) UpdateHomepageURL() *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateHomepageURL()
	})
}

// ClearHomepageURL clears the value of the "homepage_url" field.
func (u *OAuthClientUpsertBulk) ClearHomepageURL() *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.ClearHomepageURL()
	})
}

// SetPrivacyURL sets the "privacy_url" field.
func (u *OAuthClientUpsertBulk) SetPrivacyURL(v string) *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetPrivacyURL(v)
	})
}

// UpdatePrivacyURL sets the "privacy_url" field to the value that was provided on create.
func (u *OAuthClientUpsertBulk) UpdatePrivacyURL() *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdatePrivacyURL()
	})
}

// ClearPrivacyURL clears the value of the "privacy_url" field.
func (u *OAuthClientUpsertBulk) ClearPrivacyURL() *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.ClearPrivacyURL()
	})
}

// SetTermsURL sets the "terms_url" field.
func (u *OAuthClientUpsertBulk) SetTermsURL(v string) *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.SetTermsURL(v)
	})
}

// UpdateTermsURL sets the "terms_url" field to the value that was provided on create.
func (u *OAuthClientUpsertBulk) UpdateTermsURL() *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.UpdateTermsURL()
	})
}

// ClearTermsURL clears the value of the "terms_url" field.
func (u *OAuthClientUpsertBulk) ClearTermsURL() *OAuthClientUpsertBulk {
	return u.Update(func(s *OAuthClientUpsert) {
		s.ClearTermsURL()
	})
}

// Exec executes the query.
func (u *OAuthClientUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OAuthClientCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OAuthClientCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OAuthClientUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
