// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/oauthcode"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// OAuthCodeUpdate is the builder for updating OAuthCode entities.
type OAuthCodeUpdate struct {
	config
	hooks    []Hook
	mutation *OAuthCodeMutation
}

// Where appends a list predicates to the OAuthCodeUpdate builder.
func (_u *OAuthCodeUpdate) Where(ps ...predicate.OAuthCode) *OAuthCodeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OAuthCodeUpdate) SetUpdatedAt(v time.Time) *OAuthCodeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCodeHash sets the "code_hash" field.
func (_u *OAuthCodeUpdate) SetCodeHash(v string) *OAuthCodeUpdate {
	_u.mutation.SetCodeHash(v)
	return _u
}

// SetNillableCodeHash sets the "code_hash" field if the given value is not nil.
func (_u *OAuthCodeUpdate) SetNillableCodeHash(v *string) *OAuthCodeUpdate {
	if v != nil {
		_u.SetCodeHash(*v)
	}
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *OAuthCodeUpdate) SetClientID(v string) *OAuthCodeUpdate {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OAuthCodeUpdate) SetNillableClientID(v *string) *OAuthCodeUpdate {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OAuthCodeUpdate) SetUserID(v int64) *OAuthCodeUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OAuthCodeUpdate) SetNillableUserID(v *int64) *OAuthCodeUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *OAuthCodeUpdate) AddUserID(v int64) *OAuthCodeUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetRedirectURI sets the "redirect_uri" field.
func (_u *OAuthCodeUpdate) SetRedirectURI(v string) *OAuthCodeUpdate {
	_u.mutation.SetRedirectURI(v)
	return _u
}

// SetNillableRedirectURI sets the "redirect_uri" field if the given value is not nil.
func (_u *OAuthCodeUpdate) SetNillableRedirectURI(v *string) *OAuthCodeUpdate {
	if v != nil {
		_u.SetRedirectURI(*v)
	}
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *OAuthCodeUpdate) SetScopes(v []string) *OAuthCodeUpdate {
	_u.mutation.SetScopes(v)
	return _u
}

// AppendScopes appends value to the "scopes" field.
func (_u *OAuthCodeUpdate) AppendScopes(v []string) *OAuthCodeUpdate {
	_u.mutation.AppendScopes(v)
	return _u
}

// SetCodeChallenge sets the "code_challenge" field.
func (_u *OAuthCodeUpdate) SetCodeChallenge(v string) *OAuthCodeUpdate {
	_u.mutation.SetCodeChallenge(v)
	return _u
}

// SetNillableCodeChallenge sets the "code_challenge" field if the given value is not nil.
func (_u *OAuthCodeUpdate) SetNillableCodeChallenge(v *string) *OAuthCodeUpdate {
	if v != nil {
		_u.SetCodeChallenge(*v)
	}
	return _u
}

// SetCodeChallengeMethod sets the "code_challenge_method" field.
func (_u *OAuthCodeUpdate) SetCodeChallengeMethod(v string) *OAuthCodeUpdate {
	_u.mutation.SetCodeChallengeMethod(v)
	return _u
}

// SetNillableCodeChallengeMethod sets the "code_challenge_method" field if the given value is not nil.
func (_u *OAuthCodeUpdate) SetNillableCodeChallengeMethod(v *string) *OAuthCodeUpdate {
	if v != nil {
		_u.SetCodeChallengeMethod(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *OAuthCodeUpdate) SetExpiresAt(v time.Time) *OAuthCodeUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *OAuthCodeUpdate) SetNillableExpiresAt(v *time.Time) *OAuthCodeUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetUsedAt sets the "used_at" field.
func (_u *OAuthCodeUpdate) SetUsedAt(v time.Time) *OAuthCodeUpdate {
	_u.mutation.SetUsedAt(v)
	return _u
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (_u *OAuthCodeUpdate) SetNillableUsedAt(v *time.Time) *OAuthCodeUpdate {
	if v != nil {
		_u.SetUsedAt(*v)
	}
	return _u
}

// ClearUsedAt clears the value of the "used_at" field.
func (_u *OAuthCodeUpdate) ClearUsedAt() *OAuthCodeUpdate {
	_u.mutation.ClearUsedAt()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *OAuthCodeUpdate) SetGroupID(v int64) *OAuthCodeUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *OAuthCodeUpdate) SetNillableGroupID(v *int64) *OAuthCodeUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *OAuthCodeUpdate) AddGroupID(v int64) *OAuthCodeUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *OAuthCodeUpdate) ClearGroupID() *OAuthCodeUpdate {
	_u.mutation.ClearGroupID()
	return _u
}

// SetGrantID sets the "grant_id" field.
func (_u *OAuthCodeUpdate) SetGrantID(v string) *OAuthCodeUpdate {
	_u.mutation.SetGrantID(v)
	return _u
}

// SetNillableGrantID sets the "grant_id" field if the given value is not nil.
func (_u *OAuthCodeUpdate) SetNillableGrantID(v *string) *OAuthCodeUpdate {
	if v != nil {
		_u.SetGrantID(*v)
	}
	return _u
}

// ClearGrantID clears the value of the "grant_id" field.
func (_u *OAuthCodeUpdate) ClearGrantID() *OAuthCodeUpdate {
	_u.mutation.ClearGrantID()
	return _u
}

// SetAllowedGroupsSnapshot sets the "allowed_groups_snapshot" field.
func (_u *OAuthCodeUpdate) SetAllowedGroupsSnapshot(v []int64) *OAuthCodeUpdate {
	_u.mutation.SetAllowedGroupsSnapshot(v)
	return _u
}

// AppendAllowedGroupsSnapshot appends value to the "allowed_groups_snapshot" field.
func (_u *OAuthCodeUpdate) AppendAllowedGroupsSnapshot(v []int64) *OAuthCodeUpdate {
	_u.mutation.AppendAllowedGroupsSnapshot(v)
	return _u
}

// SetDeviceID sets the "device_id" field.
func (_u *OAuthCodeUpdate) SetDeviceID(v string) *OAuthCodeUpdate {
	_u.mutation.SetDeviceID(v)
	return _u
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_u *OAuthCodeUpdate) SetNillableDeviceID(v *string) *OAuthCodeUpdate {
	if v != nil {
		_u.SetDeviceID(*v)
	}
	return _u
}

// ClearDeviceID clears the value of the "device_id" field.
func (_u *OAuthCodeUpdate) ClearDeviceID() *OAuthCodeUpdate {
	_u.mutation.ClearDeviceID()
	return _u
}

// SetDeviceName sets the "device_name" field.
func (_u *OAuthCodeUpdate) SetDeviceName(v string) *OAuthCodeUpdate {
	_u.mutation.SetDeviceName(v)
	return _u
}

// SetNillableDeviceName sets the "device_name" field if the given value is not nil.
func (_u *OAuthCodeUpdate) SetNillableDeviceName(v *string) *OAuthCodeUpdate {
	if v != nil {
		_u.SetDeviceName(*v)
	}
	return _u
}

// ClearDeviceName clears the value of the "device_name" field.
func (_u *OAuthCodeUpdate) ClearDeviceName() *OAuthCodeUpdate {
	_u.mutation.ClearDeviceName()
	return _u
}

// Mutation returns the OAuthCodeMutation object of the builder.
func (_u *OAuthCodeUpdate) Mutation() *OAuthCodeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OAuthCodeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthCodeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OAuthCodeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthCodeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OAuthCodeUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := oauthcode.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthCodeUpdate) check() error {
	if v, ok := _u.mutation.CodeHash(); ok {
		if err := oauthcode.CodeHashValidator(v); err != nil {
			return &ValidationError{Name: "code_hash", err: fmt.Errorf(`ent: validator failed for field "OAuthCode.code_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientID(); ok {
		if err := oauthcode.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "OAuthCode.client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RedirectURI(); ok {
		if err := oauthcode.RedirectURIValidator(v); err != nil {
			return &ValidationError{Name: "redirect_uri", err: fmt.Errorf(`ent: validator failed for field "OAuthCode.redirect_uri": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CodeChallenge(); ok {
		if err := oauthcode.CodeChallengeValidator(v); err != nil {
			return &ValidationError{Name: "code_challenge", err: fmt.Errorf(`ent: validator failed for field "OAuthCode.code_challenge": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CodeChallengeMethod(); ok {
		if err := oauthcode.CodeChallengeMethodValidator(v); err != nil {
			return &ValidationError{Name: "code_challenge_method", err: fmt.Errorf(`ent: validator failed for field "OAuthCode.code_challenge_method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GrantID(); ok {
		if err := oauthcode.GrantIDValidator(v); err != nil {
			return &ValidationError{Name: "grant_id", err: fmt.Errorf(`ent: validator failed for field "OAuthCode.grant_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeviceID(); ok {
		if err := oauthcode.DeviceIDValidator(v); err != nil {
			return &ValidationError{Name: "device_id", err: fmt.Errorf(`ent: validator failed for field "OAuthCode.device_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeviceName(); ok {
		if err := oauthcode.DeviceNameValidator(v); err != nil {
			return &ValidationError{Name: "device_name", err: fmt.Errorf(`ent: validator failed for field "OAuthCode.device_name": %w`, err)}
		}
	}
	return nil
}

func (_u *OAuthCodeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthcode.Table, oauthcode.Columns, sqlgraph.NewFieldSpec(oauthcode.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthcode.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CodeHash(); ok {
		_spec.SetField(oauthcode.FieldCodeHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(oauthcode.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(oauthcode.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(oauthcode.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RedirectURI(); ok {
		_spec.SetField(oauthcode.FieldRedirectURI, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(oauthcode.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthcode.FieldScopes, value)
		})
	}
	if value, ok := _u.mutation.CodeChallenge(); ok {
		_spec.SetField(oauthcode.FieldCodeChallenge, field.TypeString, value)
	}
	if value, ok := _u.mutation.CodeChallengeMethod(); ok {
		_spec.SetField(oauthcode.FieldCodeChallengeMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthcode.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UsedAt(); ok {
		_spec.SetField(oauthcode.FieldUsedAt, field.TypeTime, value)
	}
	if _u.mutation.UsedAtCleared() {
		_spec.ClearField(oauthcode.FieldUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(oauthcode.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(oauthcode.FieldGroupID, field.TypeInt64, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(oauthcode.FieldGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.GrantID(); ok {
		_spec.SetField(oauthcode.FieldGrantID, field.TypeString, value)
	}
	if _u.mutation.GrantIDCleared() {
		_spec.ClearField(oauthcode.FieldGrantID, field.TypeString)
	}
	if value, ok := _u.mutation.AllowedGroupsSnapshot(); ok {
		_spec.SetField(oauthcode.FieldAllowedGroupsSnapshot, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAllowedGroupsSnapshot(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthcode.FieldAllowedGroupsSnapshot, value)
		})
	}
	if value, ok := _u.mutation.DeviceID(); ok {
		_spec.SetField(oauthcode.FieldDeviceID, field.TypeString, value)
	}
	if _u.mutation.DeviceIDCleared() {
		_spec.ClearField(oauthcode.FieldDeviceID, field.TypeString)
	}
	if value, ok := _u.mutation.DeviceName(); ok {
		_spec.SetField(oauthcode.FieldDeviceName, field.TypeString, value)
	}
	if _u.mutation.DeviceNameCleared() {
		_spec.ClearField(oauthcode.FieldDeviceName, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthcode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OAuthCodeUpdateOne is the builder for updating a single OAuthCode entity.
type OAuthCodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OAuthCodeMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OAuthCodeUpdateOne) SetUpdatedAt(v time.Time) *OAuthCodeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCodeHash sets the "code_hash" field.
func (_u *OAuthCodeUpdateOne) SetCodeHash(v string) *OAuthCodeUpdateOne {
	_u.mutation.SetCodeHash(v)
	return _u
}

// SetNillableCodeHash sets the "code_hash" field if the given value is not nil.
func (_u *OAuthCodeUpdateOne) SetNillableCodeHash(v *string) *OAuthCodeUpdateOne {
	if v != nil {
		_u.SetCodeHash(*v)
	}
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *OAuthCodeUpdateOne) SetClientID(v string) *OAuthCodeUpdateOne {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OAuthCodeUpdateOne) SetNillableClientID(v *string) *OAuthCodeUpdateOne {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OAuthCodeUpdateOne) SetUserID(v int64) *OAuthCodeUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OAuthCodeUpdateOne) SetNillableUserID(v *int64) *OAuthCodeUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *OAuthCodeUpdateOne) AddUserID(v int64) *OAuthCodeUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetRedirectURI sets the "redirect_uri" field.
func (_u *OAuthCodeUpdateOne) SetRedirectURI(v string) *OAuthCodeUpdateOne {
	_u.mutation.SetRedirectURI(v)
	return _u
}

// SetNillableRedirectURI sets the "redirect_uri" field if the given value is not nil.
func (_u *OAuthCodeUpdateOne) SetNillableRedirectURI(v *string) *OAuthCodeUpdateOne {
	if v != nil {
		_u.SetRedirectURI(*v)
	}
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *OAuthCodeUpdateOne) SetScopes(v []string) *OAuthCodeUpdateOne {
	_u.mutation.SetScopes(v)
	return _u
}

// AppendScopes appends value to the "scopes" field.
func (_u *OAuthCodeUpdateOne) AppendScopes(v []string) *OAuthCodeUpdateOne {
	_u.mutation.AppendScopes(v)
	return _u
}

// SetCodeChallenge sets the "code_challenge" field.
func (_u *OAuthCodeUpdateOne) SetCodeChallenge(v string) *OAuthCodeUpdateOne {
	_u.mutation.SetCodeChallenge(v)
	return _u
}

// SetNillableCodeChallenge sets the "code_challenge" field if the given value is not nil.
func (_u *OAuthCodeUpdateOne) SetNillableCodeChallenge(v *string) *OAuthCodeUpdateOne {
	if v != nil {
		_u.SetCodeChallenge(*v)
	}
	return _u
}

// SetCodeChallengeMethod sets the "code_challenge_method" field.
func (_u *OAuthCodeUpdateOne) SetCodeChallengeMethod(v string) *OAuthCodeUpdateOne {
	_u.mutation.SetCodeChallengeMethod(v)
	return _u
}

// SetNillableCodeChallengeMethod sets the "code_challenge_method" field if the given value is not nil.
func (_u *OAuthCodeUpdateOne) SetNillableCodeChallengeMethod(v *string) *OAuthCodeUpdateOne {
	if v != nil {
		_u.SetCodeChallengeMethod(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *OAuthCodeUpdateOne) SetExpiresAt(v time.Time) *OAuthCodeUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *OAuthCodeUpdateOne) SetNillableExpiresAt(v *time.Time) *OAuthCodeUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetUsedAt sets the "used_at" field.
func (_u *OAuthCodeUpdateOne) SetUsedAt(v time.Time) *OAuthCodeUpdateOne {
	_u.mutation.SetUsedAt(v)
	return _u
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (_u *OAuthCodeUpdateOne) SetNillableUsedAt(v *time.Time) *OAuthCodeUpdateOne {
	if v != nil {
		_u.SetUsedAt(*v)
	}
	return _u
}

// ClearUsedAt clears the value of the "used_at" field.
func (_u *OAuthCodeUpdateOne) ClearUsedAt() *OAuthCodeUpdateOne {
	_u.mutation.ClearUsedAt()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *OAuthCodeUpdateOne) SetGroupID(v int64) *OAuthCodeUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *OAuthCodeUpdateOne) SetNillableGroupID(v *int64) *OAuthCodeUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *OAuthCodeUpdateOne) AddGroupID(v int64) *OAuthCodeUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *OAuthCodeUpdateOne) ClearGroupID() *OAuthCodeUpdateOne {
	_u.mutation.ClearGroupID()
	return _u
}

// SetGrantID sets the "grant_id" field.
func (_u *OAuthCodeUpdateOne) SetGrantID(v string) *OAuthCodeUpdateOne {
	_u.mutation.SetGrantID(v)
	return _u
}

// SetNillableGrantID sets the "grant_id" field if the given value is not nil.
func (_u *OAuthCodeUpdateOne) SetNillableGrantID(v *string) *OAuthCodeUpdateOne {
	if v != nil {
		_u.SetGrantID(*v)
	}
	return _u
}

// ClearGrantID clears the value of the "grant_id" field.
func (_u *OAuthCodeUpdateOne) ClearGrantID() *OAuthCodeUpdateOne {
	_u.mutation.ClearGrantID()
	return _u
}

// SetAllowedGroupsSnapshot sets the "allowed_groups_snapshot" field.
func (_u *OAuthCodeUpdateOne) SetAllowedGroupsSnapshot(v []int64) *OAuthCodeUpdateOne {
	_u.mutation.SetAllowedGroupsSnapshot(v)
	return _u
}

// AppendAllowedGroupsSnapshot appends value to the "allowed_groups_snapshot" field.
func (_u *OAuthCodeUpdateOne) AppendAllowedGroupsSnapshot(v []int64) *OAuthCodeUpdateOne {
	_u.mutation.AppendAllowedGroupsSnapshot(v)
	return _u
}

// SetDeviceID sets the "device_id" field.
func (_u *OAuthCodeUpdateOne) SetDeviceID(v string) *OAuthCodeUpdateOne {
	_u.mutation.SetDeviceID(v)
	return _u
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_u *OAuthCodeUpdateOne) SetNillableDeviceID(v *string) *OAuthCodeUpdateOne {
	if v != nil {
		_u.SetDeviceID(*v)
	}
	return _u
}

// ClearDeviceID clears the value of the "device_id" field.
func (_u *OAuthCodeUpdateOne) ClearDeviceID() *OAuthCodeUpdateOne {
	_u.mutation.ClearDeviceID()
	return _u
}

// SetDeviceName sets the "device_name" field.
func (_u *OAuthCodeUpdateOne) SetDeviceName(v string) *OAuthCodeUpdateOne {
	_u.mutation.SetDeviceName(v)
	return _u
}

// SetNillableDeviceName sets the "device_name" field if the given value is not nil.
func (_u *OAuthCodeUpdateOne) SetNillableDeviceName(v *string) *OAuthCodeUpdateOne {
	if v != nil {
		_u.SetDeviceName(*v)
	}
	return _u
}

// ClearDeviceName clears the value of the "device_name" field.
func (_u *OAuthCodeUpdateOne) ClearDeviceName() *OAuthCodeUpdateOne {
	_u.mutation.ClearDeviceName()
	return _u
}

// Mutation returns the OAuthCodeMutation object of the builder.
func (_u *OAuthCodeUpdateOne) Mutation() *OAuthCodeMutation {
	return _u.mutation
}

// Where appends a list predicates to the OAuthCodeUpdate builder.
func (_u *OAuthCodeUpdateOne) Where(ps ...predicate.OAuthCode) *OAuthCodeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OAuthCodeUpdateOne) Select(field string, fields ...string) *OAuthCodeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OAuthCode entity.
func (_u *OAuthCodeUpdateOne) Save(ctx context.Context) (*OAuthCode, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthCodeUpdateOne) SaveX(ctx context.Context) *OAuthCode {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OAuthCodeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthCodeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OAuthCodeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := oauthcode.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthCodeUpdateOne) check() error {
	if v, ok := _u.mutation.CodeHash(); ok {
		if err := oauthcode.CodeHashValidator(v); err != nil {
			return &ValidationError{Name: "code_hash", err: fmt.Errorf(`ent: validator failed for field "OAuthCode.code_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientID(); ok {
		if err := oauthcode.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "OAuthCode.client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RedirectURI(); ok {
		if err := oauthcode.RedirectURIValidator(v); err != nil {
			return &ValidationError{Name: "redirect_uri", err: fmt.Errorf(`ent: validator failed for field "OAuthCode.redirect_uri": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CodeChallenge(); ok {
		if err := oauthcode.CodeChallengeValidator(v); err != nil {
			return &ValidationError{Name: "code_challenge", err: fmt.Errorf(`ent: validator failed for field "OAuthCode.code_challenge": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CodeChallengeMethod(); ok {
		if err := oauthcode.CodeChallengeMethodValidator(v); err != nil {
			return &ValidationError{Name: "code_challenge_method", err: fmt.Errorf(`ent: validator failed for field "OAuthCode.code_challenge_method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GrantID(); ok {
		if err := oauthcode.GrantIDValidator(v); err != nil {
			return &ValidationError{Name: "grant_id", err: fmt.Errorf(`ent: validator failed for field "OAuthCode.grant_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeviceID(); ok {
		if err := oauthcode.DeviceIDValidator(v); err != nil {
			return &ValidationError{Name: "device_id", err: fmt.Errorf(`ent: validator failed for field "OAuthCode.device_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeviceName(); ok {
		if err := oauthcode.DeviceNameValidator(v); err != nil {
			return &ValidationError{Name: "device_name", err: fmt.Errorf(`ent: validator failed for field "OAuthCode.device_name": %w`, err)}
		}
	}
	return nil
}

func (_u *OAuthCodeUpdateOne) sqlSave(ctx context.Context) (_node *OAuthCode, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthcode.Table, oauthcode.Columns, sqlgraph.NewFieldSpec(oauthcode.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OAuthCode.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauthcode.FieldID)
		for _, f := range fields {
			if !oauthcode.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != oauthcode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthcode.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CodeHash(); ok {
		_spec.SetField(oauthcode.FieldCodeHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(oauthcode.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(oauthcode.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(oauthcode.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RedirectURI(); ok {
		_spec.SetField(oauthcode.FieldRedirectURI, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(oauthcode.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthcode.FieldScopes, value)
		})
	}
	if value, ok := _u.mutation.CodeChallenge(); ok {
		_spec.SetField(oauthcode.FieldCodeChallenge, field.TypeString, value)
	}
	if value, ok := _u.mutation.CodeChallengeMethod(); ok {
		_spec.SetField(oauthcode.FieldCodeChallengeMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthcode.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UsedAt(); ok {
		_spec.SetField(oauthcode.FieldUsedAt, field.TypeTime, value)
	}
	if _u.mutation.UsedAtCleared() {
		_spec.ClearField(oauthcode.FieldUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(oauthcode.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(oauthcode.FieldGroupID, field.TypeInt64, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(oauthcode.FieldGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.GrantID(); ok {
		_spec.SetField(oauthcode.FieldGrantID, field.TypeString, value)
	}
	if _u.mutation.GrantIDCleared() {
		_spec.ClearField(oauthcode.FieldGrantID, field.TypeString)
	}
	if value, ok := _u.mutation.AllowedGroupsSnapshot(); ok {
		_spec.SetField(oauthcode.FieldAllowedGroupsSnapshot, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAllowedGroupsSnapshot(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthcode.FieldAllowedGroupsSnapshot, value)
		})
	}
	if value, ok := _u.mutation.DeviceID(); ok {
		_spec.SetField(oauthcode.FieldDeviceID, field.TypeString, value)
	}
	if _u.mutation.DeviceIDCleared() {
		_spec.ClearField(oauthcode.FieldDeviceID, field.TypeString)
	}
	if value, ok := _u.mutation.DeviceName(); ok {
		_spec.SetField(oauthcode.FieldDeviceName, field.TypeString, value)
	}
	if _u.mutation.DeviceNameCleared() {
		_spec.ClearField(oauthcode.FieldDeviceName, field.TypeString)
	}
	_node = &OAuthCode{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthcode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
