// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/oauthcode"
)

// OAuthCodeCreate is the builder for creating a OAuthCode entity.
type OAuthCodeCreate struct {
	config
	mutation *OAuthCodeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *OAuthCodeCreate) SetCreatedAt(v time.Time) *OAuthCodeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OAuthCodeCreate) SetNillableCreatedAt(v *time.Time) *OAuthCodeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OAuthCodeCreate) SetUpdatedAt(v time.Time) *OAuthCodeCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OAuthCodeCreate) SetNillableUpdatedAt(v *time.Time) *OAuthCodeCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCodeHash sets the "code_hash" field.
func (_c *OAuthCodeCreate) SetCodeHash(v string) *OAuthCodeCreate {
	_c.mutation.SetCodeHash(v)
	return _c
}

// SetClientID sets the "client_id" field.
func (_c *OAuthCodeCreate) SetClientID(v string) *OAuthCodeCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *OAuthCodeCreate) SetUserID(v int64) *OAuthCodeCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetRedirectURI sets the "redirect_uri" field.
func (_c *OAuthCodeCreate) SetRedirectURI(v string) *OAuthCodeCreate {
	_c.mutation.SetRedirectURI(v)
	return _c
}

// SetScopes sets the "scopes" field.
func (_c *OAuthCodeCreate) SetScopes(v []string) *OAuthCodeCreate {
	_c.mutation.SetScopes(v)
	return _c
}

// SetCodeChallenge sets the "code_challenge" field.
func (_c *OAuthCodeCreate) SetCodeChallenge(v string) *OAuthCodeCreate {
	_c.mutation.SetCodeChallenge(v)
	return _c
}

// SetCodeChallengeMethod sets the "code_challenge_method" field.
func (_c *OAuthCodeCreate) SetCodeChallengeMethod(v string) *OAuthCodeCreate {
	_c.mutation.SetCodeChallengeMethod(v)
	return _c
}

// SetNillableCodeChallengeMethod sets the "code_challenge_method" field if the given value is not nil.
func (_c *OAuthCodeCreate) SetNillableCodeChallengeMethod(v *string) *OAuthCodeCreate {
	if v != nil {
		_c.SetCodeChallengeMethod(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *OAuthCodeCreate) SetExpiresAt(v time.Time) *OAuthCodeCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetUsedAt sets the "used_at" field.
func (_c *OAuthCodeCreate) SetUsedAt(v time.Time) *OAuthCodeCreate {
	_c.mutation.SetUsedAt(v)
	return _c
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (_c *OAuthCodeCreate) SetNillableUsedAt(v *time.Time) *OAuthCodeCreate {
	if v != nil {
		_c.SetUsedAt(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *OAuthCodeCreate) SetGroupID(v int64) *OAuthCodeCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_c *OAuthCodeCreate) SetNillableGroupID(v *int64) *OAuthCodeCreate {
	if v != nil {
		_c.SetGroupID(*v)
	}
	return _c
}

// SetGrantID sets the "grant_id" field.
func (_c *OAuthCodeCreate) SetGrantID(v string) *OAuthCodeCreate {
	_c.mutation.SetGrantID(v)
	return _c
}

// SetNillableGrantID sets the "grant_id" field if the given value is not nil.
func (_c *OAuthCodeCreate) SetNillableGrantID(v *string) *OAuthCodeCreate {
	if v != nil {
		_c.SetGrantID(*v)
	}
	return _c
}

// SetAllowedGroupsSnapshot sets the "allowed_groups_snapshot" field.
func (_c *OAuthCodeCreate) SetAllowedGroupsSnapshot(v []int64) *OAuthCodeCreate {
	_c.mutation.SetAllowedGroupsSnapshot(v)
	return _c
}

// SetDeviceID sets the "device_id" field.
func (_c *OAuthCodeCreate) SetDeviceID(v string) *OAuthCodeCreate {
	_c.mutation.SetDeviceID(v)
	return _c
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_c *OAuthCodeCreate) SetNillableDeviceID(v *string) *OAuthCodeCreate {
	if v != nil {
		_c.SetDeviceID(*v)
	}
	return _c
}

// SetDeviceName sets the "device_name" field.
func (_c *OAuthCodeCreate) SetDeviceName(v string) *OAuthCodeCreate {
	_c.mutation.SetDeviceName(v)
	return _c
}

// SetNillableDeviceName sets the "device_name" field if the given value is not nil.
func (_c *OAuthCodeCreate) SetNillableDeviceName(v *string) *OAuthCodeCreate {
	if v != nil {
		_c.SetDeviceName(*v)
	}
	return _c
}

// Mutation returns the OAuthCodeMutation object of the builder.
func (_c *OAuthCodeCreate) Mutation() *OAuthCodeMutation {
	return _c.mutation
}

// Save creates the OAuthCode in the database.
func (_c *OAuthCodeCreate) Save(ctx context.Context) (*OAuthCode, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OAuthCodeCreate) SaveX(ctx context.Context) *OAuthCode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthCodeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthCodeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OAuthCodeCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := oauthcode.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := oauthcode.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.CodeChallengeMethod(); !ok {
		v := oauthcode.DefaultCodeChallengeMethod
		_c.mutation.SetCodeChallengeMethod(v)
	}
	if _, ok := _c.mutation.AllowedGroupsSnapshot(); !ok {
		v := oauthcode.DefaultAllowedGroupsSnapshot
		_c.mutation.SetAllowedGroupsSnapshot(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OAuthCodeCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OAuthCode.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OAuthCode.updated_at"`)}
	}
	if _, ok := _c.mutation.CodeHash(); !ok {
		return &ValidationError{Name: "code_hash", err: errors.New(`ent: missing required field "OAuthCode.code_hash"`)}
	}
	if v, ok := _c.mutation.CodeHash(); ok {
		if err := oauthcode.CodeHashValidator(v); err != nil {
			return &ValidationError{Name: "code_hash", err: fmt.Errorf(`ent: validator failed for field "OAuthCode.code_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`ent: missing required field "OAuthCode.client_id"`)}
	}
	if v, ok := _c.mutation.ClientID(); ok {
		if err := oauthcode.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "OAuthCode.client_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "OAuthCode.user_id"`)}
	}
	if _, ok := _c.mutation.RedirectURI(); !ok {
		return &ValidationError{Name: "redirect_uri", err: errors.New(`ent: missing required field "OAuthCode.redirect_uri"`)}
	}
	if v, ok := _c.mutation.RedirectURI(); ok {
		if err := oauthcode.RedirectURIValidator(v); err != nil {
			return &ValidationError{Name: "redirect_uri", err: fmt.Errorf(`ent: validator failed for field "OAuthCode.redirect_uri": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Scopes(); !ok {
		return &ValidationError{Name: "scopes", err: errors.New(`ent: missing required field "OAuthCode.scopes"`)}
	}
	if _, ok := _c.mutation.CodeChallenge(); !ok {
		return &ValidationError{Name: "code_challenge", err: errors.New(`ent: missing required field "OAuthCode.code_challenge"`)}
	}
	if v, ok := _c.mutation.CodeChallenge(); ok {
		if err := oauthcode.CodeChallengeValidator(v); err != nil {
			return &ValidationError{Name: "code_challenge", err: fmt.Errorf(`ent: validator failed for field "OAuthCode.code_challenge": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CodeChallengeMethod(); !ok {
		return &ValidationError{Name: "code_challenge_method", err: errors.New(`ent: missing required field "OAuthCode.code_challenge_method"`)}
	}
	if v, ok := _c.mutation.CodeChallengeMethod(); ok {
		if err := oauthcode.CodeChallengeMethodValidator(v); err != nil {
			return &ValidationError{Name: "code_challenge_method", err: fmt.Errorf(`ent: validator failed for field "OAuthCode.code_challenge_method": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "OAuthCode.expires_at"`)}
	}
	if v, ok := _c.mutation.GrantID(); ok {
		if err := oauthcode.GrantIDValidator(v); err != nil {
			return &ValidationError{Name: "grant_id", err: fmt.Errorf(`ent: validator failed for field "OAuthCode.grant_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AllowedGroupsSnapshot(); !ok {
		return &ValidationError{Name: "allowed_groups_snapshot", err: errors.New(`ent: missing required field "OAuthCode.allowed_groups_snapshot"`)}
	}
	if v, ok := _c.mutation.DeviceID(); ok {
		if err := oauthcode.DeviceIDValidator(v); err != nil {
			return &ValidationError{Name: "device_id", err: fmt.Errorf(`ent: validator failed for field "OAuthCode.device_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.DeviceName(); ok {
		if err := oauthcode.DeviceNameValidator(v); err != nil {
			return &ValidationError{Name: "device_name", err: fmt.Errorf(`ent: validator failed for field "OAuthCode.device_name": %w`, err)}
		}
	}
	return nil
}

func (_c *OAuthCodeCreate) sqlSave(ctx context.Context) (*OAuthCode, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OAuthCodeCreate) createSpec() (*OAuthCode, *sqlgraph.CreateSpec) {
	var (
		_node = &OAuthCode{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(oauthcode.Table, sqlgraph.NewFieldSpec(oauthcode.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(oauthcode.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthcode.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.CodeHash(); ok {
		_spec.SetField(oauthcode.FieldCodeHash, field.TypeString, value)
		_node.CodeHash = value
	}
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(oauthcode.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(oauthcode.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.RedirectURI(); ok {
		_spec.SetField(oauthcode.FieldRedirectURI, field.TypeString, value)
		_node.RedirectURI = value
	}
	if value, ok := _c.mutation.Scopes(); ok {
		_spec.SetField(oauthcode.FieldScopes, field.TypeJSON, value)
		_node.Scopes = value
	}
	if value, ok := _c.mutation.CodeChallenge(); ok {
		_spec.SetField(oauthcode.FieldCodeChallenge, field.TypeString, value)
		_node.CodeChallenge = value
	}
	if value, ok := _c.mutation.CodeChallengeMethod(); ok {
		_spec.SetField(oauthcode.FieldCodeChallengeMethod, field.TypeString, value)
		_node.CodeChallengeMethod = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthcode.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.UsedAt(); ok {
		_spec.SetField(oauthcode.FieldUsedAt, field.TypeTime, value)
		_node.UsedAt = &value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(oauthcode.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = &value
	}
	if value, ok := _c.mutation.GrantID(); ok {
		_spec.SetField(oauthcode.FieldGrantID, field.TypeString, value)
		_node.GrantID = &value
	}
	if value, ok := _c.mutation.AllowedGroupsSnapshot(); ok {
		_spec.SetField(oauthcode.FieldAllowedGroupsSnapshot, field.TypeJSON, value)
		_node.AllowedGroupsSnapshot = value
	}
	if value, ok := _c.mutation.DeviceID(); ok {
		_spec.SetField(oauthcode.FieldDeviceID, field.TypeString, value)
		_node.DeviceID = &value
	}
	if value, ok := _c.mutation.DeviceName(); ok {
		_spec.SetField(oauthcode.FieldDeviceName, field.TypeString, value)
		_node.DeviceName = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OAuthCode.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OAuthCodeUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OAuthCodeCreate) OnConflict(opts ...sql.ConflictOption) *OAuthCodeUpsertOne {
	_c.conflict = opts
	return &OAuthCodeUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OAuthCode.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OAuthCodeCreate) OnConflictColumns(columns ...string) *OAuthCodeUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OAuthCodeUpsertOne{
		create: _c,
	}
}

type (
	// OAuthCodeUpsertOne is the builder for "upsert"-ing
	//  one OAuthCode node.
	OAuthCodeUpsertOne struct {
		create *OAuthCodeCreate
	}

	// OAuthCodeUpsert is the "OnConflict" setter.
	OAuthCodeUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *OAuthCodeUpsert) SetUpdatedAt(v time.Time) *OAuthCodeUpsert {
	u.Set(oauthcode.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OAuthCodeUpsert) UpdateUpdatedAt() *OAuthCodeUpsert {
	u.SetExcluded(oauthcode.FieldUpdatedAt)
	return u
}

// SetCodeHash sets the "code_hash" field.
func (u *OAuthCodeUpsert) SetCodeHash(v string) *OAuthCodeUpsert {
	u.Set(oauthcode.FieldCodeHash, v)
	return u
}

// UpdateCodeHash sets the "code_hash" field to the value that was provided on create.
func (u *OAuthCodeUpsert) UpdateCodeHash() *OAuthCodeUpsert {
	u.SetExcluded(oauthcode.FieldCodeHash)
	return u
}

// SetClientID sets the "client_id" field.
func (u *OAuthCodeUpsert) SetClientID(v string) *OAuthCodeUpsert {
	u.Set(oauthcode.FieldClientID, v)
	return u
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *OAuthCodeUpsert) UpdateClientID() *OAuthCodeUpsert {
	u.SetExcluded(oauthcode.FieldClientID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *OAuthCodeUpsert) SetUserID(v int64) *OAuthCodeUpsert {
	u.Set(oauthcode.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OAuthCodeUpsert) UpdateUserID() *OAuthCodeUpsert {
	u.SetExcluded(oauthcode.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *OAuthCodeUpsert) AddUserID(v int64) *OAuthCodeUpsert {
	u.Add(oauthcode.FieldUserID, v)
	return u
}

// SetRedirectURI sets the "redirect_uri" field.
func (u *OAuthCodeUpsert) SetRedirectURI(v string) *OAuthCodeUpsert {
	u.Set(oauthcode.FieldRedirectURI, v)
	return u
}

// UpdateRedirectURI sets the "redirect_uri" field to the value that was provided on create.
func (u *OAuthCodeUpsert) UpdateRedirectURI() *OAuthCodeUpsert {
	u.SetExcluded(oauthcode.FieldRedirectURI)
	return u
}

// SetScopes sets the "scopes" field.
func (u *OAuthCodeUpsert) SetScopes(v []string) *OAuthCodeUpsert {
	u.Set(oauthcode.FieldScopes, v)
	return u
}

// UpdateScopes sets the "scopes" field to the value that was provided on create.
func (u *OAuthCodeUpsert) UpdateScopes() *OAuthCodeUpsert {
	u.SetExcluded(oauthcode.FieldScopes)
	return u
}

// SetCodeChallenge sets the "code_challenge" field.
func (u *OAuthCodeUpsert) SetCodeChallenge(v string) *OAuthCodeUpsert {
	u.Set(oauthcode.FieldCodeChallenge, v)
	return u
}

// UpdateCodeChallenge sets the "code_challenge" field to the value that was provided on create.
func (u *OAuthCodeUpsert) UpdateCodeChallenge() *OAuthCodeUpsert {
	u.SetExcluded(oauthcode.FieldCodeChallenge)
	return u
}

// SetCodeChallengeMethod sets the "code_challenge_method" field.
func (u *OAuthCodeUpsert) SetCodeChallengeMethod(v string) *OAuthCodeUpsert {
	u.Set(oauthcode.FieldCodeChallengeMethod, v)
	return u
}

// UpdateCodeChallengeMethod sets the "code_challenge_method" field to the value that was provided on create.
func (u *OAuthCodeUpsert) UpdateCodeChallengeMethod() *OAuthCodeUpsert {
	u.SetExcluded(oauthcode.FieldCodeChallengeMethod)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *OAuthCodeUpsert) SetExpiresAt(v time.Time) *OAuthCodeUpsert {
	u.Set(oauthcode.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *OAuthCodeUpsert) UpdateExpiresAt() *OAuthCodeUpsert {
	u.SetExcluded(oauthcode.FieldExpiresAt)
	return u
}

// SetUsedAt sets the "used_at" field.
func (u *OAuthCodeUpsert) SetUsedAt(v time.Time) *OAuthCodeUpsert {
	u.Set(oauthcode.FieldUsedAt, v)
	return u
}

// UpdateUsedAt sets the "used_at" field to the value that was provided on create.
func (u *OAuthCodeUpsert) UpdateUsedAt() *OAuthCodeUpsert {
	u.SetExcluded(oauthcode.FieldUsedAt)
	return u
}

// ClearUsedAt clears the value of the "used_at" field.
func (u *OAuthCodeUpsert) ClearUsedAt() *OAuthCodeUpsert {
	u.SetNull(oauthcode.FieldUsedAt)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *OAuthCodeUpsert) SetGroupID(v int64) *OAuthCodeUpsert {
	u.Set(oauthcode.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *OAuthCodeUpsert) UpdateGroupID() *OAuthCodeUpsert {
	u.SetExcluded(oauthcode.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *OAuthCodeUpsert) AddGroupID(v int64) *OAuthCodeUpsert {
	u.Add(oauthcode.FieldGroupID, v)
	return u
}

// ClearGroupID clears the value of the "group_id" field.
func (u *OAuthCodeUpsert) ClearGroupID() *OAuthCodeUpsert {
	u.SetNull(oauthcode.FieldGroupID)
	return u
}

// SetGrantID sets the "grant_id" field.
func (u *OAuthCodeUpsert) SetGrantID(v string) *OAuthCodeUpsert {
	u.Set(oauthcode.FieldGrantID, v)
	return u
}

// UpdateGrantID sets the "grant_id" field to the value that was provided on create.
func (u *OAuthCodeUpsert) UpdateGrantID() *OAuthCodeUpsert {
	u.SetExcluded(oauthcode.FieldGrantID)
	return u
}

// ClearGrantID clears the value of the "grant_id" field.
func (u *OAuthCodeUpsert) ClearGrantID() *OAuthCodeUpsert {
	u.SetNull(oauthcode.FieldGrantID)
	return u
}

// SetAllowedGroupsSnapshot sets the "allowed_groups_snapshot" field.
func (u *OAuthCodeUpsert) SetAllowedGroupsSnapshot(v []int64) *OAuthCodeUpsert {
	u.Set(oauthcode.FieldAllowedGroupsSnapshot, v)
	return u
}

// UpdateAllowedGroupsSnapshot sets the "allowed_groups_snapshot" field to the value that was provided on create.
func (u *OAuthCodeUpsert) UpdateAllowedGroupsSnapshot() *OAuthCodeUpsert {
	u.SetExcluded(oauthcode.FieldAllowedGroupsSnapshot)
	return u
}

// SetDeviceID sets the "device_id" field.
func (u *OAuthCodeUpsert) SetDeviceID(v string) *OAuthCodeUpsert {
	u.Set(oauthcode.FieldDeviceID, v)
	return u
}

// UpdateDeviceID sets the "device_id" field to the value that was provided on create.
func (u *OAuthCodeUpsert) UpdateDeviceID() *OAuthCodeUpsert {
	u.SetExcluded(oauthcode.FieldDeviceID)
	return u
}

// ClearDeviceID clears the value of the "device_id" field.
func (u *OAuthCodeUpsert) ClearDeviceID() *OAuthCodeUpsert {
	u.SetNull(oauthcode.FieldDeviceID)
	return u
}

// SetDeviceName sets the "device_name" field.
func (u *OAuthCodeUpsert) SetDeviceName(v string) *OAuthCodeUpsert {
	u.Set(oauthcode.FieldDeviceName, v)
	return u
}

// UpdateDeviceName sets the "device_name" field to the value that was provided on create.
func (u *OAuthCodeUpsert) UpdateDeviceName() *OAuthCodeUpsert {
	u.SetExcluded(oauthcode.FieldDeviceName)
	return u
}

// ClearDeviceName clears the value of the "device_name" field.
func (u *OAuthCodeUpsert) ClearDeviceName() *OAuthCodeUpsert {
	u.SetNull(oauthcode.FieldDeviceName)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.OAuthCode.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OAuthCodeUpsertOne) UpdateNewValues() *OAuthCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(oauthcode.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OAuthCode.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OAuthCodeUpsertOne) Ignore() *OAuthCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OAuthCodeUpsertOne) DoNothing() *OAuthCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OAuthCodeCreate.OnConflict
// documentation for more info.
func (u *OAuthCodeUpsertOne) Update(set func(*OAuthCodeUpsert)) *OAuthCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OAuthCodeUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OAuthCodeUpsertOne) SetUpdatedAt(v time.Time) *OAuthCodeUpsertOne {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OAuthCodeUpsertOne) UpdateUpdatedAt() *OAuthCodeUpsertOne {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetCodeHash sets the "code_hash" field.
func (u *OAuthCodeUpsertOne) SetCodeHash(v string) *OAuthCodeUpsertOne {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.SetCodeHash(v)
	})
}

// UpdateCodeHash sets the "code_hash" field to the value that was provided on create.
func (u *OAuthCodeUpsertOne) UpdateCodeHash() *OAuthCodeUpsertOne {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.UpdateCodeHash()
	})
}

// SetClientID sets the "client_id" field.
func (u *OAuthCodeUpsertOne) SetClientID(v string) *OAuthCodeUpsertOne {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *OAuthCodeUpsertOne) UpdateClientID() *OAuthCodeUpsertOne {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.UpdateClientID()
	})
}

// SetUserID sets the "user_id" field.
func (u *OAuthCodeUpsertOne) SetUserID(v int64) *OAuthCodeUpsertOne {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *OAuthCodeUpsertOne) AddUserID(v int64) *OAuthCodeUpsertOne {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OAuthCodeUpsertOne) UpdateUserID() *OAuthCodeUpsertOne {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.UpdateUserID()
	})
}

// SetRedirectURI sets the "redirect_uri" field.
func (u *OAuthCodeUpsertOne) SetRedirectURI(v string) *OAuthCodeUpsertOne {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.SetRedirectURI(v)
	})
}

// UpdateRedirectURI sets the "redirect_uri" field to the value that was provided on create.
func (u *OAuthCodeUpsertOne) UpdateRedirectURI() *OAuthCodeUpsertOne {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.UpdateRedirectURI()
	})
}

// SetScopes sets the "scopes" field.
func (u *OAuthCodeUpsertOne) SetScopes(v []string) *OAuthCodeUpsertOne {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.SetScopes(v)
	})
}

// UpdateScopes sets the "scopes" field to the value that was provided on create.
func (u *OAuthCodeUpsertOne) UpdateScopes() *OAuthCodeUpsertOne {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.UpdateScopes()
	})
}

// SetCodeChallenge sets the "code_challenge" field.
func (u *OAuthCodeUpsertOne) SetCodeChallenge(v string) *OAuthCodeUpsertOne {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.SetCodeChallenge(v)
	})
}

// UpdateCodeChallenge sets the "code_challenge" field to the value that was provided on create.
func (u *OAuthCodeUpsertOne) UpdateCodeChallenge() *OAuthCodeUpsertOne {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.UpdateCodeChallenge()
	})
}

// SetCodeChallengeMethod sets the "code_challenge_method" field.
func (u *OAuthCodeUpsertOne) SetCodeChallengeMethod(v string) *OAuthCodeUpsertOne {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.SetCodeChallengeMethod(v)
	})
}

// UpdateCodeChallengeMethod sets the "code_challenge_method" field to the value that was provided on create.
func (u *OAuthCodeUpsertOne) UpdateCodeChallengeMethod() *OAuthCodeUpsertOne {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.UpdateCodeChallengeMethod()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *OAuthCodeUpsertOne) SetExpiresAt(v time.Time) *OAuthCodeUpsertOne {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *OAuthCodeUpsertOne) UpdateExpiresAt() *OAuthCodeUpsertOne {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetUsedAt sets the "used_at" field.
func (u *OAuthCodeUpsertOne) SetUsedAt(v time.Time) *OAuthCodeUpsertOne {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.SetUsedAt(v)
	})
}

// UpdateUsedAt sets the "used_at" field to the value that was provided on create.
func (u *OAuthCodeUpsertOne) UpdateUsedAt() *OAuthCodeUpsertOne {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.UpdateUsedAt()
	})
}

// ClearUsedAt clears the value of the "used_at" field.
func (u *OAuthCodeUpsertOne) ClearUsedAt() *OAuthCodeUpsertOne {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.ClearUsedAt()
	})
}

// SetGroupID sets the "group_id" field.
func (u *OAuthCodeUpsertOne) SetGroupID(v int64) *OAuthCodeUpsertOne {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *OAuthCodeUpsertOne) AddGroupID(v int64) *OAuthCodeUpsertOne {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *OAuthCodeUpsertOne) UpdateGroupID() *OAuthCodeUpsertOne {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *OAuthCodeUpsertOne) ClearGroupID() *OAuthCodeUpsertOne {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.ClearGroupID()
	})
}

// SetGrantID sets the "grant_id" field.
func (u *OAuthCodeUpsertOne) SetGrantID(v string) *OAuthCodeUpsertOne {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.SetGrantID(v)
	})
}

// UpdateGrantID sets the "grant_id" field to the value that was provided on create.
func (u *OAuthCodeUpsertOne) UpdateGrantID() *OAuthCodeUpsertOne {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.UpdateGrantID()
	})
}

// ClearGrantID clears the value of the "grant_id" field.
func (u *OAuthCodeUpsertOne) ClearGrantID() *OAuthCodeUpsertOne {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.ClearGrantID()
	})
}

// SetAllowedGroupsSnapshot sets the "allowed_groups_snapshot" field.
func (u *OAuthCodeUpsertOne) SetAllowedGroupsSnapshot(v []int64) *OAuthCodeUpsertOne {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.SetAllowedGroupsSnapshot(v)
	})
}

// UpdateAllowedGroupsSnapshot sets the "allowed_groups_snapshot" field to the value that was provided on create.
func (u *OAuthCodeUpsertOne) UpdateAllowedGroupsSnapshot() *OAuthCodeUpsertOne {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.UpdateAllowedGroupsSnapshot()
	})
}

// SetDeviceID sets the "device_id" field.
func (u *OAuthCodeUpsertOne) SetDeviceID(v string) *OAuthCodeUpsertOne {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.SetDeviceID(v)
	})
}

// UpdateDeviceID sets the "device_id" field to the value that was provided on create.
func (u *OAuthCodeUpsertOne) UpdateDeviceID() *OAuthCodeUpsertOne {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.UpdateDeviceID()
	})
}

// ClearDeviceID clears the value of the "device_id" field.
func (u *OAuthCodeUpsertOne) ClearDeviceID() *OAuthCodeUpsertOne {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.ClearDeviceID()
	})
}

// SetDeviceName sets the "device_name" field.
func (u *OAuthCodeUpsertOne) SetDeviceName(v string) *OAuthCodeUpsertOne {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.SetDeviceName(v)
	})
}

// UpdateDeviceName sets the "device_name" field to the value that was provided on create.
func (u *OAuthCodeUpsertOne) UpdateDeviceName() *OAuthCodeUpsertOne {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.UpdateDeviceName()
	})
}

// ClearDeviceName clears the value of the "device_name" field.
func (u *OAuthCodeUpsertOne) ClearDeviceName() *OAuthCodeUpsertOne {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.ClearDeviceName()
	})
}

// Exec executes the query.
func (u *OAuthCodeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OAuthCodeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OAuthCodeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OAuthCodeUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OAuthCodeUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OAuthCodeCreateBulk is the builder for creating many OAuthCode entities in bulk.
type OAuthCodeCreateBulk struct {
	config
	err      error
	builders []*OAuthCodeCreate
	conflict []sql.ConflictOption
}

// Save creates the OAuthCode entities in the database.
func (_c *OAuthCodeCreateBulk) Save(ctx context.Context) ([]*OAuthCode, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OAuthCode, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OAuthCodeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OAuthCodeCreateBulk) SaveX(ctx context.Context) []*OAuthCode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthCodeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthCodeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OAuthCode.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OAuthCodeUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OAuthCodeCreateBulk) OnConflict(opts ...sql.ConflictOption) *OAuthCodeUpsertBulk {
	_c.conflict = opts
	return &OAuthCodeUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OAuthCode.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OAuthCodeCreateBulk) OnConflictColumns(columns ...string) *OAuthCodeUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OAuthCodeUpsertBulk{
		create: _c,
	}
}

// OAuthCodeUpsertBulk is the builder for "upsert"-ing
// a bulk of OAuthCode nodes.
type OAuthCodeUpsertBulk struct {
	create *OAuthCodeCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OAuthCode.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OAuthCodeUpsertBulk) UpdateNewValues() *OAuthCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(oauthcode.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OAuthCode.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OAuthCodeUpsertBulk) Ignore() *OAuthCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OAuthCodeUpsertBulk) DoNothing() *OAuthCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OAuthCodeCreateBulk.OnConflict
// documentation for more info.
func (u *OAuthCodeUpsertBulk) Update(set func(*OAuthCodeUpsert)) *OAuthCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OAuthCodeUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OAuthCodeUpsertBulk) SetUpdatedAt(v time.Time) *OAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OAuthCodeUpsertBulk) UpdateUpdatedAt() *OAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetCodeHash sets the "code_hash" field.
func (u *OAuthCodeUpsertBulk) SetCodeHash(v string) *OAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.SetCodeHash(v)
	})
}

// UpdateCodeHash sets the "code_hash" field to the value that was provided on create.
func (u *OAuthCodeUpsertBulk) UpdateCodeHash() *OAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.UpdateCodeHash()
	})
}

// SetClientID sets the "client_id" field.
func (u *OAuthCodeUpsertBulk) SetClientID(v string) *OAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *OAuthCodeUpsertBulk) UpdateClientID() *OAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.UpdateClientID()
	})
}

// SetUserID sets the "user_id" field.
func (u *OAuthCodeUpsertBulk) SetUserID(v int64) *OAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *OAuthCodeUpsertBulk) AddUserID(v int64) *OAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OAuthCodeUpsertBulk) UpdateUserID() *OAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.UpdateUserID()
	})
}

// SetRedirectURI sets the "redirect_uri" field.
func (u *OAuthCodeUpsertBulk) SetRedirectURI(v string) *OAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.SetRedirectURI(v)
	})
}

// UpdateRedirectURI sets the "redirect_uri" field to the value that was provided on create.
func (u *OAuthCodeUpsertBulk) UpdateRedirectURI() *OAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.UpdateRedirectURI()
	})
}

// SetScopes sets the "scopes" field.
func (u *OAuthCodeUpsertBulk) SetScopes(v []string) *OAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.SetScopes(v)
	})
}

// UpdateScopes sets the "scopes" field to the value that was provided on create.
func (u *OAuthCodeUpsertBulk) UpdateScopes() *OAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.UpdateScopes()
	})
}

// SetCodeChallenge sets the "code_challenge" field.
func (u *OAuthCodeUpsertBulk) SetCodeChallenge(v string) *OAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.SetCodeChallenge(v)
	})
}

// UpdateCodeChallenge sets the "code_challenge" field to the value that was provided on create.
func (u *OAuthCodeUpsertBulk) UpdateCodeChallenge() *OAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.UpdateCodeChallenge()
	})
}

// SetCodeChallengeMethod sets the "code_challenge_method" field.
func (u *OAuthCodeUpsertBulk) SetCodeChallengeMethod(v string) *OAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.SetCodeChallengeMethod(v)
	})
}

// UpdateCodeChallengeMethod sets the "code_challenge_method" field to the value that was provided on create.
func (u *OAuthCodeUpsertBulk) UpdateCodeChallengeMethod() *OAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.UpdateCodeChallengeMethod()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *OAuthCodeUpsertBulk) SetExpiresAt(v time.Time) *OAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *OAuthCodeUpsertBulk) UpdateExpiresAt() *OAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetUsedAt sets the "used_at" field.
func (u *OAuthCodeUpsertBulk) SetUsedAt(v time.Time) *OAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.SetUsedAt(v)
	})
}

// UpdateUsedAt sets the "used_at" field to the value that was provided on create.
func (u *OAuthCodeUpsertBulk) UpdateUsedAt() *OAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.UpdateUsedAt()
	})
}

// ClearUsedAt clears the value of the "used_at" field.
func (u *OAuthCodeUpsertBulk) ClearUsedAt() *OAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.ClearUsedAt()
	})
}

// SetGroupID sets the "group_id" field.
func (u *OAuthCodeUpsertBulk) SetGroupID(v int64) *OAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *OAuthCodeUpsertBulk) AddGroupID(v int64) *OAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *OAuthCodeUpsertBulk) UpdateGroupID() *OAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *OAuthCodeUpsertBulk) ClearGroupID() *OAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.ClearGroupID()
	})
}

// SetGrantID sets the "grant_id" field.
func (u *OAuthCodeUpsertBulk) SetGrantID(v string) *OAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.SetGrantID(v)
	})
}

// UpdateGrantID sets the "grant_id" field to the value that was provided on create.
func (u *OAuthCodeUpsertBulk) UpdateGrantID() *OAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.UpdateGrantID()
	})
}

// ClearGrantID clears the value of the "grant_id" field.
func (u *OAuthCodeUpsertBulk) ClearGrantID() *OAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.ClearGrantID()
	})
}

// SetAllowedGroupsSnapshot sets the "allowed_groups_snapshot" field.
func (u *OAuthCodeUpsertBulk) SetAllowedGroupsSnapshot(v []int64) *OAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.SetAllowedGroupsSnapshot(v)
	})
}

// UpdateAllowedGroupsSnapshot sets the "allowed_groups_snapshot" field to the value that was provided on create.
func (u *OAuthCodeUpsertBulk) UpdateAllowedGroupsSnapshot() *OAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.UpdateAllowedGroupsSnapshot()
	})
}

// SetDeviceID sets the "device_id" field.
func (u *OAuthCodeUpsertBulk) SetDeviceID(v string) *OAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.SetDeviceID(v)
	})
}

// UpdateDeviceID sets the "device_id" field to the value that was provided on create.
func (u *OAuthCodeUpsertBulk) UpdateDeviceID() *OAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.UpdateDeviceID()
	})
}

// ClearDeviceID clears the value of the "device_id" field.
func (u *OAuthCodeUpsertBulk) ClearDeviceID() *OAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.ClearDeviceID()
	})
}

// SetDeviceName sets the "device_name" field.
func (u *OAuthCodeUpsertBulk) SetDeviceName(v string) *OAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.SetDeviceName(v)
	})
}

// UpdateDeviceName sets the "device_name" field to the value that was provided on create.
func (u *OAuthCodeUpsertBulk) UpdateDeviceName() *OAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.UpdateDeviceName()
	})
}

// ClearDeviceName clears the value of the "device_name" field.
func (u *OAuthCodeUpsertBulk) ClearDeviceName() *OAuthCodeUpsertBulk {
	return u.Update(func(s *OAuthCodeUpsert) {
		s.ClearDeviceName()
	})
}

// Exec executes the query.
func (u *OAuthCodeUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OAuthCodeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OAuthCodeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OAuthCodeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
