// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/oauthauthorizetransaction"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// OAuthAuthorizeTransactionDelete is the builder for deleting a OAuthAuthorizeTransaction entity.
type OAuthAuthorizeTransactionDelete struct {
	config
	hooks    []Hook
	mutation *OAuthAuthorizeTransactionMutation
}

// Where appends a list predicates to the OAuthAuthorizeTransactionDelete builder.
func (_d *OAuthAuthorizeTransactionDelete) Where(ps ...predicate.OAuthAuthorizeTransaction) *OAuthAuthorizeTransactionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *OAuthAuthorizeTransactionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OAuthAuthorizeTransactionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *OAuthAuthorizeTransactionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(oauthauthorizetransaction.Table, sqlgraph.NewFieldSpec(oauthauthorizetransaction.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// OAuthAuthorizeTransactionDeleteOne is the builder for deleting a single OAuthAuthorizeTransaction entity.
type OAuthAuthorizeTransactionDeleteOne struct {
	_d *OAuthAuthorizeTransactionDelete
}

// Where appends a list predicates to the OAuthAuthorizeTransactionDelete builder.
func (_d *OAuthAuthorizeTransactionDeleteOne) Where(ps ...predicate.OAuthAuthorizeTransaction) *OAuthAuthorizeTransactionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *OAuthAuthorizeTransactionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{oauthauthorizetransaction.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OAuthAuthorizeTransactionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
