// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/oauthauthorizetransaction"
)

// OAuthAuthorizeTransactionCreate is the builder for creating a OAuthAuthorizeTransaction entity.
type OAuthAuthorizeTransactionCreate struct {
	config
	mutation *OAuthAuthorizeTransactionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *OAuthAuthorizeTransactionCreate) SetCreatedAt(v time.Time) *OAuthAuthorizeTransactionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OAuthAuthorizeTransactionCreate) SetNillableCreatedAt(v *time.Time) *OAuthAuthorizeTransactionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OAuthAuthorizeTransactionCreate) SetUpdatedAt(v time.Time) *OAuthAuthorizeTransactionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OAuthAuthorizeTransactionCreate) SetNillableUpdatedAt(v *time.Time) *OAuthAuthorizeTransactionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTransactionID sets the "transaction_id" field.
func (_c *OAuthAuthorizeTransactionCreate) SetTransactionID(v string) *OAuthAuthorizeTransactionCreate {
	_c.mutation.SetTransactionID(v)
	return _c
}

// SetCsrfHash sets the "csrf_hash" field.
func (_c *OAuthAuthorizeTransactionCreate) SetCsrfHash(v string) *OAuthAuthorizeTransactionCreate {
	_c.mutation.SetCsrfHash(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *OAuthAuthorizeTransactionCreate) SetUserID(v int64) *OAuthAuthorizeTransactionCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetClientID sets the "client_id" field.
func (_c *OAuthAuthorizeTransactionCreate) SetClientID(v string) *OAuthAuthorizeTransactionCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetRedirectURI sets the "redirect_uri" field.
func (_c *OAuthAuthorizeTransactionCreate) SetRedirectURI(v string) *OAuthAuthorizeTransactionCreate {
	_c.mutation.SetRedirectURI(v)
	return _c
}

// SetResponseType sets the "response_type" field.
func (_c *OAuthAuthorizeTransactionCreate) SetResponseType(v string) *OAuthAuthorizeTransactionCreate {
	_c.mutation.SetResponseType(v)
	return _c
}

// SetNillableResponseType sets the "response_type" field if the given value is not nil.
func (_c *OAuthAuthorizeTransactionCreate) SetNillableResponseType(v *string) *OAuthAuthorizeTransactionCreate {
	if v != nil {
		_c.SetResponseType(*v)
	}
	return _c
}

// SetScopes sets the "scopes" field.
func (_c *OAuthAuthorizeTransactionCreate) SetScopes(v []string) *OAuthAuthorizeTransactionCreate {
	_c.mutation.SetScopes(v)
	return _c
}

// SetAllowedGroupsSnapshot sets the "allowed_groups_snapshot" field.
func (_c *OAuthAuthorizeTransactionCreate) SetAllowedGroupsSnapshot(v []int64) *OAuthAuthorizeTransactionCreate {
	_c.mutation.SetAllowedGroupsSnapshot(v)
	return _c
}

// SetState sets the "state" field.
func (_c *OAuthAuthorizeTransactionCreate) SetState(v string) *OAuthAuthorizeTransactionCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetCodeChallenge sets the "code_challenge" field.
func (_c *OAuthAuthorizeTransactionCreate) SetCodeChallenge(v string) *OAuthAuthorizeTransactionCreate {
	_c.mutation.SetCodeChallenge(v)
	return _c
}

// SetCodeChallengeMethod sets the "code_challenge_method" field.
func (_c *OAuthAuthorizeTransactionCreate) SetCodeChallengeMethod(v string) *OAuthAuthorizeTransactionCreate {
	_c.mutation.SetCodeChallengeMethod(v)
	return _c
}

// SetNillableCodeChallengeMethod sets the "code_challenge_method" field if the given value is not nil.
func (_c *OAuthAuthorizeTransactionCreate) SetNillableCodeChallengeMethod(v *string) *OAuthAuthorizeTransactionCreate {
	if v != nil {
		_c.SetCodeChallengeMethod(*v)
	}
	return _c
}

// SetRequestedGroupID sets the "requested_group_id" field.
func (_c *OAuthAuthorizeTransactionCreate) SetRequestedGroupID(v int64) *OAuthAuthorizeTransactionCreate {
	_c.mutation.SetRequestedGroupID(v)
	return _c
}

// SetNillableRequestedGroupID sets the "requested_group_id" field if the given value is not nil.
func (_c *OAuthAuthorizeTransactionCreate) SetNillableRequestedGroupID(v *int64) *OAuthAuthorizeTransactionCreate {
	if v != nil {
		_c.SetRequestedGroupID(*v)
	}
	return _c
}

// SetDeviceID sets the "device_id" field.
func (_c *OAuthAuthorizeTransactionCreate) SetDeviceID(v string) *OAuthAuthorizeTransactionCreate {
	_c.mutation.SetDeviceID(v)
	return _c
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_c *OAuthAuthorizeTransactionCreate) SetNillableDeviceID(v *string) *OAuthAuthorizeTransactionCreate {
	if v != nil {
		_c.SetDeviceID(*v)
	}
	return _c
}

// SetDeviceName sets the "device_name" field.
func (_c *OAuthAuthorizeTransactionCreate) SetDeviceName(v string) *OAuthAuthorizeTransactionCreate {
	_c.mutation.SetDeviceName(v)
	return _c
}

// SetNillableDeviceName sets the "device_name" field if the given value is not nil.
func (_c *OAuthAuthorizeTransactionCreate) SetNillableDeviceName(v *string) *OAuthAuthorizeTransactionCreate {
	if v != nil {
		_c.SetDeviceName(*v)
	}
	return _c
}

// SetConsumedAt sets the "consumed_at" field.
func (_c *OAuthAuthorizeTransactionCreate) SetConsumedAt(v time.Time) *OAuthAuthorizeTransactionCreate {
	_c.mutation.SetConsumedAt(v)
	return _c
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_c *OAuthAuthorizeTransactionCreate) SetNillableConsumedAt(v *time.Time) *OAuthAuthorizeTransactionCreate {
	if v != nil {
		_c.SetConsumedAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *OAuthAuthorizeTransactionCreate) SetExpiresAt(v time.Time) *OAuthAuthorizeTransactionCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetCreatedIP sets the "created_ip" field.
func (_c *OAuthAuthorizeTransactionCreate) SetCreatedIP(v string) *OAuthAuthorizeTransactionCreate {
	_c.mutation.SetCreatedIP(v)
	return _c
}

// SetNillableCreatedIP sets the "created_ip" field if the given value is not nil.
func (_c *OAuthAuthorizeTransactionCreate) SetNillableCreatedIP(v *string) *OAuthAuthorizeTransactionCreate {
	if v != nil {
		_c.SetCreatedIP(*v)
	}
	return _c
}

// SetCreatedUserAgent sets the "created_user_agent" field.
func (_c *OAuthAuthorizeTransactionCreate) SetCreatedUserAgent(v string) *OAuthAuthorizeTransactionCreate {
	_c.mutation.SetCreatedUserAgent(v)
	return _c
}

// SetNillableCreatedUserAgent sets the "created_user_agent" field if the given value is not nil.
func (_c *OAuthAuthorizeTransactionCreate) SetNillableCreatedUserAgent(v *string) *OAuthAuthorizeTransactionCreate {
	if v != nil {
		_c.SetCreatedUserAgent(*v)
	}
	return _c
}

// Mutation returns the OAuthAuthorizeTransactionMutation object of the builder.
func (_c *OAuthAuthorizeTransactionCreate) Mutation() *OAuthAuthorizeTransactionMutation {
	return _c.mutation
}

// Save creates the OAuthAuthorizeTransaction in the database.
func (_c *OAuthAuthorizeTransactionCreate) Save(ctx context.Context) (*OAuthAuthorizeTransaction, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OAuthAuthorizeTransactionCreate) SaveX(ctx context.Context) *OAuthAuthorizeTransaction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthAuthorizeTransactionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthAuthorizeTransactionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OAuthAuthorizeTransactionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := oauthauthorizetransaction.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := oauthauthorizetransaction.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ResponseType(); !ok {
		v := oauthauthorizetransaction.DefaultResponseType
		_c.mutation.SetResponseType(v)
	}
	if _, ok := _c.mutation.Scopes(); !ok {
		v := oauthauthorizetransaction.DefaultScopes
		_c.mutation.SetScopes(v)
	}
	if _, ok := _c.mutation.AllowedGroupsSnapshot(); !ok {
		v := oauthauthorizetransaction.DefaultAllowedGroupsSnapshot
		_c.mutation.SetAllowedGroupsSnapshot(v)
	}
	if _, ok := _c.mutation.CodeChallengeMethod(); !ok {
		v := oauthauthorizetransaction.DefaultCodeChallengeMethod
		_c.mutation.SetCodeChallengeMethod(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OAuthAuthorizeTransactionCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OAuthAuthorizeTransaction.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OAuthAuthorizeTransaction.updated_at"`)}
	}
	if _, ok := _c.mutation.TransactionID(); !ok {
		return &ValidationError{Name: "transaction_id", err: errors.New(`ent: missing required field "OAuthAuthorizeTransaction.transaction_id"`)}
	}
	if v, ok := _c.mutation.TransactionID(); ok {
		if err := oauthauthorizetransaction.TransactionIDValidator(v); err != nil {
			return &ValidationError{Name: "transaction_id", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizeTransaction.transaction_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CsrfHash(); !ok {
		return &ValidationError{Name: "csrf_hash", err: errors.New(`ent: missing required field "OAuthAuthorizeTransaction.csrf_hash"`)}
	}
	if v, ok := _c.mutation.CsrfHash(); ok {
		if err := oauthauthorizetransaction.CsrfHashValidator(v); err != nil {
			return &ValidationError{Name: "csrf_hash", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizeTransaction.csrf_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "OAuthAuthorizeTransaction.user_id"`)}
	}
	if _, ok := _c.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`ent: missing required field "OAuthAuthorizeTransaction.client_id"`)}
	}
	if v, ok := _c.mutation.ClientID(); ok {
		if err := oauthauthorizetransaction.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizeTransaction.client_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RedirectURI(); !ok {
		return &ValidationError{Name: "redirect_uri", err: errors.New(`ent: missing required field "OAuthAuthorizeTransaction.redirect_uri"`)}
	}
	if v, ok := _c.mutation.RedirectURI(); ok {
		if err := oauthauthorizetransaction.RedirectURIValidator(v); err != nil {
			return &ValidationError{Name: "redirect_uri", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizeTransaction.redirect_uri": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ResponseType(); !ok {
		return &ValidationError{Name: "response_type", err: errors.New(`ent: missing required field "OAuthAuthorizeTransaction.response_type"`)}
	}
	if v, ok := _c.mutation.ResponseType(); ok {
		if err := oauthauthorizetransaction.ResponseTypeValidator(v); err != nil {
			return &ValidationError{Name: "response_type", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizeTransaction.response_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Scopes(); !ok {
		return &ValidationError{Name: "scopes", err: errors.New(`ent: missing required field "OAuthAuthorizeTransaction.scopes"`)}
	}
	if _, ok := _c.mutation.AllowedGroupsSnapshot(); !ok {
		return &ValidationError{Name: "allowed_groups_snapshot", err: errors.New(`ent: missing required field "OAuthAuthorizeTransaction.allowed_groups_snapshot"`)}
	}
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "OAuthAuthorizeTransaction.state"`)}
	}
	if _, ok := _c.mutation.CodeChallenge(); !ok {
		return &ValidationError{Name: "code_challenge", err: errors.New(`ent: missing required field "OAuthAuthorizeTransaction.code_challenge"`)}
	}
	if v, ok := _c.mutation.CodeChallenge(); ok {
		if err := oauthauthorizetransaction.CodeChallengeValidator(v); err != nil {
			return &ValidationError{Name: "code_challenge", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizeTransaction.code_challenge": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CodeChallengeMethod(); !ok {
		return &ValidationError{Name: "code_challenge_method", err: errors.New(`ent: missing required field "OAuthAuthorizeTransaction.code_challenge_method"`)}
	}
	if v, ok := _c.mutation.CodeChallengeMethod(); ok {
		if err := oauthauthorizetransaction.CodeChallengeMethodValidator(v); err != nil {
			return &ValidationError{Name: "code_challenge_method", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizeTransaction.code_challenge_method": %w`, err)}
		}
	}
	if v, ok := _c.mutation.DeviceID(); ok {
		if err := oauthauthorizetransaction.DeviceIDValidator(v); err != nil {
			return &ValidationError{Name: "device_id", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizeTransaction.device_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.DeviceName(); ok {
		if err := oauthauthorizetransaction.DeviceNameValidator(v); err != nil {
			return &ValidationError{Name: "device_name", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizeTransaction.device_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "OAuthAuthorizeTransaction.expires_at"`)}
	}
	if v, ok := _c.mutation.CreatedIP(); ok {
		if err := oauthauthorizetransaction.CreatedIPValidator(v); err != nil {
			return &ValidationError{Name: "created_ip", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizeTransaction.created_ip": %w`, err)}
		}
	}
	return nil
}

func (_c *OAuthAuthorizeTransactionCreate) sqlSave(ctx context.Context) (*OAuthAuthorizeTransaction, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OAuthAuthorizeTransactionCreate) createSpec() (*OAuthAuthorizeTransaction, *sqlgraph.CreateSpec) {
	var (
		_node = &OAuthAuthorizeTransaction{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(oauthauthorizetransaction.Table, sqlgraph.NewFieldSpec(oauthauthorizetransaction.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(oauthauthorizetransaction.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthauthorizetransaction.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.TransactionID(); ok {
		_spec.SetField(oauthauthorizetransaction.FieldTransactionID, field.TypeString, value)
		_node.TransactionID = value
	}
	if value, ok := _c.mutation.CsrfHash(); ok {
		_spec.SetField(oauthauthorizetransaction.FieldCsrfHash, field.TypeString, value)
		_node.CsrfHash = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(oauthauthorizetransaction.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(oauthauthorizetransaction.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := _c.mutation.RedirectURI(); ok {
		_spec.SetField(oauthauthorizetransaction.FieldRedirectURI, field.TypeString, value)
		_node.RedirectURI = value
	}
	if value, ok := _c.mutation.ResponseType(); ok {
		_spec.SetField(oauthauthorizetransaction.FieldResponseType, field.TypeString, value)
		_node.ResponseType = value
	}
	if value, ok := _c.mutation.Scopes(); ok {
		_spec.SetField(oauthauthorizetransaction.FieldScopes, field.TypeJSON, value)
		_node.Scopes = value
	}
	if value, ok := _c.mutation.AllowedGroupsSnapshot(); ok {
		_spec.SetField(oauthauthorizetransaction.FieldAllowedGroupsSnapshot, field.TypeJSON, value)
		_node.AllowedGroupsSnapshot = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(oauthauthorizetransaction.FieldState, field.TypeString, value)
		_node.State = value
	}
	if value, ok := _c.mutation.CodeChallenge(); ok {
		_spec.SetField(oauthauthorizetransaction.FieldCodeChallenge, field.TypeString, value)
		_node.CodeChallenge = value
	}
	if value, ok := _c.mutation.CodeChallengeMethod(); ok {
		_spec.SetField(oauthauthorizetransaction.FieldCodeChallengeMethod, field.TypeString, value)
		_node.CodeChallengeMethod = value
	}
	if value, ok := _c.mutation.RequestedGroupID(); ok {
		_spec.SetField(oauthauthorizetransaction.FieldRequestedGroupID, field.TypeInt64, value)
		_node.RequestedGroupID = &value
	}
	if value, ok := _c.mutation.DeviceID(); ok {
		_spec.SetField(oauthauthorizetransaction.FieldDeviceID, field.TypeString, value)
		_node.DeviceID = &value
	}
	if value, ok := _c.mutation.DeviceName(); ok {
		_spec.SetField(oauthauthorizetransaction.FieldDeviceName, field.TypeString, value)
		_node.DeviceName = &value
	}
	if value, ok := _c.mutation.ConsumedAt(); ok {
		_spec.SetField(oauthauthorizetransaction.FieldConsumedAt, field.TypeTime, value)
		_node.ConsumedAt = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthauthorizetransaction.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.CreatedIP(); ok {
		_spec.SetField(oauthauthorizetransaction.FieldCreatedIP, field.TypeString, value)
		_node.CreatedIP = &value
	}
	if value, ok := _c.mutation.CreatedUserAgent(); ok {
		_spec.SetField(oauthauthorizetransaction.FieldCreatedUserAgent, field.TypeString, value)
		_node.CreatedUserAgent = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OAuthAuthorizeTransaction.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OAuthAuthorizeTransactionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OAuthAuthorizeTransactionCreate) OnConflict(opts ...sql.ConflictOption) *OAuthAuthorizeTransactionUpsertOne {
	_c.conflict = opts
	return &OAuthAuthorizeTransactionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OAuthAuthorizeTransaction.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OAuthAuthorizeTransactionCreate) OnConflictColumns(columns ...string) *OAuthAuthorizeTransactionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OAuthAuthorizeTransactionUpsertOne{
		create: _c,
	}
}

type (
	// OAuthAuthorizeTransactionUpsertOne is the builder for "upsert"-ing
	//  one OAuthAuthorizeTransaction node.
	OAuthAuthorizeTransactionUpsertOne struct {
		create *OAuthAuthorizeTransactionCreate
	}

	// OAuthAuthorizeTransactionUpsert is the "OnConflict" setter.
	OAuthAuthorizeTransactionUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *OAuthAuthorizeTransactionUpsert) SetUpdatedAt(v time.Time) *OAuthAuthorizeTransactionUpsert {
	u.Set(oauthauthorizetransaction.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsert) UpdateUpdatedAt() *OAuthAuthorizeTransactionUpsert {
	u.SetExcluded(oauthauthorizetransaction.FieldUpdatedAt)
	return u
}

// SetTransactionID sets the "transaction_id" field.
func (u *OAuthAuthorizeTransactionUpsert) SetTransactionID(v string) *OAuthAuthorizeTransactionUpsert {
	u.Set(oauthauthorizetransaction.FieldTransactionID, v)
	return u
}

// UpdateTransactionID sets the "transaction_id" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsert) UpdateTransactionID() *OAuthAuthorizeTransactionUpsert {
	u.SetExcluded(oauthauthorizetransaction.FieldTransactionID)
	return u
}

// SetCsrfHash sets the "csrf_hash" field.
func (u *OAuthAuthorizeTransactionUpsert) SetCsrfHash(v string) *OAuthAuthorizeTransactionUpsert {
	u.Set(oauthauthorizetransaction.FieldCsrfHash, v)
	return u
}

// UpdateCsrfHash sets the "csrf_hash" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsert) UpdateCsrfHash() *OAuthAuthorizeTransactionUpsert {
	u.SetExcluded(oauthauthorizetransaction.FieldCsrfHash)
	return u
}

// SetUserID sets the "user_id" field.
func (u *OAuthAuthorizeTransactionUpsert) SetUserID(v int64) *OAuthAuthorizeTransactionUpsert {
	u.Set(oauthauthorizetransaction.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsert) UpdateUserID() *OAuthAuthorizeTransactionUpsert {
	u.SetExcluded(oauthauthorizetransaction.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *OAuthAuthorizeTransactionUpsert) AddUserID(v int64) *OAuthAuthorizeTransactionUpsert {
	u.Add(oauthauthorizetransaction.FieldUserID, v)
	return u
}

// SetClientID sets the "client_id" field.
func (u *OAuthAuthorizeTransactionUpsert) SetClientID(v string) *OAuthAuthorizeTransactionUpsert {
	u.Set(oauthauthorizetransaction.FieldClientID, v)
	return u
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsert) UpdateClientID() *OAuthAuthorizeTransactionUpsert {
	u.SetExcluded(oauthauthorizetransaction.FieldClientID)
	return u
}

// SetRedirectURI sets the "redirect_uri" field.
func (u *OAuthAuthorizeTransactionUpsert) SetRedirectURI(v string) *OAuthAuthorizeTransactionUpsert {
	u.Set(oauthauthorizetransaction.FieldRedirectURI, v)
	return u
}

// UpdateRedirectURI sets the "redirect_uri" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsert) UpdateRedirectURI() *OAuthAuthorizeTransactionUpsert {
	u.SetExcluded(oauthauthorizetransaction.FieldRedirectURI)
	return u
}

// SetResponseType sets the "response_type" field.
func (u *OAuthAuthorizeTransactionUpsert) SetResponseType(v string) *OAuthAuthorizeTransactionUpsert {
	u.Set(oauthauthorizetransaction.FieldResponseType, v)
	return u
}

// UpdateResponseType sets the "response_type" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsert) UpdateResponseType() *OAuthAuthorizeTransactionUpsert {
	u.SetExcluded(oauthauthorizetransaction.FieldResponseType)
	return u
}

// SetScopes sets the "scopes" field.
func (u *OAuthAuthorizeTransactionUpsert) SetScopes(v []string) *OAuthAuthorizeTransactionUpsert {
	u.Set(oauthauthorizetransaction.FieldScopes, v)
	return u
}

// UpdateScopes sets the "scopes" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsert) UpdateScopes() *OAuthAuthorizeTransactionUpsert {
	u.SetExcluded(oauthauthorizetransaction.FieldScopes)
	return u
}

// SetAllowedGroupsSnapshot sets the "allowed_groups_snapshot" field.
func (u *OAuthAuthorizeTransactionUpsert) SetAllowedGroupsSnapshot(v []int64) *OAuthAuthorizeTransactionUpsert {
	u.Set(oauthauthorizetransaction.FieldAllowedGroupsSnapshot, v)
	return u
}

// UpdateAllowedGroupsSnapshot sets the "allowed_groups_snapshot" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsert) UpdateAllowedGroupsSnapshot() *OAuthAuthorizeTransactionUpsert {
	u.SetExcluded(oauthauthorizetransaction.FieldAllowedGroupsSnapshot)
	return u
}

// SetState sets the "state" field.
func (u *OAuthAuthorizeTransactionUpsert) SetState(v string) *OAuthAuthorizeTransactionUpsert {
	u.Set(oauthauthorizetransaction.FieldState, v)
	return u
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsert) UpdateState() *OAuthAuthorizeTransactionUpsert {
	u.SetExcluded(oauthauthorizetransaction.FieldState)
	return u
}

// SetCodeChallenge sets the "code_challenge" field.
func (u *OAuthAuthorizeTransactionUpsert) SetCodeChallenge(v string) *OAuthAuthorizeTransactionUpsert {
	u.Set(oauthauthorizetransaction.FieldCodeChallenge, v)
	return u
}

// UpdateCodeChallenge sets the "code_challenge" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsert) UpdateCodeChallenge() *OAuthAuthorizeTransactionUpsert {
	u.SetExcluded(oauthauthorizetransaction.FieldCodeChallenge)
	return u
}

// SetCodeChallengeMethod sets the "code_challenge_method" field.
func (u *OAuthAuthorizeTransactionUpsert) SetCodeChallengeMethod(v string) *OAuthAuthorizeTransactionUpsert {
	u.Set(oauthauthorizetransaction.FieldCodeChallengeMethod, v)
	return u
}

// UpdateCodeChallengeMethod sets the "code_challenge_method" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsert) UpdateCodeChallengeMethod() *OAuthAuthorizeTransactionUpsert {
	u.SetExcluded(oauthauthorizetransaction.FieldCodeChallengeMethod)
	return u
}

// SetRequestedGroupID sets the "requested_group_id" field.
func (u *OAuthAuthorizeTransactionUpsert) SetRequestedGroupID(v int64) *OAuthAuthorizeTransactionUpsert {
	u.Set(oauthauthorizetransaction.FieldRequestedGroupID, v)
	return u
}

// UpdateRequestedGroupID sets the "requested_group_id" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsert) UpdateRequestedGroupID() *OAuthAuthorizeTransactionUpsert {
	u.SetExcluded(oauthauthorizetransaction.FieldRequestedGroupID)
	return u
}

// AddRequestedGroupID adds v to the "requested_group_id" field.
func (u *OAuthAuthorizeTransactionUpsert) AddRequestedGroupID(v int64) *OAuthAuthorizeTransactionUpsert {
	u.Add(oauthauthorizetransaction.FieldRequestedGroupID, v)
	return u
}

// ClearRequestedGroupID clears the value of the "requested_group_id" field.
func (u *OAuthAuthorizeTransactionUpsert) ClearRequestedGroupID() *OAuthAuthorizeTransactionUpsert {
	u.SetNull(oauthauthorizetransaction.FieldRequestedGroupID)
	return u
}

// SetDeviceID sets the "device_id" field.
func (u *OAuthAuthorizeTransactionUpsert) SetDeviceID(v string) *OAuthAuthorizeTransactionUpsert {
	u.Set(oauthauthorizetransaction.FieldDeviceID, v)
	return u
}

// UpdateDeviceID sets the "device_id" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsert) UpdateDeviceID() *OAuthAuthorizeTransactionUpsert {
	u.SetExcluded(oauthauthorizetransaction.FieldDeviceID)
	return u
}

// ClearDeviceID clears the value of the "device_id" field.
func (u *OAuthAuthorizeTransactionUpsert) ClearDeviceID() *OAuthAuthorizeTransactionUpsert {
	u.SetNull(oauthauthorizetransaction.FieldDeviceID)
	return u
}

// SetDeviceName sets the "device_name" field.
func (u *OAuthAuthorizeTransactionUpsert) SetDeviceName(v string) *OAuthAuthorizeTransactionUpsert {
	u.Set(oauthauthorizetransaction.FieldDeviceName, v)
	return u
}

// UpdateDeviceName sets the "device_name" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsert) UpdateDeviceName() *OAuthAuthorizeTransactionUpsert {
	u.SetExcluded(oauthauthorizetransaction.FieldDeviceName)
	return u
}

// ClearDeviceName clears the value of the "device_name" field.
func (u *OAuthAuthorizeTransactionUpsert) ClearDeviceName() *OAuthAuthorizeTransactionUpsert {
	u.SetNull(oauthauthorizetransaction.FieldDeviceName)
	return u
}

// SetConsumedAt sets the "consumed_at" field.
func (u *OAuthAuthorizeTransactionUpsert) SetConsumedAt(v time.Time) *OAuthAuthorizeTransactionUpsert {
	u.Set(oauthauthorizetransaction.FieldConsumedAt, v)
	return u
}

// UpdateConsumedAt sets the "consumed_at" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsert) UpdateConsumedAt() *OAuthAuthorizeTransactionUpsert {
	u.SetExcluded(oauthauthorizetransaction.FieldConsumedAt)
	return u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (u *OAuthAuthorizeTransactionUpsert) ClearConsumedAt() *OAuthAuthorizeTransactionUpsert {
	u.SetNull(oauthauthorizetransaction.FieldConsumedAt)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *OAuthAuthorizeTransactionUpsert) SetExpiresAt(v time.Time) *OAuthAuthorizeTransactionUpsert {
	u.Set(oauthauthorizetransaction.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsert) UpdateExpiresAt() *OAuthAuthorizeTransactionUpsert {
	u.SetExcluded(oauthauthorizetransaction.FieldExpiresAt)
	return u
}

// SetCreatedIP sets the "created_ip" field.
func (u *OAuthAuthorizeTransactionUpsert) SetCreatedIP(v string) *OAuthAuthorizeTransactionUpsert {
	u.Set(oauthauthorizetransaction.FieldCreatedIP, v)
	return u
}

// UpdateCreatedIP sets the "created_ip" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsert) UpdateCreatedIP() *OAuthAuthorizeTransactionUpsert {
	u.SetExcluded(oauthauthorizetransaction.FieldCreatedIP)
	return u
}

// ClearCreatedIP clears the value of the "created_ip" field.
func (u *OAuthAuthorizeTransactionUpsert) ClearCreatedIP() *OAuthAuthorizeTransactionUpsert {
	u.SetNull(oauthauthorizetransaction.FieldCreatedIP)
	return u
}

// SetCreatedUserAgent sets the "created_user_agent" field.
func (u *OAuthAuthorizeTransactionUpsert) SetCreatedUserAgent(v string) *OAuthAuthorizeTransactionUpsert {
	u.Set(oauthauthorizetransaction.FieldCreatedUserAgent, v)
	return u
}

// UpdateCreatedUserAgent sets the "created_user_agent" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsert) UpdateCreatedUserAgent() *OAuthAuthorizeTransactionUpsert {
	u.SetExcluded(oauthauthorizetransaction.FieldCreatedUserAgent)
	return u
}

// ClearCreatedUserAgent clears the value of the "created_user_agent" field.
func (u *OAuthAuthorizeTransactionUpsert) ClearCreatedUserAgent() *OAuthAuthorizeTransactionUpsert {
	u.SetNull(oauthauthorizetransaction.FieldCreatedUserAgent)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.OAuthAuthorizeTransaction.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OAuthAuthorizeTransactionUpsertOne) UpdateNewValues() *OAuthAuthorizeTransactionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(oauthauthorizetransaction.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OAuthAuthorizeTransaction.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OAuthAuthorizeTransactionUpsertOne) Ignore() *OAuthAuthorizeTransactionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OAuthAuthorizeTransactionUpsertOne) DoNothing() *OAuthAuthorizeTransactionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OAuthAuthorizeTransactionCreate.OnConflict
// documentation for more info.
func (u *OAuthAuthorizeTransactionUpsertOne) Update(set func(*OAuthAuthorizeTransactionUpsert)) *OAuthAuthorizeTransactionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OAuthAuthorizeTransactionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OAuthAuthorizeTransactionUpsertOne) SetUpdatedAt(v time.Time) *OAuthAuthorizeTransactionUpsertOne {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsertOne) UpdateUpdatedAt() *OAuthAuthorizeTransactionUpsertOne {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetTransactionID sets the "transaction_id" field.
func (u *OAuthAuthorizeTransactionUpsertOne) SetTransactionID(v string) *OAuthAuthorizeTransactionUpsertOne {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.SetTransactionID(v)
	})
}

// UpdateTransactionID sets the "transaction_id" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsertOne) UpdateTransactionID() *OAuthAuthorizeTransactionUpsertOne {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.UpdateTransactionID()
	})
}

// SetCsrfHash sets the "csrf_hash" field.
func (u *OAuthAuthorizeTransactionUpsertOne) SetCsrfHash(v string) *OAuthAuthorizeTransactionUpsertOne {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.SetCsrfHash(v)
	})
}

// UpdateCsrfHash sets the "csrf_hash" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsertOne) UpdateCsrfHash() *OAuthAuthorizeTransactionUpsertOne {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.UpdateCsrfHash()
	})
}

// SetUserID sets the "user_id" field.
func (u *OAuthAuthorizeTransactionUpsertOne) SetUserID(v int64) *OAuthAuthorizeTransactionUpsertOne {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *OAuthAuthorizeTransactionUpsertOne) AddUserID(v int64) *OAuthAuthorizeTransactionUpsertOne {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsertOne) UpdateUserID() *OAuthAuthorizeTransactionUpsertOne {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.UpdateUserID()
	})
}

// SetClientID sets the "client_id" field.
func (u *OAuthAuthorizeTransactionUpsertOne) SetClientID(v string) *OAuthAuthorizeTransactionUpsertOne {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsertOne) UpdateClientID() *OAuthAuthorizeTransactionUpsertOne {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.UpdateClientID()
	})
}

// SetRedirectURI sets the "redirect_uri" field.
func (u *OAuthAuthorizeTransactionUpsertOne) SetRedirectURI(v string) *OAuthAuthorizeTransactionUpsertOne {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.SetRedirectURI(v)
	})
}

// UpdateRedirectURI sets the "redirect_uri" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsertOne) UpdateRedirectURI() *OAuthAuthorizeTransactionUpsertOne {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.UpdateRedirectURI()
	})
}

// SetResponseType sets the "response_type" field.
func (u *OAuthAuthorizeTransactionUpsertOne) SetResponseType(v string) *OAuthAuthorizeTransactionUpsertOne {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.SetResponseType(v)
	})
}

// UpdateResponseType sets the "response_type" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsertOne) UpdateResponseType() *OAuthAuthorizeTransactionUpsertOne {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.UpdateResponseType()
	})
}

// SetScopes sets the "scopes" field.
func (u *OAuthAuthorizeTransactionUpsertOne) SetScopes(v []string) *OAuthAuthorizeTransactionUpsertOne {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.SetScopes(v)
	})
}

// UpdateScopes sets the "scopes" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsertOne) UpdateScopes() *OAuthAuthorizeTransactionUpsertOne {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.UpdateScopes()
	})
}

// SetAllowedGroupsSnapshot sets the "allowed_groups_snapshot" field.
func (u *OAuthAuthorizeTransactionUpsertOne) SetAllowedGroupsSnapshot(v []int64) *OAuthAuthorizeTransactionUpsertOne {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.SetAllowedGroupsSnapshot(v)
	})
}

// UpdateAllowedGroupsSnapshot sets the "allowed_groups_snapshot" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsertOne) UpdateAllowedGroupsSnapshot() *OAuthAuthorizeTransactionUpsertOne {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.UpdateAllowedGroupsSnapshot()
	})
}

// SetState sets the "state" field.
func (u *OAuthAuthorizeTransactionUpsertOne) SetState(v string) *OAuthAuthorizeTransactionUpsertOne {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsertOne) UpdateState() *OAuthAuthorizeTransactionUpsertOne {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.UpdateState()
	})
}

// SetCodeChallenge sets the "code_challenge" field.
func (u *OAuthAuthorizeTransactionUpsertOne) SetCodeChallenge(v string) *OAuthAuthorizeTransactionUpsertOne {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.SetCodeChallenge(v)
	})
}

// UpdateCodeChallenge sets the "code_challenge" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsertOne) UpdateCodeChallenge() *OAuthAuthorizeTransactionUpsertOne {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.UpdateCodeChallenge()
	})
}

// SetCodeChallengeMethod sets the "code_challenge_method" field.
func (u *OAuthAuthorizeTransactionUpsertOne) SetCodeChallengeMethod(v string) *OAuthAuthorizeTransactionUpsertOne {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.SetCodeChallengeMethod(v)
	})
}

// UpdateCodeChallengeMethod sets the "code_challenge_method" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsertOne) UpdateCodeChallengeMethod() *OAuthAuthorizeTransactionUpsertOne {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.UpdateCodeChallengeMethod()
	})
}

// SetRequestedGroupID sets the "requested_group_id" field.
func (u *OAuthAuthorizeTransactionUpsertOne) SetRequestedGroupID(v int64) *OAuthAuthorizeTransactionUpsertOne {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.SetRequestedGroupID(v)
	})
}

// AddRequestedGroupID adds v to the "requested_group_id" field.
func (u *OAuthAuthorizeTransactionUpsertOne) AddRequestedGroupID(v int64) *OAuthAuthorizeTransactionUpsertOne {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.AddRequestedGroupID(v)
	})
}

// UpdateRequestedGroupID sets the "requested_group_id" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsertOne) UpdateRequestedGroupID() *OAuthAuthorizeTransactionUpsertOne {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.UpdateRequestedGroupID()
	})
}

// ClearRequestedGroupID clears the value of the "requested_group_id" field.
func (u *OAuthAuthorizeTransactionUpsertOne) ClearRequestedGroupID() *OAuthAuthorizeTransactionUpsertOne {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.ClearRequestedGroupID()
	})
}

// SetDeviceID sets the "device_id" field.
func (u *OAuthAuthorizeTransactionUpsertOne) SetDeviceID(v string) *OAuthAuthorizeTransactionUpsertOne {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.SetDeviceID(v)
	})
}

// UpdateDeviceID sets the "device_id" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsertOne) UpdateDeviceID() *OAuthAuthorizeTransactionUpsertOne {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.UpdateDeviceID()
	})
}

// ClearDeviceID clears the value of the "device_id" field.
func (u *OAuthAuthorizeTransactionUpsertOne) ClearDeviceID() *OAuthAuthorizeTransactionUpsertOne {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.ClearDeviceID()
	})
}

// SetDeviceName sets the "device_name" field.
func (u *OAuthAuthorizeTransactionUpsertOne) SetDeviceName(v string) *OAuthAuthorizeTransactionUpsertOne {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.SetDeviceName(v)
	})
}

// UpdateDeviceName sets the "device_name" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsertOne) UpdateDeviceName() *OAuthAuthorizeTransactionUpsertOne {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.UpdateDeviceName()
	})
}

// ClearDeviceName clears the value of the "device_name" field.
func (u *OAuthAuthorizeTransactionUpsertOne) ClearDeviceName() *OAuthAuthorizeTransactionUpsertOne {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.ClearDeviceName()
	})
}

// SetConsumedAt sets the "consumed_at" field.
func (u *OAuthAuthorizeTransactionUpsertOne) SetConsumedAt(v time.Time) *OAuthAuthorizeTransactionUpsertOne {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.SetConsumedAt(v)
	})
}

// UpdateConsumedAt sets the "consumed_at" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsertOne) UpdateConsumedAt() *OAuthAuthorizeTransactionUpsertOne {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.UpdateConsumedAt()
	})
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (u *OAuthAuthorizeTransactionUpsertOne) ClearConsumedAt() *OAuthAuthorizeTransactionUpsertOne {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.ClearConsumedAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *OAuthAuthorizeTransactionUpsertOne) SetExpiresAt(v time.Time) *OAuthAuthorizeTransactionUpsertOne {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsertOne) UpdateExpiresAt() *OAuthAuthorizeTransactionUpsertOne {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetCreatedIP sets the "created_ip" field.
func (u *OAuthAuthorizeTransactionUpsertOne) SetCreatedIP(v string) *OAuthAuthorizeTransactionUpsertOne {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.SetCreatedIP(v)
	})
}

// UpdateCreatedIP sets the "created_ip" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsertOne) UpdateCreatedIP() *OAuthAuthorizeTransactionUpsertOne {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.UpdateCreatedIP()
	})
}

// ClearCreatedIP clears the value of the "created_ip" field.
func (u *OAuthAuthorizeTransactionUpsertOne) ClearCreatedIP() *OAuthAuthorizeTransactionUpsertOne {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.ClearCreatedIP()
	})
}

// SetCreatedUserAgent sets the "created_user_agent" field.
func (u *OAuthAuthorizeTransactionUpsertOne) SetCreatedUserAgent(v string) *OAuthAuthorizeTransactionUpsertOne {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.SetCreatedUserAgent(v)
	})
}

// UpdateCreatedUserAgent sets the "created_user_agent" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsertOne) UpdateCreatedUserAgent() *OAuthAuthorizeTransactionUpsertOne {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.UpdateCreatedUserAgent()
	})
}

// ClearCreatedUserAgent clears the value of the "created_user_agent" field.
func (u *OAuthAuthorizeTransactionUpsertOne) ClearCreatedUserAgent() *OAuthAuthorizeTransactionUpsertOne {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.ClearCreatedUserAgent()
	})
}

// Exec executes the query.
func (u *OAuthAuthorizeTransactionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OAuthAuthorizeTransactionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OAuthAuthorizeTransactionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OAuthAuthorizeTransactionUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OAuthAuthorizeTransactionUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OAuthAuthorizeTransactionCreateBulk is the builder for creating many OAuthAuthorizeTransaction entities in bulk.
type OAuthAuthorizeTransactionCreateBulk struct {
	config
	err      error
	builders []*OAuthAuthorizeTransactionCreate
	conflict []sql.ConflictOption
}

// Save creates the OAuthAuthorizeTransaction entities in the database.
func (_c *OAuthAuthorizeTransactionCreateBulk) Save(ctx context.Context) ([]*OAuthAuthorizeTransaction, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OAuthAuthorizeTransaction, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OAuthAuthorizeTransactionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OAuthAuthorizeTransactionCreateBulk) SaveX(ctx context.Context) []*OAuthAuthorizeTransaction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthAuthorizeTransactionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthAuthorizeTransactionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OAuthAuthorizeTransaction.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OAuthAuthorizeTransactionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OAuthAuthorizeTransactionCreateBulk) OnConflict(opts ...sql.ConflictOption) *OAuthAuthorizeTransactionUpsertBulk {
	_c.conflict = opts
	return &OAuthAuthorizeTransactionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OAuthAuthorizeTransaction.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OAuthAuthorizeTransactionCreateBulk) OnConflictColumns(columns ...string) *OAuthAuthorizeTransactionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OAuthAuthorizeTransactionUpsertBulk{
		create: _c,
	}
}

// OAuthAuthorizeTransactionUpsertBulk is the builder for "upsert"-ing
// a bulk of OAuthAuthorizeTransaction nodes.
type OAuthAuthorizeTransactionUpsertBulk struct {
	create *OAuthAuthorizeTransactionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OAuthAuthorizeTransaction.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OAuthAuthorizeTransactionUpsertBulk) UpdateNewValues() *OAuthAuthorizeTransactionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(oauthauthorizetransaction.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OAuthAuthorizeTransaction.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OAuthAuthorizeTransactionUpsertBulk) Ignore() *OAuthAuthorizeTransactionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OAuthAuthorizeTransactionUpsertBulk) DoNothing() *OAuthAuthorizeTransactionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OAuthAuthorizeTransactionCreateBulk.OnConflict
// documentation for more info.
func (u *OAuthAuthorizeTransactionUpsertBulk) Update(set func(*OAuthAuthorizeTransactionUpsert)) *OAuthAuthorizeTransactionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OAuthAuthorizeTransactionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OAuthAuthorizeTransactionUpsertBulk) SetUpdatedAt(v time.Time) *OAuthAuthorizeTransactionUpsertBulk {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsertBulk) UpdateUpdatedAt() *OAuthAuthorizeTransactionUpsertBulk {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetTransactionID sets the "transaction_id" field.
func (u *OAuthAuthorizeTransactionUpsertBulk) SetTransactionID(v string) *OAuthAuthorizeTransactionUpsertBulk {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.SetTransactionID(v)
	})
}

// UpdateTransactionID sets the "transaction_id" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsertBulk) UpdateTransactionID() *OAuthAuthorizeTransactionUpsertBulk {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.UpdateTransactionID()
	})
}

// SetCsrfHash sets the "csrf_hash" field.
func (u *OAuthAuthorizeTransactionUpsertBulk) SetCsrfHash(v string) *OAuthAuthorizeTransactionUpsertBulk {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.SetCsrfHash(v)
	})
}

// UpdateCsrfHash sets the "csrf_hash" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsertBulk) UpdateCsrfHash() *OAuthAuthorizeTransactionUpsertBulk {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.UpdateCsrfHash()
	})
}

// SetUserID sets the "user_id" field.
func (u *OAuthAuthorizeTransactionUpsertBulk) SetUserID(v int64) *OAuthAuthorizeTransactionUpsertBulk {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *OAuthAuthorizeTransactionUpsertBulk) AddUserID(v int64) *OAuthAuthorizeTransactionUpsertBulk {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsertBulk) UpdateUserID() *OAuthAuthorizeTransactionUpsertBulk {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.UpdateUserID()
	})
}

// SetClientID sets the "client_id" field.
func (u *OAuthAuthorizeTransactionUpsertBulk) SetClientID(v string) *OAuthAuthorizeTransactionUpsertBulk {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsertBulk) UpdateClientID() *OAuthAuthorizeTransactionUpsertBulk {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.UpdateClientID()
	})
}

// SetRedirectURI sets the "redirect_uri" field.
func (u *OAuthAuthorizeTransactionUpsertBulk) SetRedirectURI(v string) *OAuthAuthorizeTransactionUpsertBulk {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.SetRedirectURI(v)
	})
}

// UpdateRedirectURI sets the "redirect_uri" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsertBulk) UpdateRedirectURI() *OAuthAuthorizeTransactionUpsertBulk {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.UpdateRedirectURI()
	})
}

// SetResponseType sets the "response_type" field.
func (u *OAuthAuthorizeTransactionUpsertBulk) SetResponseType(v string) *OAuthAuthorizeTransactionUpsertBulk {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.SetResponseType(v)
	})
}

// UpdateResponseType sets the "response_type" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsertBulk) UpdateResponseType() *OAuthAuthorizeTransactionUpsertBulk {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.UpdateResponseType()
	})
}

// SetScopes sets the "scopes" field.
func (u *OAuthAuthorizeTransactionUpsertBulk) SetScopes(v []string) *OAuthAuthorizeTransactionUpsertBulk {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.SetScopes(v)
	})
}

// UpdateScopes sets the "scopes" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsertBulk) UpdateScopes() *OAuthAuthorizeTransactionUpsertBulk {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.UpdateScopes()
	})
}

// SetAllowedGroupsSnapshot sets the "allowed_groups_snapshot" field.
func (u *OAuthAuthorizeTransactionUpsertBulk) SetAllowedGroupsSnapshot(v []int64) *OAuthAuthorizeTransactionUpsertBulk {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.SetAllowedGroupsSnapshot(v)
	})
}

// UpdateAllowedGroupsSnapshot sets the "allowed_groups_snapshot" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsertBulk) UpdateAllowedGroupsSnapshot() *OAuthAuthorizeTransactionUpsertBulk {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.UpdateAllowedGroupsSnapshot()
	})
}

// SetState sets the "state" field.
func (u *OAuthAuthorizeTransactionUpsertBulk) SetState(v string) *OAuthAuthorizeTransactionUpsertBulk {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsertBulk) UpdateState() *OAuthAuthorizeTransactionUpsertBulk {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.UpdateState()
	})
}

// SetCodeChallenge sets the "code_challenge" field.
func (u *OAuthAuthorizeTransactionUpsertBulk) SetCodeChallenge(v string) *OAuthAuthorizeTransactionUpsertBulk {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.SetCodeChallenge(v)
	})
}

// UpdateCodeChallenge sets the "code_challenge" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsertBulk) UpdateCodeChallenge() *OAuthAuthorizeTransactionUpsertBulk {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.UpdateCodeChallenge()
	})
}

// SetCodeChallengeMethod sets the "code_challenge_method" field.
func (u *OAuthAuthorizeTransactionUpsertBulk) SetCodeChallengeMethod(v string) *OAuthAuthorizeTransactionUpsertBulk {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.SetCodeChallengeMethod(v)
	})
}

// UpdateCodeChallengeMethod sets the "code_challenge_method" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsertBulk) UpdateCodeChallengeMethod() *OAuthAuthorizeTransactionUpsertBulk {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.UpdateCodeChallengeMethod()
	})
}

// SetRequestedGroupID sets the "requested_group_id" field.
func (u *OAuthAuthorizeTransactionUpsertBulk) SetRequestedGroupID(v int64) *OAuthAuthorizeTransactionUpsertBulk {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.SetRequestedGroupID(v)
	})
}

// AddRequestedGroupID adds v to the "requested_group_id" field.
func (u *OAuthAuthorizeTransactionUpsertBulk) AddRequestedGroupID(v int64) *OAuthAuthorizeTransactionUpsertBulk {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.AddRequestedGroupID(v)
	})
}

// UpdateRequestedGroupID sets the "requested_group_id" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsertBulk) UpdateRequestedGroupID() *OAuthAuthorizeTransactionUpsertBulk {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.UpdateRequestedGroupID()
	})
}

// ClearRequestedGroupID clears the value of the "requested_group_id" field.
func (u *OAuthAuthorizeTransactionUpsertBulk) ClearRequestedGroupID() *OAuthAuthorizeTransactionUpsertBulk {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.ClearRequestedGroupID()
	})
}

// SetDeviceID sets the "device_id" field.
func (u *OAuthAuthorizeTransactionUpsertBulk) SetDeviceID(v string) *OAuthAuthorizeTransactionUpsertBulk {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.SetDeviceID(v)
	})
}

// UpdateDeviceID sets the "device_id" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsertBulk) UpdateDeviceID() *OAuthAuthorizeTransactionUpsertBulk {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.UpdateDeviceID()
	})
}

// ClearDeviceID clears the value of the "device_id" field.
func (u *OAuthAuthorizeTransactionUpsertBulk) ClearDeviceID() *OAuthAuthorizeTransactionUpsertBulk {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.ClearDeviceID()
	})
}

// SetDeviceName sets the "device_name" field.
func (u *OAuthAuthorizeTransactionUpsertBulk) SetDeviceName(v string) *OAuthAuthorizeTransactionUpsertBulk {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.SetDeviceName(v)
	})
}

// UpdateDeviceName sets the "device_name" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsertBulk) UpdateDeviceName() *OAuthAuthorizeTransactionUpsertBulk {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.UpdateDeviceName()
	})
}

// ClearDeviceName clears the value of the "device_name" field.
func (u *OAuthAuthorizeTransactionUpsertBulk) ClearDeviceName() *OAuthAuthorizeTransactionUpsertBulk {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.ClearDeviceName()
	})
}

// SetConsumedAt sets the "consumed_at" field.
func (u *OAuthAuthorizeTransactionUpsertBulk) SetConsumedAt(v time.Time) *OAuthAuthorizeTransactionUpsertBulk {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.SetConsumedAt(v)
	})
}

// UpdateConsumedAt sets the "consumed_at" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsertBulk) UpdateConsumedAt() *OAuthAuthorizeTransactionUpsertBulk {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.UpdateConsumedAt()
	})
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (u *OAuthAuthorizeTransactionUpsertBulk) ClearConsumedAt() *OAuthAuthorizeTransactionUpsertBulk {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.ClearConsumedAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *OAuthAuthorizeTransactionUpsertBulk) SetExpiresAt(v time.Time) *OAuthAuthorizeTransactionUpsertBulk {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsertBulk) UpdateExpiresAt() *OAuthAuthorizeTransactionUpsertBulk {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetCreatedIP sets the "created_ip" field.
func (u *OAuthAuthorizeTransactionUpsertBulk) SetCreatedIP(v string) *OAuthAuthorizeTransactionUpsertBulk {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.SetCreatedIP(v)
	})
}

// UpdateCreatedIP sets the "created_ip" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsertBulk) UpdateCreatedIP() *OAuthAuthorizeTransactionUpsertBulk {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.UpdateCreatedIP()
	})
}

// ClearCreatedIP clears the value of the "created_ip" field.
func (u *OAuthAuthorizeTransactionUpsertBulk) ClearCreatedIP() *OAuthAuthorizeTransactionUpsertBulk {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.ClearCreatedIP()
	})
}

// SetCreatedUserAgent sets the "created_user_agent" field.
func (u *OAuthAuthorizeTransactionUpsertBulk) SetCreatedUserAgent(v string) *OAuthAuthorizeTransactionUpsertBulk {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.SetCreatedUserAgent(v)
	})
}

// UpdateCreatedUserAgent sets the "created_user_agent" field to the value that was provided on create.
func (u *OAuthAuthorizeTransactionUpsertBulk) UpdateCreatedUserAgent() *OAuthAuthorizeTransactionUpsertBulk {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.UpdateCreatedUserAgent()
	})
}

// ClearCreatedUserAgent clears the value of the "created_user_agent" field.
func (u *OAuthAuthorizeTransactionUpsertBulk) ClearCreatedUserAgent() *OAuthAuthorizeTransactionUpsertBulk {
	return u.Update(func(s *OAuthAuthorizeTransactionUpsert) {
		s.ClearCreatedUserAgent()
	})
}

// Exec executes the query.
func (u *OAuthAuthorizeTransactionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OAuthAuthorizeTransactionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OAuthAuthorizeTransactionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OAuthAuthorizeTransactionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
