// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/oauthrefreshtoken"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// OAuthRefreshTokenUpdate is the builder for updating OAuthRefreshToken entities.
type OAuthRefreshTokenUpdate struct {
	config
	hooks    []Hook
	mutation *OAuthRefreshTokenMutation
}

// Where appends a list predicates to the OAuthRefreshTokenUpdate builder.
func (_u *OAuthRefreshTokenUpdate) Where(ps ...predicate.OAuthRefreshToken) *OAuthRefreshTokenUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OAuthRefreshTokenUpdate) SetUpdatedAt(v time.Time) *OAuthRefreshTokenUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *OAuthRefreshTokenUpdate) SetTokenHash(v string) *OAuthRefreshTokenUpdate {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_u *OAuthRefreshTokenUpdate) SetNillableTokenHash(v *string) *OAuthRefreshTokenUpdate {
	if v != nil {
		_u.SetTokenHash(*v)
	}
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *OAuthRefreshTokenUpdate) SetClientID(v string) *OAuthRefreshTokenUpdate {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OAuthRefreshTokenUpdate) SetNillableClientID(v *string) *OAuthRefreshTokenUpdate {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OAuthRefreshTokenUpdate) SetUserID(v int64) *OAuthRefreshTokenUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OAuthRefreshTokenUpdate) SetNillableUserID(v *int64) *OAuthRefreshTokenUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *OAuthRefreshTokenUpdate) AddUserID(v int64) *OAuthRefreshTokenUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *OAuthRefreshTokenUpdate) SetAPIKeyID(v int64) *OAuthRefreshTokenUpdate {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *OAuthRefreshTokenUpdate) SetNillableAPIKeyID(v *int64) *OAuthRefreshTokenUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *OAuthRefreshTokenUpdate) AddAPIKeyID(v int64) *OAuthRefreshTokenUpdate {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *OAuthRefreshTokenUpdate) SetScopes(v []string) *OAuthRefreshTokenUpdate {
	_u.mutation.SetScopes(v)
	return _u
}

// AppendScopes appends value to the "scopes" field.
func (_u *OAuthRefreshTokenUpdate) AppendScopes(v []string) *OAuthRefreshTokenUpdate {
	_u.mutation.AppendScopes(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *OAuthRefreshTokenUpdate) SetExpiresAt(v time.Time) *OAuthRefreshTokenUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *OAuthRefreshTokenUpdate) SetNillableExpiresAt(v *time.Time) *OAuthRefreshTokenUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *OAuthRefreshTokenUpdate) SetRevokedAt(v time.Time) *OAuthRefreshTokenUpdate {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *OAuthRefreshTokenUpdate) SetNillableRevokedAt(v *time.Time) *OAuthRefreshTokenUpdate {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *OAuthRefreshTokenUpdate) ClearRevokedAt() *OAuthRefreshTokenUpdate {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetRotatedToHash sets the "rotated_to_hash" field.
func (_u *OAuthRefreshTokenUpdate) SetRotatedToHash(v string) *OAuthRefreshTokenUpdate {
	_u.mutation.SetRotatedToHash(v)
	return _u
}

// SetNillableRotatedToHash sets the "rotated_to_hash" field if the given value is not nil.
func (_u *OAuthRefreshTokenUpdate) SetNillableRotatedToHash(v *string) *OAuthRefreshTokenUpdate {
	if v != nil {
		_u.SetRotatedToHash(*v)
	}
	return _u
}

// ClearRotatedToHash clears the value of the "rotated_to_hash" field.
func (_u *OAuthRefreshTokenUpdate) ClearRotatedToHash() *OAuthRefreshTokenUpdate {
	_u.mutation.ClearRotatedToHash()
	return _u
}

// Mutation returns the OAuthRefreshTokenMutation object of the builder.
func (_u *OAuthRefreshTokenUpdate) Mutation() *OAuthRefreshTokenMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OAuthRefreshTokenUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthRefreshTokenUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OAuthRefreshTokenUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthRefreshTokenUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OAuthRefreshTokenUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := oauthrefreshtoken.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthRefreshTokenUpdate) check() error {
	if v, ok := _u.mutation.TokenHash(); ok {
		if err := oauthrefreshtoken.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "OAuthRefreshToken.token_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientID(); ok {
		if err := oauthrefreshtoken.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "OAuthRefreshToken.client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RotatedToHash(); ok {
		if err := oauthrefreshtoken.RotatedToHashValidator(v); err != nil {
			return &ValidationError{Name: "rotated_to_hash", err: fmt.Errorf(`ent: validator failed for field "OAuthRefreshToken.rotated_to_hash": %w`, err)}
		}
	}
	return nil
}

func (_u *OAuthRefreshTokenUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthrefreshtoken.Table, oauthrefreshtoken.Columns, sqlgraph.NewFieldSpec(oauthrefreshtoken.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthrefreshtoken.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(oauthrefreshtoken.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(oauthrefreshtoken.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(oauthrefreshtoken.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(oauthrefreshtoken.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(oauthrefreshtoken.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(oauthrefreshtoken.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(oauthrefreshtoken.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthrefreshtoken.FieldScopes, value)
		})
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthrefreshtoken.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(oauthrefreshtoken.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(oauthrefreshtoken.FieldRevokedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RotatedToHash(); ok {
		_spec.SetField(oauthrefreshtoken.FieldRotatedToHash, field.TypeString, value)
	}
	if _u.mutation.RotatedToHashCleared() {
		_spec.ClearField(oauthrefreshtoken.FieldRotatedToHash, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthrefreshtoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OAuthRefreshTokenUpdateOne is the builder for updating a single OAuthRefreshToken entity.
type OAuthRefreshTokenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OAuthRefreshTokenMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OAuthRefreshTokenUpdateOne) SetUpdatedAt(v time.Time) *OAuthRefreshTokenUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *OAuthRefreshTokenUpdateOne) SetTokenHash(v string) *OAuthRefreshTokenUpdateOne {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_u *OAuthRefreshTokenUpdateOne) SetNillableTokenHash(v *string) *OAuthRefreshTokenUpdateOne {
	if v != nil {
		_u.SetTokenHash(*v)
	}
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *OAuthRefreshTokenUpdateOne) SetClientID(v string) *OAuthRefreshTokenUpdateOne {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OAuthRefreshTokenUpdateOne) SetNillableClientID(v *string) *OAuthRefreshTokenUpdateOne {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OAuthRefreshTokenUpdateOne) SetUserID(v int64) *OAuthRefreshTokenUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OAuthRefreshTokenUpdateOne) SetNillableUserID(v *int64) *OAuthRefreshTokenUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *OAuthRefreshTokenUpdateOne) AddUserID(v int64) *OAuthRefreshTokenUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *OAuthRefreshTokenUpdateOne) SetAPIKeyID(v int64) *OAuthRefreshTokenUpdateOne {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *OAuthRefreshTokenUpdateOne) SetNillableAPIKeyID(v *int64) *OAuthRefreshTokenUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *OAuthRefreshTokenUpdateOne) AddAPIKeyID(v int64) *OAuthRefreshTokenUpdateOne {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *OAuthRefreshTokenUpdateOne) SetScopes(v []string) *OAuthRefreshTokenUpdateOne {
	_u.mutation.SetScopes(v)
	return _u
}

// AppendScopes appends value to the "scopes" field.
func (_u *OAuthRefreshTokenUpdateOne) AppendScopes(v []string) *OAuthRefreshTokenUpdateOne {
	_u.mutation.AppendScopes(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *OAuthRefreshTokenUpdateOne) SetExpiresAt(v time.Time) *OAuthRefreshTokenUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *OAuthRefreshTokenUpdateOne) SetNillableExpiresAt(v *time.Time) *OAuthRefreshTokenUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *OAuthRefreshTokenUpdateOne) SetRevokedAt(v time.Time) *OAuthRefreshTokenUpdateOne {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *OAuthRefreshTokenUpdateOne) SetNillableRevokedAt(v *time.Time) *OAuthRefreshTokenUpdateOne {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *OAuthRefreshTokenUpdateOne) ClearRevokedAt() *OAuthRefreshTokenUpdateOne {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetRotatedToHash sets the "rotated_to_hash" field.
func (_u *OAuthRefreshTokenUpdateOne) SetRotatedToHash(v string) *OAuthRefreshTokenUpdateOne {
	_u.mutation.SetRotatedToHash(v)
	return _u
}

// SetNillableRotatedToHash sets the "rotated_to_hash" field if the given value is not nil.
func (_u *OAuthRefreshTokenUpdateOne) SetNillableRotatedToHash(v *string) *OAuthRefreshTokenUpdateOne {
	if v != nil {
		_u.SetRotatedToHash(*v)
	}
	return _u
}

// ClearRotatedToHash clears the value of the "rotated_to_hash" field.
func (_u *OAuthRefreshTokenUpdateOne) ClearRotatedToHash() *OAuthRefreshTokenUpdateOne {
	_u.mutation.ClearRotatedToHash()
	return _u
}

// Mutation returns the OAuthRefreshTokenMutation object of the builder.
func (_u *OAuthRefreshTokenUpdateOne) Mutation() *OAuthRefreshTokenMutation {
	return _u.mutation
}

// Where appends a list predicates to the OAuthRefreshTokenUpdate builder.
func (_u *OAuthRefreshTokenUpdateOne) Where(ps ...predicate.OAuthRefreshToken) *OAuthRefreshTokenUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OAuthRefreshTokenUpdateOne) Select(field string, fields ...string) *OAuthRefreshTokenUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OAuthRefreshToken entity.
func (_u *OAuthRefreshTokenUpdateOne) Save(ctx context.Context) (*OAuthRefreshToken, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthRefreshTokenUpdateOne) SaveX(ctx context.Context) *OAuthRefreshToken {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OAuthRefreshTokenUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthRefreshTokenUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OAuthRefreshTokenUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := oauthrefreshtoken.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthRefreshTokenUpdateOne) check() error {
	if v, ok := _u.mutation.TokenHash(); ok {
		if err := oauthrefreshtoken.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "OAuthRefreshToken.token_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientID(); ok {
		if err := oauthrefreshtoken.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "OAuthRefreshToken.client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RotatedToHash(); ok {
		if err := oauthrefreshtoken.RotatedToHashValidator(v); err != nil {
			return &ValidationError{Name: "rotated_to_hash", err: fmt.Errorf(`ent: validator failed for field "OAuthRefreshToken.rotated_to_hash": %w`, err)}
		}
	}
	return nil
}

func (_u *OAuthRefreshTokenUpdateOne) sqlSave(ctx context.Context) (_node *OAuthRefreshToken, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthrefreshtoken.Table, oauthrefreshtoken.Columns, sqlgraph.NewFieldSpec(oauthrefreshtoken.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OAuthRefreshToken.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauthrefreshtoken.FieldID)
		for _, f := range fields {
			if !oauthrefreshtoken.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != oauthrefreshtoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthrefreshtoken.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(oauthrefreshtoken.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(oauthrefreshtoken.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(oauthrefreshtoken.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(oauthrefreshtoken.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(oauthrefreshtoken.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(oauthrefreshtoken.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(oauthrefreshtoken.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthrefreshtoken.FieldScopes, value)
		})
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthrefreshtoken.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(oauthrefreshtoken.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(oauthrefreshtoken.FieldRevokedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RotatedToHash(); ok {
		_spec.SetField(oauthrefreshtoken.FieldRotatedToHash, field.TypeString, value)
	}
	if _u.mutation.RotatedToHashCleared() {
		_spec.ClearField(oauthrefreshtoken.FieldRotatedToHash, field.TypeString)
	}
	_node = &OAuthRefreshToken{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthrefreshtoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
