// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/oauthdevicecode"
)

// OAuthDeviceCodeCreate is the builder for creating a OAuthDeviceCode entity.
type OAuthDeviceCodeCreate struct {
	config
	mutation *OAuthDeviceCodeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *OAuthDeviceCodeCreate) SetCreatedAt(v time.Time) *OAuthDeviceCodeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OAuthDeviceCodeCreate) SetNillableCreatedAt(v *time.Time) *OAuthDeviceCodeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OAuthDeviceCodeCreate) SetUpdatedAt(v time.Time) *OAuthDeviceCodeCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OAuthDeviceCodeCreate) SetNillableUpdatedAt(v *time.Time) *OAuthDeviceCodeCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeviceCodeHash sets the "device_code_hash" field.
func (_c *OAuthDeviceCodeCreate) SetDeviceCodeHash(v string) *OAuthDeviceCodeCreate {
	_c.mutation.SetDeviceCodeHash(v)
	return _c
}

// SetUserCodeHash sets the "user_code_hash" field.
func (_c *OAuthDeviceCodeCreate) SetUserCodeHash(v string) *OAuthDeviceCodeCreate {
	_c.mutation.SetUserCodeHash(v)
	return _c
}

// SetClientID sets the "client_id" field.
func (_c *OAuthDeviceCodeCreate) SetClientID(v string) *OAuthDeviceCodeCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetScopes sets the "scopes" field.
func (_c *OAuthDeviceCodeCreate) SetScopes(v []string) *OAuthDeviceCodeCreate {
	_c.mutation.SetScopes(v)
	return _c
}

// SetGrantID sets the "grant_id" field.
func (_c *OAuthDeviceCodeCreate) SetGrantID(v string) *OAuthDeviceCodeCreate {
	_c.mutation.SetGrantID(v)
	return _c
}

// SetNillableGrantID sets the "grant_id" field if the given value is not nil.
func (_c *OAuthDeviceCodeCreate) SetNillableGrantID(v *string) *OAuthDeviceCodeCreate {
	if v != nil {
		_c.SetGrantID(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *OAuthDeviceCodeCreate) SetGroupID(v int64) *OAuthDeviceCodeCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_c *OAuthDeviceCodeCreate) SetNillableGroupID(v *int64) *OAuthDeviceCodeCreate {
	if v != nil {
		_c.SetGroupID(*v)
	}
	return _c
}

// SetDeviceID sets the "device_id" field.
func (_c *OAuthDeviceCodeCreate) SetDeviceID(v string) *OAuthDeviceCodeCreate {
	_c.mutation.SetDeviceID(v)
	return _c
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_c *OAuthDeviceCodeCreate) SetNillableDeviceID(v *string) *OAuthDeviceCodeCreate {
	if v != nil {
		_c.SetDeviceID(*v)
	}
	return _c
}

// SetDeviceName sets the "device_name" field.
func (_c *OAuthDeviceCodeCreate) SetDeviceName(v string) *OAuthDeviceCodeCreate {
	_c.mutation.SetDeviceName(v)
	return _c
}

// SetNillableDeviceName sets the "device_name" field if the given value is not nil.
func (_c *OAuthDeviceCodeCreate) SetNillableDeviceName(v *string) *OAuthDeviceCodeCreate {
	if v != nil {
		_c.SetDeviceName(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *OAuthDeviceCodeCreate) SetStatus(v string) *OAuthDeviceCodeCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *OAuthDeviceCodeCreate) SetNillableStatus(v *string) *OAuthDeviceCodeCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetIntervalSeconds sets the "interval_seconds" field.
func (_c *OAuthDeviceCodeCreate) SetIntervalSeconds(v int) *OAuthDeviceCodeCreate {
	_c.mutation.SetIntervalSeconds(v)
	return _c
}

// SetNillableIntervalSeconds sets the "interval_seconds" field if the given value is not nil.
func (_c *OAuthDeviceCodeCreate) SetNillableIntervalSeconds(v *int) *OAuthDeviceCodeCreate {
	if v != nil {
		_c.SetIntervalSeconds(*v)
	}
	return _c
}

// SetPollCount sets the "poll_count" field.
func (_c *OAuthDeviceCodeCreate) SetPollCount(v int) *OAuthDeviceCodeCreate {
	_c.mutation.SetPollCount(v)
	return _c
}

// SetNillablePollCount sets the "poll_count" field if the given value is not nil.
func (_c *OAuthDeviceCodeCreate) SetNillablePollCount(v *int) *OAuthDeviceCodeCreate {
	if v != nil {
		_c.SetPollCount(*v)
	}
	return _c
}

// SetLastPollAt sets the "last_poll_at" field.
func (_c *OAuthDeviceCodeCreate) SetLastPollAt(v time.Time) *OAuthDeviceCodeCreate {
	_c.mutation.SetLastPollAt(v)
	return _c
}

// SetNillableLastPollAt sets the "last_poll_at" field if the given value is not nil.
func (_c *OAuthDeviceCodeCreate) SetNillableLastPollAt(v *time.Time) *OAuthDeviceCodeCreate {
	if v != nil {
		_c.SetLastPollAt(*v)
	}
	return _c
}

// SetSlowDownCount sets the "slow_down_count" field.
func (_c *OAuthDeviceCodeCreate) SetSlowDownCount(v int) *OAuthDeviceCodeCreate {
	_c.mutation.SetSlowDownCount(v)
	return _c
}

// SetNillableSlowDownCount sets the "slow_down_count" field if the given value is not nil.
func (_c *OAuthDeviceCodeCreate) SetNillableSlowDownCount(v *int) *OAuthDeviceCodeCreate {
	if v != nil {
		_c.SetSlowDownCount(*v)
	}
	return _c
}

// SetFailedUserCodeAttempts sets the "failed_user_code_attempts" field.
func (_c *OAuthDeviceCodeCreate) SetFailedUserCodeAttempts(v int) *OAuthDeviceCodeCreate {
	_c.mutation.SetFailedUserCodeAttempts(v)
	return _c
}

// SetNillableFailedUserCodeAttempts sets the "failed_user_code_attempts" field if the given value is not nil.
func (_c *OAuthDeviceCodeCreate) SetNillableFailedUserCodeAttempts(v *int) *OAuthDeviceCodeCreate {
	if v != nil {
		_c.SetFailedUserCodeAttempts(*v)
	}
	return _c
}

// SetApprovedByUserID sets the "approved_by_user_id" field.
func (_c *OAuthDeviceCodeCreate) SetApprovedByUserID(v int64) *OAuthDeviceCodeCreate {
	_c.mutation.SetApprovedByUserID(v)
	return _c
}

// SetNillableApprovedByUserID sets the "approved_by_user_id" field if the given value is not nil.
func (_c *OAuthDeviceCodeCreate) SetNillableApprovedByUserID(v *int64) *OAuthDeviceCodeCreate {
	if v != nil {
		_c.SetApprovedByUserID(*v)
	}
	return _c
}

// SetApprovedAt sets the "approved_at" field.
func (_c *OAuthDeviceCodeCreate) SetApprovedAt(v time.Time) *OAuthDeviceCodeCreate {
	_c.mutation.SetApprovedAt(v)
	return _c
}

// SetNillableApprovedAt sets the "approved_at" field if the given value is not nil.
func (_c *OAuthDeviceCodeCreate) SetNillableApprovedAt(v *time.Time) *OAuthDeviceCodeCreate {
	if v != nil {
		_c.SetApprovedAt(*v)
	}
	return _c
}

// SetDeniedAt sets the "denied_at" field.
func (_c *OAuthDeviceCodeCreate) SetDeniedAt(v time.Time) *OAuthDeviceCodeCreate {
	_c.mutation.SetDeniedAt(v)
	return _c
}

// SetNillableDeniedAt sets the "denied_at" field if the given value is not nil.
func (_c *OAuthDeviceCodeCreate) SetNillableDeniedAt(v *time.Time) *OAuthDeviceCodeCreate {
	if v != nil {
		_c.SetDeniedAt(*v)
	}
	return _c
}

// SetConsumedAt sets the "consumed_at" field.
func (_c *OAuthDeviceCodeCreate) SetConsumedAt(v time.Time) *OAuthDeviceCodeCreate {
	_c.mutation.SetConsumedAt(v)
	return _c
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_c *OAuthDeviceCodeCreate) SetNillableConsumedAt(v *time.Time) *OAuthDeviceCodeCreate {
	if v != nil {
		_c.SetConsumedAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *OAuthDeviceCodeCreate) SetExpiresAt(v time.Time) *OAuthDeviceCodeCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetCreatedIP sets the "created_ip" field.
func (_c *OAuthDeviceCodeCreate) SetCreatedIP(v string) *OAuthDeviceCodeCreate {
	_c.mutation.SetCreatedIP(v)
	return _c
}

// SetNillableCreatedIP sets the "created_ip" field if the given value is not nil.
func (_c *OAuthDeviceCodeCreate) SetNillableCreatedIP(v *string) *OAuthDeviceCodeCreate {
	if v != nil {
		_c.SetCreatedIP(*v)
	}
	return _c
}

// SetCreatedUserAgent sets the "created_user_agent" field.
func (_c *OAuthDeviceCodeCreate) SetCreatedUserAgent(v string) *OAuthDeviceCodeCreate {
	_c.mutation.SetCreatedUserAgent(v)
	return _c
}

// SetNillableCreatedUserAgent sets the "created_user_agent" field if the given value is not nil.
func (_c *OAuthDeviceCodeCreate) SetNillableCreatedUserAgent(v *string) *OAuthDeviceCodeCreate {
	if v != nil {
		_c.SetCreatedUserAgent(*v)
	}
	return _c
}

// Mutation returns the OAuthDeviceCodeMutation object of the builder.
func (_c *OAuthDeviceCodeCreate) Mutation() *OAuthDeviceCodeMutation {
	return _c.mutation
}

// Save creates the OAuthDeviceCode in the database.
func (_c *OAuthDeviceCodeCreate) Save(ctx context.Context) (*OAuthDeviceCode, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OAuthDeviceCodeCreate) SaveX(ctx context.Context) *OAuthDeviceCode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthDeviceCodeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthDeviceCodeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OAuthDeviceCodeCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := oauthdevicecode.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := oauthdevicecode.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Scopes(); !ok {
		v := oauthdevicecode.DefaultScopes
		_c.mutation.SetScopes(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := oauthdevicecode.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.IntervalSeconds(); !ok {
		v := oauthdevicecode.DefaultIntervalSeconds
		_c.mutation.SetIntervalSeconds(v)
	}
	if _, ok := _c.mutation.PollCount(); !ok {
		v := oauthdevicecode.DefaultPollCount
		_c.mutation.SetPollCount(v)
	}
	if _, ok := _c.mutation.SlowDownCount(); !ok {
		v := oauthdevicecode.DefaultSlowDownCount
		_c.mutation.SetSlowDownCount(v)
	}
	if _, ok := _c.mutation.FailedUserCodeAttempts(); !ok {
		v := oauthdevicecode.DefaultFailedUserCodeAttempts
		_c.mutation.SetFailedUserCodeAttempts(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OAuthDeviceCodeCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OAuthDeviceCode.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OAuthDeviceCode.updated_at"`)}
	}
	if _, ok := _c.mutation.DeviceCodeHash(); !ok {
		return &ValidationError{Name: "device_code_hash", err: errors.New(`ent: missing required field "OAuthDeviceCode.device_code_hash"`)}
	}
	if v, ok := _c.mutation.DeviceCodeHash(); ok {
		if err := oauthdevicecode.DeviceCodeHashValidator(v); err != nil {
			return &ValidationError{Name: "device_code_hash", err: fmt.Errorf(`ent: validator failed for field "OAuthDeviceCode.device_code_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserCodeHash(); !ok {
		return &ValidationError{Name: "user_code_hash", err: errors.New(`ent: missing required field "OAuthDeviceCode.user_code_hash"`)}
	}
	if v, ok := _c.mutation.UserCodeHash(); ok {
		if err := oauthdevicecode.UserCodeHashValidator(v); err != nil {
			return &ValidationError{Name: "user_code_hash", err: fmt.Errorf(`ent: validator failed for field "OAuthDeviceCode.user_code_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`ent: missing required field "OAuthDeviceCode.client_id"`)}
	}
	if v, ok := _c.mutation.ClientID(); ok {
		if err := oauthdevicecode.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "OAuthDeviceCode.client_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Scopes(); !ok {
		return &ValidationError{Name: "scopes", err: errors.New(`ent: missing required field "OAuthDeviceCode.scopes"`)}
	}
	if v, ok := _c.mutation.GrantID(); ok {
		if err := oauthdevicecode.GrantIDValidator(v); err != nil {
			return &ValidationError{Name: "grant_id", err: fmt.Errorf(`ent: validator failed for field "OAuthDeviceCode.grant_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.DeviceID(); ok {
		if err := oauthdevicecode.DeviceIDValidator(v); err != nil {
			return &ValidationError{Name: "device_id", err: fmt.Errorf(`ent: validator failed for field "OAuthDeviceCode.device_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.DeviceName(); ok {
		if err := oauthdevicecode.DeviceNameValidator(v); err != nil {
			return &ValidationError{Name: "device_name", err: fmt.Errorf(`ent: validator failed for field "OAuthDeviceCode.device_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "OAuthDeviceCode.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := oauthdevicecode.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OAuthDeviceCode.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IntervalSeconds(); !ok {
		return &ValidationError{Name: "interval_seconds", err: errors.New(`ent: missing required field "OAuthDeviceCode.interval_seconds"`)}
	}
	if _, ok := _c.mutation.PollCount(); !ok {
		return &ValidationError{Name: "poll_count", err: errors.New(`ent: missing required field "OAuthDeviceCode.poll_count"`)}
	}
	if _, ok := _c.mutation.SlowDownCount(); !ok {
		return &ValidationError{Name: "slow_down_count", err: errors.New(`ent: missing required field "OAuthDeviceCode.slow_down_count"`)}
	}
	if _, ok := _c.mutation.FailedUserCodeAttempts(); !ok {
		return &ValidationError{Name: "failed_user_code_attempts", err: errors.New(`ent: missing required field "OAuthDeviceCode.failed_user_code_attempts"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "OAuthDeviceCode.expires_at"`)}
	}
	if v, ok := _c.mutation.CreatedIP(); ok {
		if err := oauthdevicecode.CreatedIPValidator(v); err != nil {
			return &ValidationError{Name: "created_ip", err: fmt.Errorf(`ent: validator failed for field "OAuthDeviceCode.created_ip": %w`, err)}
		}
	}
	return nil
}

func (_c *OAuthDeviceCodeCreate) sqlSave(ctx context.Context) (*OAuthDeviceCode, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OAuthDeviceCodeCreate) createSpec() (*OAuthDeviceCode, *sqlgraph.CreateSpec) {
	var (
		_node = &OAuthDeviceCode{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(oauthdevicecode.Table, sqlgraph.NewFieldSpec(oauthdevicecode.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(oauthdevicecode.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthdevicecode.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeviceCodeHash(); ok {
		_spec.SetField(oauthdevicecode.FieldDeviceCodeHash, field.TypeString, value)
		_node.DeviceCodeHash = value
	}
	if value, ok := _c.mutation.UserCodeHash(); ok {
		_spec.SetField(oauthdevicecode.FieldUserCodeHash, field.TypeString, value)
		_node.UserCodeHash = value
	}
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(oauthdevicecode.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := _c.mutation.Scopes(); ok {
		_spec.SetField(oauthdevicecode.FieldScopes, field.TypeJSON, value)
		_node.Scopes = value
	}
	if value, ok := _c.mutation.GrantID(); ok {
		_spec.SetField(oauthdevicecode.FieldGrantID, field.TypeString, value)
		_node.GrantID = &value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(oauthdevicecode.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = &value
	}
	if value, ok := _c.mutation.DeviceID(); ok {
		_spec.SetField(oauthdevicecode.FieldDeviceID, field.TypeString, value)
		_node.DeviceID = &value
	}
	if value, ok := _c.mutation.DeviceName(); ok {
		_spec.SetField(oauthdevicecode.FieldDeviceName, field.TypeString, value)
		_node.DeviceName = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(oauthdevicecode.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.IntervalSeconds(); ok {
		_spec.SetField(oauthdevicecode.FieldIntervalSeconds, field.TypeInt, value)
		_node.IntervalSeconds = value
	}
	if value, ok := _c.mutation.PollCount(); ok {
		_spec.SetField(oauthdevicecode.FieldPollCount, field.TypeInt, value)
		_node.PollCount = value
	}
	if value, ok := _c.mutation.LastPollAt(); ok {
		_spec.SetField(oauthdevicecode.FieldLastPollAt, field.TypeTime, value)
		_node.LastPollAt = &value
	}
	if value, ok := _c.mutation.SlowDownCount(); ok {
		_spec.SetField(oauthdevicecode.FieldSlowDownCount, field.TypeInt, value)
		_node.SlowDownCount = value
	}
	if value, ok := _c.mutation.FailedUserCodeAttempts(); ok {
		_spec.SetField(oauthdevicecode.FieldFailedUserCodeAttempts, field.TypeInt, value)
		_node.FailedUserCodeAttempts = value
	}
	if value, ok := _c.mutation.ApprovedByUserID(); ok {
		_spec.SetField(oauthdevicecode.FieldApprovedByUserID, field.TypeInt64, value)
		_node.ApprovedByUserID = &value
	}
	if value, ok := _c.mutation.ApprovedAt(); ok {
		_spec.SetField(oauthdevicecode.FieldApprovedAt, field.TypeTime, value)
		_node.ApprovedAt = &value
	}
	if value, ok := _c.mutation.DeniedAt(); ok {
		_spec.SetField(oauthdevicecode.FieldDeniedAt, field.TypeTime, value)
		_node.DeniedAt = &value
	}
	if value, ok := _c.mutation.ConsumedAt(); ok {
		_spec.SetField(oauthdevicecode.FieldConsumedAt, field.TypeTime, value)
		_node.ConsumedAt = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthdevicecode.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.CreatedIP(); ok {
		_spec.SetField(oauthdevicecode.FieldCreatedIP, field.TypeString, value)
		_node.CreatedIP = &value
	}
	if value, ok := _c.mutation.CreatedUserAgent(); ok {
		_spec.SetField(oauthdevicecode.FieldCreatedUserAgent, field.TypeString, value)
		_node.CreatedUserAgent = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OAuthDeviceCode.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OAuthDeviceCodeUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OAuthDeviceCodeCreate) OnConflict(opts ...sql.ConflictOption) *OAuthDeviceCodeUpsertOne {
	_c.conflict = opts
	return &OAuthDeviceCodeUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OAuthDeviceCode.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OAuthDeviceCodeCreate) OnConflictColumns(columns ...string) *OAuthDeviceCodeUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OAuthDeviceCodeUpsertOne{
		create: _c,
	}
}

type (
	// OAuthDeviceCodeUpsertOne is the builder for "upsert"-ing
	//  one OAuthDeviceCode node.
	OAuthDeviceCodeUpsertOne struct {
		create *OAuthDeviceCodeCreate
	}

	// OAuthDeviceCodeUpsert is the "OnConflict" setter.
	OAuthDeviceCodeUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *OAuthDeviceCodeUpsert) SetUpdatedAt(v time.Time) *OAuthDeviceCodeUpsert {
	u.Set(oauthdevicecode.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsert) UpdateUpdatedAt() *OAuthDeviceCodeUpsert {
	u.SetExcluded(oauthdevicecode.FieldUpdatedAt)
	return u
}

// SetDeviceCodeHash sets the "device_code_hash" field.
func (u *OAuthDeviceCodeUpsert) SetDeviceCodeHash(v string) *OAuthDeviceCodeUpsert {
	u.Set(oauthdevicecode.FieldDeviceCodeHash, v)
	return u
}

// UpdateDeviceCodeHash sets the "device_code_hash" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsert) UpdateDeviceCodeHash() *OAuthDeviceCodeUpsert {
	u.SetExcluded(oauthdevicecode.FieldDeviceCodeHash)
	return u
}

// SetUserCodeHash sets the "user_code_hash" field.
func (u *OAuthDeviceCodeUpsert) SetUserCodeHash(v string) *OAuthDeviceCodeUpsert {
	u.Set(oauthdevicecode.FieldUserCodeHash, v)
	return u
}

// UpdateUserCodeHash sets the "user_code_hash" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsert) UpdateUserCodeHash() *OAuthDeviceCodeUpsert {
	u.SetExcluded(oauthdevicecode.FieldUserCodeHash)
	return u
}

// SetClientID sets the "client_id" field.
func (u *OAuthDeviceCodeUpsert) SetClientID(v string) *OAuthDeviceCodeUpsert {
	u.Set(oauthdevicecode.FieldClientID, v)
	return u
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsert) UpdateClientID() *OAuthDeviceCodeUpsert {
	u.SetExcluded(oauthdevicecode.FieldClientID)
	return u
}

// SetScopes sets the "scopes" field.
func (u *OAuthDeviceCodeUpsert) SetScopes(v []string) *OAuthDeviceCodeUpsert {
	u.Set(oauthdevicecode.FieldScopes, v)
	return u
}

// UpdateScopes sets the "scopes" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsert) UpdateScopes() *OAuthDeviceCodeUpsert {
	u.SetExcluded(oauthdevicecode.FieldScopes)
	return u
}

// SetGrantID sets the "grant_id" field.
func (u *OAuthDeviceCodeUpsert) SetGrantID(v string) *OAuthDeviceCodeUpsert {
	u.Set(oauthdevicecode.FieldGrantID, v)
	return u
}

// UpdateGrantID sets the "grant_id" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsert) UpdateGrantID() *OAuthDeviceCodeUpsert {
	u.SetExcluded(oauthdevicecode.FieldGrantID)
	return u
}

// ClearGrantID clears the value of the "grant_id" field.
func (u *OAuthDeviceCodeUpsert) ClearGrantID() *OAuthDeviceCodeUpsert {
	u.SetNull(oauthdevicecode.FieldGrantID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *OAuthDeviceCodeUpsert) SetGroupID(v int64) *OAuthDeviceCodeUpsert {
	u.Set(oauthdevicecode.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsert) UpdateGroupID() *OAuthDeviceCodeUpsert {
	u.SetExcluded(oauthdevicecode.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *OAuthDeviceCodeUpsert) AddGroupID(v int64) *OAuthDeviceCodeUpsert {
	u.Add(oauthdevicecode.FieldGroupID, v)
	return u
}

// ClearGroupID clears the value of the "group_id" field.
func (u *OAuthDeviceCodeUpsert) ClearGroupID() *OAuthDeviceCodeUpsert {
	u.SetNull(oauthdevicecode.FieldGroupID)
	return u
}

// SetDeviceID sets the "device_id" field.
func (u *OAuthDeviceCodeUpsert) SetDeviceID(v string) *OAuthDeviceCodeUpsert {
	u.Set(oauthdevicecode.FieldDeviceID, v)
	return u
}

// UpdateDeviceID sets the "device_id" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsert) UpdateDeviceID() *OAuthDeviceCodeUpsert {
	u.SetExcluded(oauthdevicecode.FieldDeviceID)
	return u
}

// ClearDeviceID clears the value of the "device_id" field.
func (u *OAuthDeviceCodeUpsert) ClearDeviceID() *OAuthDeviceCodeUpsert {
	u.SetNull(oauthdevicecode.FieldDeviceID)
	return u
}

// SetDeviceName sets the "device_name" field.
func (u *OAuthDeviceCodeUpsert) SetDeviceName(v string) *OAuthDeviceCodeUpsert {
	u.Set(oauthdevicecode.FieldDeviceName, v)
	return u
}

// UpdateDeviceName sets the "device_name" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsert) UpdateDeviceName() *OAuthDeviceCodeUpsert {
	u.SetExcluded(oauthdevicecode.FieldDeviceName)
	return u
}

// ClearDeviceName clears the value of the "device_name" field.
func (u *OAuthDeviceCodeUpsert) ClearDeviceName() *OAuthDeviceCodeUpsert {
	u.SetNull(oauthdevicecode.FieldDeviceName)
	return u
}

// SetStatus sets the "status" field.
func (u *OAuthDeviceCodeUpsert) SetStatus(v string) *OAuthDeviceCodeUpsert {
	u.Set(oauthdevicecode.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsert) UpdateStatus() *OAuthDeviceCodeUpsert {
	u.SetExcluded(oauthdevicecode.FieldStatus)
	return u
}

// SetIntervalSeconds sets the "interval_seconds" field.
func (u *OAuthDeviceCodeUpsert) SetIntervalSeconds(v int) *OAuthDeviceCodeUpsert {
	u.Set(oauthdevicecode.FieldIntervalSeconds, v)
	return u
}

// UpdateIntervalSeconds sets the "interval_seconds" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsert) UpdateIntervalSeconds() *OAuthDeviceCodeUpsert {
	u.SetExcluded(oauthdevicecode.FieldIntervalSeconds)
	return u
}

// AddIntervalSeconds adds v to the "interval_seconds" field.
func (u *OAuthDeviceCodeUpsert) AddIntervalSeconds(v int) *OAuthDeviceCodeUpsert {
	u.Add(oauthdevicecode.FieldIntervalSeconds, v)
	return u
}

// SetPollCount sets the "poll_count" field.
func (u *OAuthDeviceCodeUpsert) SetPollCount(v int) *OAuthDeviceCodeUpsert {
	u.Set(oauthdevicecode.FieldPollCount, v)
	return u
}

// UpdatePollCount sets the "poll_count" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsert) UpdatePollCount() *OAuthDeviceCodeUpsert {
	u.SetExcluded(oauthdevicecode.FieldPollCount)
	return u
}

// AddPollCount adds v to the "poll_count" field.
func (u *OAuthDeviceCodeUpsert) AddPollCount(v int) *OAuthDeviceCodeUpsert {
	u.Add(oauthdevicecode.FieldPollCount, v)
	return u
}

// SetLastPollAt sets the "last_poll_at" field.
func (u *OAuthDeviceCodeUpsert) SetLastPollAt(v time.Time) *OAuthDeviceCodeUpsert {
	u.Set(oauthdevicecode.FieldLastPollAt, v)
	return u
}

// UpdateLastPollAt sets the "last_poll_at" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsert) UpdateLastPollAt() *OAuthDeviceCodeUpsert {
	u.SetExcluded(oauthdevicecode.FieldLastPollAt)
	return u
}

// ClearLastPollAt clears the value of the "last_poll_at" field.
func (u *OAuthDeviceCodeUpsert) ClearLastPollAt() *OAuthDeviceCodeUpsert {
	u.SetNull(oauthdevicecode.FieldLastPollAt)
	return u
}

// SetSlowDownCount sets the "slow_down_count" field.
func (u *OAuthDeviceCodeUpsert) SetSlowDownCount(v int) *OAuthDeviceCodeUpsert {
	u.Set(oauthdevicecode.FieldSlowDownCount, v)
	return u
}

// UpdateSlowDownCount sets the "slow_down_count" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsert) UpdateSlowDownCount() *OAuthDeviceCodeUpsert {
	u.SetExcluded(oauthdevicecode.FieldSlowDownCount)
	return u
}

// AddSlowDownCount adds v to the "slow_down_count" field.
func (u *OAuthDeviceCodeUpsert) AddSlowDownCount(v int) *OAuthDeviceCodeUpsert {
	u.Add(oauthdevicecode.FieldSlowDownCount, v)
	return u
}

// SetFailedUserCodeAttempts sets the "failed_user_code_attempts" field.
func (u *OAuthDeviceCodeUpsert) SetFailedUserCodeAttempts(v int) *OAuthDeviceCodeUpsert {
	u.Set(oauthdevicecode.FieldFailedUserCodeAttempts, v)
	return u
}

// UpdateFailedUserCodeAttempts sets the "failed_user_code_attempts" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsert) UpdateFailedUserCodeAttempts() *OAuthDeviceCodeUpsert {
	u.SetExcluded(oauthdevicecode.FieldFailedUserCodeAttempts)
	return u
}

// AddFailedUserCodeAttempts adds v to the "failed_user_code_attempts" field.
func (u *OAuthDeviceCodeUpsert) AddFailedUserCodeAttempts(v int) *OAuthDeviceCodeUpsert {
	u.Add(oauthdevicecode.FieldFailedUserCodeAttempts, v)
	return u
}

// SetApprovedByUserID sets the "approved_by_user_id" field.
func (u *OAuthDeviceCodeUpsert) SetApprovedByUserID(v int64) *OAuthDeviceCodeUpsert {
	u.Set(oauthdevicecode.FieldApprovedByUserID, v)
	return u
}

// UpdateApprovedByUserID sets the "approved_by_user_id" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsert) UpdateApprovedByUserID() *OAuthDeviceCodeUpsert {
	u.SetExcluded(oauthdevicecode.FieldApprovedByUserID)
	return u
}

// AddApprovedByUserID adds v to the "approved_by_user_id" field.
func (u *OAuthDeviceCodeUpsert) AddApprovedByUserID(v int64) *OAuthDeviceCodeUpsert {
	u.Add(oauthdevicecode.FieldApprovedByUserID, v)
	return u
}

// ClearApprovedByUserID clears the value of the "approved_by_user_id" field.
func (u *OAuthDeviceCodeUpsert) ClearApprovedByUserID() *OAuthDeviceCodeUpsert {
	u.SetNull(oauthdevicecode.FieldApprovedByUserID)
	return u
}

// SetApprovedAt sets the "approved_at" field.
func (u *OAuthDeviceCodeUpsert) SetApprovedAt(v time.Time) *OAuthDeviceCodeUpsert {
	u.Set(oauthdevicecode.FieldApprovedAt, v)
	return u
}

// UpdateApprovedAt sets the "approved_at" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsert) UpdateApprovedAt() *OAuthDeviceCodeUpsert {
	u.SetExcluded(oauthdevicecode.FieldApprovedAt)
	return u
}

// ClearApprovedAt clears the value of the "approved_at" field.
func (u *OAuthDeviceCodeUpsert) ClearApprovedAt() *OAuthDeviceCodeUpsert {
	u.SetNull(oauthdevicecode.FieldApprovedAt)
	return u
}

// SetDeniedAt sets the "denied_at" field.
func (u *OAuthDeviceCodeUpsert) SetDeniedAt(v time.Time) *OAuthDeviceCodeUpsert {
	u.Set(oauthdevicecode.FieldDeniedAt, v)
	return u
}

// UpdateDeniedAt sets the "denied_at" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsert) UpdateDeniedAt() *OAuthDeviceCodeUpsert {
	u.SetExcluded(oauthdevicecode.FieldDeniedAt)
	return u
}

// ClearDeniedAt clears the value of the "denied_at" field.
func (u *OAuthDeviceCodeUpsert) ClearDeniedAt() *OAuthDeviceCodeUpsert {
	u.SetNull(oauthdevicecode.FieldDeniedAt)
	return u
}

// SetConsumedAt sets the "consumed_at" field.
func (u *OAuthDeviceCodeUpsert) SetConsumedAt(v time.Time) *OAuthDeviceCodeUpsert {
	u.Set(oauthdevicecode.FieldConsumedAt, v)
	return u
}

// UpdateConsumedAt sets the "consumed_at" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsert) UpdateConsumedAt() *OAuthDeviceCodeUpsert {
	u.SetExcluded(oauthdevicecode.FieldConsumedAt)
	return u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (u *OAuthDeviceCodeUpsert) ClearConsumedAt() *OAuthDeviceCodeUpsert {
	u.SetNull(oauthdevicecode.FieldConsumedAt)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *OAuthDeviceCodeUpsert) SetExpiresAt(v time.Time) *OAuthDeviceCodeUpsert {
	u.Set(oauthdevicecode.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsert) UpdateExpiresAt() *OAuthDeviceCodeUpsert {
	u.SetExcluded(oauthdevicecode.FieldExpiresAt)
	return u
}

// SetCreatedIP sets the "created_ip" field.
func (u *OAuthDeviceCodeUpsert) SetCreatedIP(v string) *OAuthDeviceCodeUpsert {
	u.Set(oauthdevicecode.FieldCreatedIP, v)
	return u
}

// UpdateCreatedIP sets the "created_ip" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsert) UpdateCreatedIP() *OAuthDeviceCodeUpsert {
	u.SetExcluded(oauthdevicecode.FieldCreatedIP)
	return u
}

// ClearCreatedIP clears the value of the "created_ip" field.
func (u *OAuthDeviceCodeUpsert) ClearCreatedIP() *OAuthDeviceCodeUpsert {
	u.SetNull(oauthdevicecode.FieldCreatedIP)
	return u
}

// SetCreatedUserAgent sets the "created_user_agent" field.
func (u *OAuthDeviceCodeUpsert) SetCreatedUserAgent(v string) *OAuthDeviceCodeUpsert {
	u.Set(oauthdevicecode.FieldCreatedUserAgent, v)
	return u
}

// UpdateCreatedUserAgent sets the "created_user_agent" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsert) UpdateCreatedUserAgent() *OAuthDeviceCodeUpsert {
	u.SetExcluded(oauthdevicecode.FieldCreatedUserAgent)
	return u
}

// ClearCreatedUserAgent clears the value of the "created_user_agent" field.
func (u *OAuthDeviceCodeUpsert) ClearCreatedUserAgent() *OAuthDeviceCodeUpsert {
	u.SetNull(oauthdevicecode.FieldCreatedUserAgent)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.OAuthDeviceCode.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OAuthDeviceCodeUpsertOne) UpdateNewValues() *OAuthDeviceCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(oauthdevicecode.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OAuthDeviceCode.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OAuthDeviceCodeUpsertOne) Ignore() *OAuthDeviceCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OAuthDeviceCodeUpsertOne) DoNothing() *OAuthDeviceCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OAuthDeviceCodeCreate.OnConflict
// documentation for more info.
func (u *OAuthDeviceCodeUpsertOne) Update(set func(*OAuthDeviceCodeUpsert)) *OAuthDeviceCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OAuthDeviceCodeUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OAuthDeviceCodeUpsertOne) SetUpdatedAt(v time.Time) *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsertOne) UpdateUpdatedAt() *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeviceCodeHash sets the "device_code_hash" field.
func (u *OAuthDeviceCodeUpsertOne) SetDeviceCodeHash(v string) *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.SetDeviceCodeHash(v)
	})
}

// UpdateDeviceCodeHash sets the "device_code_hash" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsertOne) UpdateDeviceCodeHash() *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.UpdateDeviceCodeHash()
	})
}

// SetUserCodeHash sets the "user_code_hash" field.
func (u *OAuthDeviceCodeUpsertOne) SetUserCodeHash(v string) *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.SetUserCodeHash(v)
	})
}

// UpdateUserCodeHash sets the "user_code_hash" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsertOne) UpdateUserCodeHash() *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.UpdateUserCodeHash()
	})
}

// SetClientID sets the "client_id" field.
func (u *OAuthDeviceCodeUpsertOne) SetClientID(v string) *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsertOne) UpdateClientID() *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.UpdateClientID()
	})
}

// SetScopes sets the "scopes" field.
func (u *OAuthDeviceCodeUpsertOne) SetScopes(v []string) *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.SetScopes(v)
	})
}

// UpdateScopes sets the "scopes" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsertOne) UpdateScopes() *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.UpdateScopes()
	})
}

// SetGrantID sets the "grant_id" field.
func (u *OAuthDeviceCodeUpsertOne) SetGrantID(v string) *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.SetGrantID(v)
	})
}

// UpdateGrantID sets the "grant_id" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsertOne) UpdateGrantID() *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.UpdateGrantID()
	})
}

// ClearGrantID clears the value of the "grant_id" field.
func (u *OAuthDeviceCodeUpsertOne) ClearGrantID() *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.ClearGrantID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *OAuthDeviceCodeUpsertOne) SetGroupID(v int64) *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *OAuthDeviceCodeUpsertOne) AddGroupID(v int64) *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsertOne) UpdateGroupID() *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *OAuthDeviceCodeUpsertOne) ClearGroupID() *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.ClearGroupID()
	})
}

// SetDeviceID sets the "device_id" field.
func (u *OAuthDeviceCodeUpsertOne) SetDeviceID(v string) *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.SetDeviceID(v)
	})
}

// UpdateDeviceID sets the "device_id" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsertOne) UpdateDeviceID() *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.UpdateDeviceID()
	})
}

// ClearDeviceID clears the value of the "device_id" field.
func (u *OAuthDeviceCodeUpsertOne) ClearDeviceID() *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.ClearDeviceID()
	})
}

// SetDeviceName sets the "device_name" field.
func (u *OAuthDeviceCodeUpsertOne) SetDeviceName(v string) *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.SetDeviceName(v)
	})
}

// UpdateDeviceName sets the "device_name" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsertOne) UpdateDeviceName() *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.UpdateDeviceName()
	})
}

// ClearDeviceName clears the value of the "device_name" field.
func (u *OAuthDeviceCodeUpsertOne) ClearDeviceName() *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.ClearDeviceName()
	})
}

// SetStatus sets the "status" field.
func (u *OAuthDeviceCodeUpsertOne) SetStatus(v string) *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsertOne) UpdateStatus() *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.UpdateStatus()
	})
}

// SetIntervalSeconds sets the "interval_seconds" field.
func (u *OAuthDeviceCodeUpsertOne) SetIntervalSeconds(v int) *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.SetIntervalSeconds(v)
	})
}

// AddIntervalSeconds adds v to the "interval_seconds" field.
func (u *OAuthDeviceCodeUpsertOne) AddIntervalSeconds(v int) *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.AddIntervalSeconds(v)
	})
}

// UpdateIntervalSeconds sets the "interval_seconds" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsertOne) UpdateIntervalSeconds() *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.UpdateIntervalSeconds()
	})
}

// SetPollCount sets the "poll_count" field.
func (u *OAuthDeviceCodeUpsertOne) SetPollCount(v int) *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.SetPollCount(v)
	})
}

// AddPollCount adds v to the "poll_count" field.
func (u *OAuthDeviceCodeUpsertOne) AddPollCount(v int) *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.AddPollCount(v)
	})
}

// UpdatePollCount sets the "poll_count" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsertOne) UpdatePollCount() *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.UpdatePollCount()
	})
}

// SetLastPollAt sets the "last_poll_at" field.
func (u *OAuthDeviceCodeUpsertOne) SetLastPollAt(v time.Time) *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.SetLastPollAt(v)
	})
}

// UpdateLastPollAt sets the "last_poll_at" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsertOne) UpdateLastPollAt() *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.UpdateLastPollAt()
	})
}

// ClearLastPollAt clears the value of the "last_poll_at" field.
func (u *OAuthDeviceCodeUpsertOne) ClearLastPollAt() *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.ClearLastPollAt()
	})
}

// SetSlowDownCount sets the "slow_down_count" field.
func (u *OAuthDeviceCodeUpsertOne) SetSlowDownCount(v int) *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.SetSlowDownCount(v)
	})
}

// AddSlowDownCount adds v to the "slow_down_count" field.
func (u *OAuthDeviceCodeUpsertOne) AddSlowDownCount(v int) *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.AddSlowDownCount(v)
	})
}

// UpdateSlowDownCount sets the "slow_down_count" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsertOne) UpdateSlowDownCount() *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.UpdateSlowDownCount()
	})
}

// SetFailedUserCodeAttempts sets the "failed_user_code_attempts" field.
func (u *OAuthDeviceCodeUpsertOne) SetFailedUserCodeAttempts(v int) *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.SetFailedUserCodeAttempts(v)
	})
}

// AddFailedUserCodeAttempts adds v to the "failed_user_code_attempts" field.
func (u *OAuthDeviceCodeUpsertOne) AddFailedUserCodeAttempts(v int) *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.AddFailedUserCodeAttempts(v)
	})
}

// UpdateFailedUserCodeAttempts sets the "failed_user_code_attempts" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsertOne) UpdateFailedUserCodeAttempts() *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.UpdateFailedUserCodeAttempts()
	})
}

// SetApprovedByUserID sets the "approved_by_user_id" field.
func (u *OAuthDeviceCodeUpsertOne) SetApprovedByUserID(v int64) *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.SetApprovedByUserID(v)
	})
}

// AddApprovedByUserID adds v to the "approved_by_user_id" field.
func (u *OAuthDeviceCodeUpsertOne) AddApprovedByUserID(v int64) *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.AddApprovedByUserID(v)
	})
}

// UpdateApprovedByUserID sets the "approved_by_user_id" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsertOne) UpdateApprovedByUserID() *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.UpdateApprovedByUserID()
	})
}

// ClearApprovedByUserID clears the value of the "approved_by_user_id" field.
func (u *OAuthDeviceCodeUpsertOne) ClearApprovedByUserID() *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.ClearApprovedByUserID()
	})
}

// SetApprovedAt sets the "approved_at" field.
func (u *OAuthDeviceCodeUpsertOne) SetApprovedAt(v time.Time) *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.SetApprovedAt(v)
	})
}

// UpdateApprovedAt sets the "approved_at" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsertOne) UpdateApprovedAt() *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.UpdateApprovedAt()
	})
}

// ClearApprovedAt clears the value of the "approved_at" field.
func (u *OAuthDeviceCodeUpsertOne) ClearApprovedAt() *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.ClearApprovedAt()
	})
}

// SetDeniedAt sets the "denied_at" field.
func (u *OAuthDeviceCodeUpsertOne) SetDeniedAt(v time.Time) *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.SetDeniedAt(v)
	})
}

// UpdateDeniedAt sets the "denied_at" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsertOne) UpdateDeniedAt() *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.UpdateDeniedAt()
	})
}

// ClearDeniedAt clears the value of the "denied_at" field.
func (u *OAuthDeviceCodeUpsertOne) ClearDeniedAt() *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.ClearDeniedAt()
	})
}

// SetConsumedAt sets the "consumed_at" field.
func (u *OAuthDeviceCodeUpsertOne) SetConsumedAt(v time.Time) *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.SetConsumedAt(v)
	})
}

// UpdateConsumedAt sets the "consumed_at" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsertOne) UpdateConsumedAt() *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.UpdateConsumedAt()
	})
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (u *OAuthDeviceCodeUpsertOne) ClearConsumedAt() *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.ClearConsumedAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *OAuthDeviceCodeUpsertOne) SetExpiresAt(v time.Time) *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsertOne) UpdateExpiresAt() *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetCreatedIP sets the "created_ip" field.
func (u *OAuthDeviceCodeUpsertOne) SetCreatedIP(v string) *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.SetCreatedIP(v)
	})
}

// UpdateCreatedIP sets the "created_ip" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsertOne) UpdateCreatedIP() *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.UpdateCreatedIP()
	})
}

// ClearCreatedIP clears the value of the "created_ip" field.
func (u *OAuthDeviceCodeUpsertOne) ClearCreatedIP() *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.ClearCreatedIP()
	})
}

// SetCreatedUserAgent sets the "created_user_agent" field.
func (u *OAuthDeviceCodeUpsertOne) SetCreatedUserAgent(v string) *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.SetCreatedUserAgent(v)
	})
}

// UpdateCreatedUserAgent sets the "created_user_agent" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsertOne) UpdateCreatedUserAgent() *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.UpdateCreatedUserAgent()
	})
}

// ClearCreatedUserAgent clears the value of the "created_user_agent" field.
func (u *OAuthDeviceCodeUpsertOne) ClearCreatedUserAgent() *OAuthDeviceCodeUpsertOne {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.ClearCreatedUserAgent()
	})
}

// Exec executes the query.
func (u *OAuthDeviceCodeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OAuthDeviceCodeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OAuthDeviceCodeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OAuthDeviceCodeUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OAuthDeviceCodeUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OAuthDeviceCodeCreateBulk is the builder for creating many OAuthDeviceCode entities in bulk.
type OAuthDeviceCodeCreateBulk struct {
	config
	err      error
	builders []*OAuthDeviceCodeCreate
	conflict []sql.ConflictOption
}

// Save creates the OAuthDeviceCode entities in the database.
func (_c *OAuthDeviceCodeCreateBulk) Save(ctx context.Context) ([]*OAuthDeviceCode, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OAuthDeviceCode, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OAuthDeviceCodeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OAuthDeviceCodeCreateBulk) SaveX(ctx context.Context) []*OAuthDeviceCode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthDeviceCodeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthDeviceCodeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OAuthDeviceCode.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OAuthDeviceCodeUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OAuthDeviceCodeCreateBulk) OnConflict(opts ...sql.ConflictOption) *OAuthDeviceCodeUpsertBulk {
	_c.conflict = opts
	return &OAuthDeviceCodeUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OAuthDeviceCode.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OAuthDeviceCodeCreateBulk) OnConflictColumns(columns ...string) *OAuthDeviceCodeUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OAuthDeviceCodeUpsertBulk{
		create: _c,
	}
}

// OAuthDeviceCodeUpsertBulk is the builder for "upsert"-ing
// a bulk of OAuthDeviceCode nodes.
type OAuthDeviceCodeUpsertBulk struct {
	create *OAuthDeviceCodeCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OAuthDeviceCode.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OAuthDeviceCodeUpsertBulk) UpdateNewValues() *OAuthDeviceCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(oauthdevicecode.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OAuthDeviceCode.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OAuthDeviceCodeUpsertBulk) Ignore() *OAuthDeviceCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OAuthDeviceCodeUpsertBulk) DoNothing() *OAuthDeviceCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OAuthDeviceCodeCreateBulk.OnConflict
// documentation for more info.
func (u *OAuthDeviceCodeUpsertBulk) Update(set func(*OAuthDeviceCodeUpsert)) *OAuthDeviceCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OAuthDeviceCodeUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OAuthDeviceCodeUpsertBulk) SetUpdatedAt(v time.Time) *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsertBulk) UpdateUpdatedAt() *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeviceCodeHash sets the "device_code_hash" field.
func (u *OAuthDeviceCodeUpsertBulk) SetDeviceCodeHash(v string) *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.SetDeviceCodeHash(v)
	})
}

// UpdateDeviceCodeHash sets the "device_code_hash" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsertBulk) UpdateDeviceCodeHash() *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.UpdateDeviceCodeHash()
	})
}

// SetUserCodeHash sets the "user_code_hash" field.
func (u *OAuthDeviceCodeUpsertBulk) SetUserCodeHash(v string) *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.SetUserCodeHash(v)
	})
}

// UpdateUserCodeHash sets the "user_code_hash" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsertBulk) UpdateUserCodeHash() *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.UpdateUserCodeHash()
	})
}

// SetClientID sets the "client_id" field.
func (u *OAuthDeviceCodeUpsertBulk) SetClientID(v string) *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsertBulk) UpdateClientID() *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.UpdateClientID()
	})
}

// SetScopes sets the "scopes" field.
func (u *OAuthDeviceCodeUpsertBulk) SetScopes(v []string) *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.SetScopes(v)
	})
}

// UpdateScopes sets the "scopes" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsertBulk) UpdateScopes() *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.UpdateScopes()
	})
}

// SetGrantID sets the "grant_id" field.
func (u *OAuthDeviceCodeUpsertBulk) SetGrantID(v string) *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.SetGrantID(v)
	})
}

// UpdateGrantID sets the "grant_id" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsertBulk) UpdateGrantID() *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.UpdateGrantID()
	})
}

// ClearGrantID clears the value of the "grant_id" field.
func (u *OAuthDeviceCodeUpsertBulk) ClearGrantID() *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.ClearGrantID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *OAuthDeviceCodeUpsertBulk) SetGroupID(v int64) *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *OAuthDeviceCodeUpsertBulk) AddGroupID(v int64) *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsertBulk) UpdateGroupID() *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *OAuthDeviceCodeUpsertBulk) ClearGroupID() *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.ClearGroupID()
	})
}

// SetDeviceID sets the "device_id" field.
func (u *OAuthDeviceCodeUpsertBulk) SetDeviceID(v string) *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.SetDeviceID(v)
	})
}

// UpdateDeviceID sets the "device_id" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsertBulk) UpdateDeviceID() *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.UpdateDeviceID()
	})
}

// ClearDeviceID clears the value of the "device_id" field.
func (u *OAuthDeviceCodeUpsertBulk) ClearDeviceID() *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.ClearDeviceID()
	})
}

// SetDeviceName sets the "device_name" field.
func (u *OAuthDeviceCodeUpsertBulk) SetDeviceName(v string) *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.SetDeviceName(v)
	})
}

// UpdateDeviceName sets the "device_name" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsertBulk) UpdateDeviceName() *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.UpdateDeviceName()
	})
}

// ClearDeviceName clears the value of the "device_name" field.
func (u *OAuthDeviceCodeUpsertBulk) ClearDeviceName() *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.ClearDeviceName()
	})
}

// SetStatus sets the "status" field.
func (u *OAuthDeviceCodeUpsertBulk) SetStatus(v string) *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsertBulk) UpdateStatus() *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.UpdateStatus()
	})
}

// SetIntervalSeconds sets the "interval_seconds" field.
func (u *OAuthDeviceCodeUpsertBulk) SetIntervalSeconds(v int) *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.SetIntervalSeconds(v)
	})
}

// AddIntervalSeconds adds v to the "interval_seconds" field.
func (u *OAuthDeviceCodeUpsertBulk) AddIntervalSeconds(v int) *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.AddIntervalSeconds(v)
	})
}

// UpdateIntervalSeconds sets the "interval_seconds" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsertBulk) UpdateIntervalSeconds() *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.UpdateIntervalSeconds()
	})
}

// SetPollCount sets the "poll_count" field.
func (u *OAuthDeviceCodeUpsertBulk) SetPollCount(v int) *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.SetPollCount(v)
	})
}

// AddPollCount adds v to the "poll_count" field.
func (u *OAuthDeviceCodeUpsertBulk) AddPollCount(v int) *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.AddPollCount(v)
	})
}

// UpdatePollCount sets the "poll_count" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsertBulk) UpdatePollCount() *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.UpdatePollCount()
	})
}

// SetLastPollAt sets the "last_poll_at" field.
func (u *OAuthDeviceCodeUpsertBulk) SetLastPollAt(v time.Time) *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.SetLastPollAt(v)
	})
}

// UpdateLastPollAt sets the "last_poll_at" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsertBulk) UpdateLastPollAt() *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.UpdateLastPollAt()
	})
}

// ClearLastPollAt clears the value of the "last_poll_at" field.
func (u *OAuthDeviceCodeUpsertBulk) ClearLastPollAt() *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.ClearLastPollAt()
	})
}

// SetSlowDownCount sets the "slow_down_count" field.
func (u *OAuthDeviceCodeUpsertBulk) SetSlowDownCount(v int) *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.SetSlowDownCount(v)
	})
}

// AddSlowDownCount adds v to the "slow_down_count" field.
func (u *OAuthDeviceCodeUpsertBulk) AddSlowDownCount(v int) *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.AddSlowDownCount(v)
	})
}

// UpdateSlowDownCount sets the "slow_down_count" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsertBulk) UpdateSlowDownCount() *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.UpdateSlowDownCount()
	})
}

// SetFailedUserCodeAttempts sets the "failed_user_code_attempts" field.
func (u *OAuthDeviceCodeUpsertBulk) SetFailedUserCodeAttempts(v int) *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.SetFailedUserCodeAttempts(v)
	})
}

// AddFailedUserCodeAttempts adds v to the "failed_user_code_attempts" field.
func (u *OAuthDeviceCodeUpsertBulk) AddFailedUserCodeAttempts(v int) *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.AddFailedUserCodeAttempts(v)
	})
}

// UpdateFailedUserCodeAttempts sets the "failed_user_code_attempts" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsertBulk) UpdateFailedUserCodeAttempts() *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.UpdateFailedUserCodeAttempts()
	})
}

// SetApprovedByUserID sets the "approved_by_user_id" field.
func (u *OAuthDeviceCodeUpsertBulk) SetApprovedByUserID(v int64) *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.SetApprovedByUserID(v)
	})
}

// AddApprovedByUserID adds v to the "approved_by_user_id" field.
func (u *OAuthDeviceCodeUpsertBulk) AddApprovedByUserID(v int64) *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.AddApprovedByUserID(v)
	})
}

// UpdateApprovedByUserID sets the "approved_by_user_id" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsertBulk) UpdateApprovedByUserID() *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.UpdateApprovedByUserID()
	})
}

// ClearApprovedByUserID clears the value of the "approved_by_user_id" field.
func (u *OAuthDeviceCodeUpsertBulk) ClearApprovedByUserID() *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.ClearApprovedByUserID()
	})
}

// SetApprovedAt sets the "approved_at" field.
func (u *OAuthDeviceCodeUpsertBulk) SetApprovedAt(v time.Time) *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.SetApprovedAt(v)
	})
}

// UpdateApprovedAt sets the "approved_at" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsertBulk) UpdateApprovedAt() *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.UpdateApprovedAt()
	})
}

// ClearApprovedAt clears the value of the "approved_at" field.
func (u *OAuthDeviceCodeUpsertBulk) ClearApprovedAt() *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.ClearApprovedAt()
	})
}

// SetDeniedAt sets the "denied_at" field.
func (u *OAuthDeviceCodeUpsertBulk) SetDeniedAt(v time.Time) *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.SetDeniedAt(v)
	})
}

// UpdateDeniedAt sets the "denied_at" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsertBulk) UpdateDeniedAt() *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.UpdateDeniedAt()
	})
}

// ClearDeniedAt clears the value of the "denied_at" field.
func (u *OAuthDeviceCodeUpsertBulk) ClearDeniedAt() *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.ClearDeniedAt()
	})
}

// SetConsumedAt sets the "consumed_at" field.
func (u *OAuthDeviceCodeUpsertBulk) SetConsumedAt(v time.Time) *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.SetConsumedAt(v)
	})
}

// UpdateConsumedAt sets the "consumed_at" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsertBulk) UpdateConsumedAt() *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.UpdateConsumedAt()
	})
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (u *OAuthDeviceCodeUpsertBulk) ClearConsumedAt() *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.ClearConsumedAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *OAuthDeviceCodeUpsertBulk) SetExpiresAt(v time.Time) *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsertBulk) UpdateExpiresAt() *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetCreatedIP sets the "created_ip" field.
func (u *OAuthDeviceCodeUpsertBulk) SetCreatedIP(v string) *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.SetCreatedIP(v)
	})
}

// UpdateCreatedIP sets the "created_ip" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsertBulk) UpdateCreatedIP() *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.UpdateCreatedIP()
	})
}

// ClearCreatedIP clears the value of the "created_ip" field.
func (u *OAuthDeviceCodeUpsertBulk) ClearCreatedIP() *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.ClearCreatedIP()
	})
}

// SetCreatedUserAgent sets the "created_user_agent" field.
func (u *OAuthDeviceCodeUpsertBulk) SetCreatedUserAgent(v string) *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.SetCreatedUserAgent(v)
	})
}

// UpdateCreatedUserAgent sets the "created_user_agent" field to the value that was provided on create.
func (u *OAuthDeviceCodeUpsertBulk) UpdateCreatedUserAgent() *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.UpdateCreatedUserAgent()
	})
}

// ClearCreatedUserAgent clears the value of the "created_user_agent" field.
func (u *OAuthDeviceCodeUpsertBulk) ClearCreatedUserAgent() *OAuthDeviceCodeUpsertBulk {
	return u.Update(func(s *OAuthDeviceCodeUpsert) {
		s.ClearCreatedUserAgent()
	})
}

// Exec executes the query.
func (u *OAuthDeviceCodeUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OAuthDeviceCodeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OAuthDeviceCodeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OAuthDeviceCodeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
