// Code generated by ent, DO NOT EDIT.

package oauthauthorizetransaction

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the oauthauthorizetransaction type in the database.
	Label = "oauth_authorize_transaction"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldTransactionID holds the string denoting the transaction_id field in the database.
	FieldTransactionID = "transaction_id"
	// FieldCsrfHash holds the string denoting the csrf_hash field in the database.
	FieldCsrfHash = "csrf_hash"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldClientID holds the string denoting the client_id field in the database.
	FieldClientID = "client_id"
	// FieldRedirectURI holds the string denoting the redirect_uri field in the database.
	FieldRedirectURI = "redirect_uri"
	// FieldResponseType holds the string denoting the response_type field in the database.
	FieldResponseType = "response_type"
	// FieldScopes holds the string denoting the scopes field in the database.
	FieldScopes = "scopes"
	// FieldAllowedGroupsSnapshot holds the string denoting the allowed_groups_snapshot field in the database.
	FieldAllowedGroupsSnapshot = "allowed_groups_snapshot"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// FieldCodeChallenge holds the string denoting the code_challenge field in the database.
	FieldCodeChallenge = "code_challenge"
	// FieldCodeChallengeMethod holds the string denoting the code_challenge_method field in the database.
	FieldCodeChallengeMethod = "code_challenge_method"
	// FieldRequestedGroupID holds the string denoting the requested_group_id field in the database.
	FieldRequestedGroupID = "requested_group_id"
	// FieldDeviceID holds the string denoting the device_id field in the database.
	FieldDeviceID = "device_id"
	// FieldDeviceName holds the string denoting the device_name field in the database.
	FieldDeviceName = "device_name"
	// FieldConsumedAt holds the string denoting the consumed_at field in the database.
	FieldConsumedAt = "consumed_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldCreatedIP holds the string denoting the created_ip field in the database.
	FieldCreatedIP = "created_ip"
	// FieldCreatedUserAgent holds the string denoting the created_user_agent field in the database.
	FieldCreatedUserAgent = "created_user_agent"
	// Table holds the table name of the oauthauthorizetransaction in the database.
	Table = "oauth_authorize_transactions"
)

// Columns holds all SQL columns for oauthauthorizetransaction fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldTransactionID,
	FieldCsrfHash,
	FieldUserID,
	FieldClientID,
	FieldRedirectURI,
	FieldResponseType,
	FieldScopes,
	FieldAllowedGroupsSnapshot,
	FieldState,
	FieldCodeChallenge,
	FieldCodeChallengeMethod,
	FieldRequestedGroupID,
	FieldDeviceID,
	FieldDeviceName,
	FieldConsumedAt,
	FieldExpiresAt,
	FieldCreatedIP,
	FieldCreatedUserAgent,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// TransactionIDValidator is a validator for the "transaction_id" field. It is called by the builders before save.
	TransactionIDValidator func(string) error
	// CsrfHashValidator is a validator for the "csrf_hash" field. It is called by the builders before save.
	CsrfHashValidator func(string) error
	// ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	ClientIDValidator func(string) error
	// RedirectURIValidator is a validator for the "redirect_uri" field. It is called by the builders before save.
	RedirectURIValidator func(string) error
	// DefaultResponseType holds the default value on creation for the "response_type" field.
	DefaultResponseType string
	// ResponseTypeValidator is a validator for the "response_type" field. It is called by the builders before save.
	ResponseTypeValidator func(string) error
	// DefaultScopes holds the default value on creation for the "scopes" field.
	DefaultScopes []string
	// DefaultAllowedGroupsSnapshot holds the default value on creation for the "allowed_groups_snapshot" field.
	DefaultAllowedGroupsSnapshot []int64
	// CodeChallengeValidator is a validator for the "code_challenge" field. It is called by the builders before save.
	CodeChallengeValidator func(string) error
	// DefaultCodeChallengeMethod holds the default value on creation for the "code_challenge_method" field.
	DefaultCodeChallengeMethod string
	// CodeChallengeMethodValidator is a validator for the "code_challenge_method" field. It is called by the builders before save.
	CodeChallengeMethodValidator func(string) error
	// DeviceIDValidator is a validator for the "device_id" field. It is called by the builders before save.
	DeviceIDValidator func(string) error
	// DeviceNameValidator is a validator for the "device_name" field. It is called by the builders before save.
	DeviceNameValidator func(string) error
	// CreatedIPValidator is a validator for the "created_ip" field. It is called by the builders before save.
	CreatedIPValidator func(string) error
)

// OrderOption defines the ordering options for the OAuthAuthorizeTransaction queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTransactionID orders the results by the transaction_id field.
func ByTransactionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTransactionID, opts...).ToFunc()
}

// ByCsrfHash orders the results by the csrf_hash field.
func ByCsrfHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCsrfHash, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByClientID orders the results by the client_id field.
func ByClientID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientID, opts...).ToFunc()
}

// ByRedirectURI orders the results by the redirect_uri field.
func ByRedirectURI(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRedirectURI, opts...).ToFunc()
}

// ByResponseType orders the results by the response_type field.
func ByResponseType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponseType, opts...).ToFunc()
}

// ByState orders the results by the state field.
func ByState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldState, opts...).ToFunc()
}

// ByCodeChallenge orders the results by the code_challenge field.
func ByCodeChallenge(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCodeChallenge, opts...).ToFunc()
}

// ByCodeChallengeMethod orders the results by the code_challenge_method field.
func ByCodeChallengeMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCodeChallengeMethod, opts...).ToFunc()
}

// ByRequestedGroupID orders the results by the requested_group_id field.
func ByRequestedGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestedGroupID, opts...).ToFunc()
}

// ByDeviceID orders the results by the device_id field.
func ByDeviceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeviceID, opts...).ToFunc()
}

// ByDeviceName orders the results by the device_name field.
func ByDeviceName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeviceName, opts...).ToFunc()
}

// ByConsumedAt orders the results by the consumed_at field.
func ByConsumedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConsumedAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByCreatedIP orders the results by the created_ip field.
func ByCreatedIP(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedIP, opts...).ToFunc()
}

// ByCreatedUserAgent orders the results by the created_user_agent field.
func ByCreatedUserAgent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedUserAgent, opts...).ToFunc()
}
