// Code generated by ent, DO NOT EDIT.

package oauthaccesstoken

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the oauthaccesstoken type in the database.
	Label = "oauth_access_token"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldGrantID holds the string denoting the grant_id field in the database.
	FieldGrantID = "grant_id"
	// FieldTokenFamilyID holds the string denoting the token_family_id field in the database.
	FieldTokenFamilyID = "token_family_id"
	// FieldClientID holds the string denoting the client_id field in the database.
	FieldClientID = "client_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldScopes holds the string denoting the scopes field in the database.
	FieldScopes = "scopes"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldAllowedGroupsSnapshot holds the string denoting the allowed_groups_snapshot field in the database.
	FieldAllowedGroupsSnapshot = "allowed_groups_snapshot"
	// FieldAppType holds the string denoting the app_type field in the database.
	FieldAppType = "app_type"
	// FieldDeviceID holds the string denoting the device_id field in the database.
	FieldDeviceID = "device_id"
	// FieldDeviceName holds the string denoting the device_name field in the database.
	FieldDeviceName = "device_name"
	// FieldIssuedAt holds the string denoting the issued_at field in the database.
	FieldIssuedAt = "issued_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldLastUsedAt holds the string denoting the last_used_at field in the database.
	FieldLastUsedAt = "last_used_at"
	// FieldLastUsedIP holds the string denoting the last_used_ip field in the database.
	FieldLastUsedIP = "last_used_ip"
	// FieldLastUsedUserAgent holds the string denoting the last_used_user_agent field in the database.
	FieldLastUsedUserAgent = "last_used_user_agent"
	// FieldRevokedAt holds the string denoting the revoked_at field in the database.
	FieldRevokedAt = "revoked_at"
	// Table holds the table name of the oauthaccesstoken in the database.
	Table = "oauth_access_tokens"
)

// Columns holds all SQL columns for oauthaccesstoken fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldAPIKeyID,
	FieldGrantID,
	FieldTokenFamilyID,
	FieldClientID,
	FieldUserID,
	FieldScopes,
	FieldGroupID,
	FieldAllowedGroupsSnapshot,
	FieldAppType,
	FieldDeviceID,
	FieldDeviceName,
	FieldIssuedAt,
	FieldExpiresAt,
	FieldLastUsedAt,
	FieldLastUsedIP,
	FieldLastUsedUserAgent,
	FieldRevokedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// GrantIDValidator is a validator for the "grant_id" field. It is called by the builders before save.
	GrantIDValidator func(string) error
	// TokenFamilyIDValidator is a validator for the "token_family_id" field. It is called by the builders before save.
	TokenFamilyIDValidator func(string) error
	// ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	ClientIDValidator func(string) error
	// DefaultScopes holds the default value on creation for the "scopes" field.
	DefaultScopes []string
	// DefaultAllowedGroupsSnapshot holds the default value on creation for the "allowed_groups_snapshot" field.
	DefaultAllowedGroupsSnapshot []int64
	// DefaultAppType holds the default value on creation for the "app_type" field.
	DefaultAppType string
	// AppTypeValidator is a validator for the "app_type" field. It is called by the builders before save.
	AppTypeValidator func(string) error
	// DeviceIDValidator is a validator for the "device_id" field. It is called by the builders before save.
	DeviceIDValidator func(string) error
	// DeviceNameValidator is a validator for the "device_name" field. It is called by the builders before save.
	DeviceNameValidator func(string) error
	// LastUsedIPValidator is a validator for the "last_used_ip" field. It is called by the builders before save.
	LastUsedIPValidator func(string) error
)

// OrderOption defines the ordering options for the OAuthAccessToken queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// ByGrantID orders the results by the grant_id field.
func ByGrantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGrantID, opts...).ToFunc()
}

// ByTokenFamilyID orders the results by the token_family_id field.
func ByTokenFamilyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokenFamilyID, opts...).ToFunc()
}

// ByClientID orders the results by the client_id field.
func ByClientID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByAppType orders the results by the app_type field.
func ByAppType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAppType, opts...).ToFunc()
}

// ByDeviceID orders the results by the device_id field.
func ByDeviceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeviceID, opts...).ToFunc()
}

// ByDeviceName orders the results by the device_name field.
func ByDeviceName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeviceName, opts...).ToFunc()
}

// ByIssuedAt orders the results by the issued_at field.
func ByIssuedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIssuedAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByLastUsedAt orders the results by the last_used_at field.
func ByLastUsedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastUsedAt, opts...).ToFunc()
}

// ByLastUsedIP orders the results by the last_used_ip field.
func ByLastUsedIP(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastUsedIP, opts...).ToFunc()
}

// ByLastUsedUserAgent orders the results by the last_used_user_agent field.
func ByLastUsedUserAgent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastUsedUserAgent, opts...).ToFunc()
}

// ByRevokedAt orders the results by the revoked_at field.
func ByRevokedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevokedAt, opts...).ToFunc()
}
